<?php

/*
 * (c) Javier Eguiluz <javier.eguiluz@gmail.com>
 *
 * Este archivo pertenece a la aplicación de prueba Cupon.
 * El código fuente de la aplicación incluye un archivo llamado LICENSE
 * con toda la información sobre el copyright y la licencia.
 */

namespace Jaxxes\ResumeBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture; 
use Symfony\Component\DependencyInjection\ContainerAwareInterface;

use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerInterface;

use Jaxxes\GeneralBundle\Entity\Country;

/**
 * Fixtures de la entidad Resume.
 * Crea el registro de la cabecera para Resume = Ficha del candidato
 */
 
// class Resumes implements FixtureInterface
 class Contries extends AbstractFixture implements OrderedFixtureInterface
{
	
    public function getOrder()
    {
        return 1;
    }
    private $container;
    
    
    
    public function load(ObjectManager $manager)
    {
        // El registro inicial para la Ficha del postulante
        
         $lstCountries = array(	
								array('name'=>'Afghanistan','code'=>'AF'),
								array('name'=>'Albania','code'=>'AL'),
								array('name'=>'Algeria','code'=>'DZ'),
								array('name'=>'AmericanSamoa','code'=>'AS'),
								array('name'=>'Andorra','code'=>'AD'),
								array('name'=>'Angola','code'=>'AO'),
								array('name'=>'Anguilla','code'=>'AI'),
								array('name'=>'Antarctica','code'=>'AQ'),
								array('name'=>'AntiguaandBarbuda','code'=>'AG'),
								array('name'=>'Argentina','code'=>'AR'),
								array('name'=>'Armenia','code'=>'AM'),
								array('name'=>'Aruba','code'=>'AW'),
								array('name'=>'Australia','code'=>'AU'),
								array('name'=>'Austria','code'=>'AT'),
								array('name'=>'Azerbaijan','code'=>'AZ'),
								array('name'=>'Bahamas','code'=>'BS'),
								array('name'=>'Bahrain','code'=>'BH'),
								array('name'=>'Bangladesh','code'=>'BD'),
								array('name'=>'Barbados','code'=>'BB'),
								array('name'=>'Belarus','code'=>'BY'),
								array('name'=>'Belgium','code'=>'BE'),
								array('name'=>'Belize','code'=>'BZ'),
								array('name'=>'Benin','code'=>'BJ'),
								array('name'=>'Bermuda','code'=>'BM'),
								array('name'=>'Bhutan','code'=>'BT'),
								array('name'=>'Bolivia','code'=>'BO'),
								array('name'=>'BosniaandHerzegovina','code'=>'BA'),
								array('name'=>'Botswana','code'=>'BW'),
								array('name'=>'Brazil','code'=>'BR'),
								array('name'=>'BritishIndianOceanTerritory','code'=>'IO'),
								array('name'=>'BritishVirginIslands','code'=>'VG'),
								array('name'=>'Brunei','code'=>'BN'),
								array('name'=>'Bulgaria','code'=>'BG'),
								array('name'=>'BurkinaFaso','code'=>'BF'),
								array('name'=>'Burma(Myanmar)','code'=>'MM'),
								array('name'=>'Burundi','code'=>'BI'),
								array('name'=>'Cambodia','code'=>'KH'),
								array('name'=>'Cameroon','code'=>'CM'),
								array('name'=>'Canada','code'=>'CA'),
								array('name'=>'CapeVerde','code'=>'CV'),
								array('name'=>'CaymanIslands','code'=>'KY'),
								array('name'=>'CentralAfricanRepublic','code'=>'CF'),
								array('name'=>'Chad','code'=>'TD'),
								array('name'=>'Chile','code'=>'CL'),
								array('name'=>'China','code'=>'CN'),
								array('name'=>'ChristmasIsland','code'=>'CX'),
								array('name'=>'Cocos(Keeling)Islands','code'=>'CC'),
								array('name'=>'Colombia','code'=>'CO'),
								array('name'=>'Comoros','code'=>'KM'),
								array('name'=>'CookIslands','code'=>'CK'),
								array('name'=>'CostaRica','code'=>'CR'),
								array('name'=>'Croatia','code'=>'HR'),
								array('name'=>'Cuba','code'=>'CU'),
								array('name'=>'Cyprus','code'=>'CY'),
								array('name'=>'CzechRepublic','code'=>'CZ'),
								array('name'=>'DemocraticRepublicoftheCongo','code'=>'CD'),
								array('name'=>'Denmark','code'=>'DK'),
								array('name'=>'Djibouti','code'=>'DJ'),
								array('name'=>'Dominica','code'=>'DM'),
								array('name'=>'DominicanRepublic','code'=>'DO'),
								array('name'=>'Ecuador','code'=>'EC'),
								array('name'=>'Egypt','code'=>'EG'),
								array('name'=>'ElSalvador','code'=>'SV'),
								array('name'=>'EquatorialGuinea','code'=>'GQ'),
								array('name'=>'Eritrea','code'=>'ER'),
								array('name'=>'Estonia','code'=>'EE'),
								array('name'=>'Ethiopia','code'=>'ET'),
								array('name'=>'FalklandIslands','code'=>'FK'),
								array('name'=>'FaroeIslands','code'=>'FO'),
								array('name'=>'Fiji','code'=>'FJ'),
								array('name'=>'Finland','code'=>'FI'),
								array('name'=>'France','code'=>'FR'),
								array('name'=>'FrenchPolynesia','code'=>'PF'),
								array('name'=>'Gabon','code'=>'GA'),
								array('name'=>'Gambia','code'=>'GM'),
								array('name'=>'GazaStrip','code'=>'/'),
								array('name'=>'Georgia','code'=>'GE'),
								array('name'=>'Germany','code'=>'DE'),
								array('name'=>'Ghana','code'=>'GH'),
								array('name'=>'Gibraltar','code'=>'GI'),
								array('name'=>'Greece','code'=>'GR'),
								array('name'=>'Greenland','code'=>'GL'),
								array('name'=>'Grenada','code'=>'GD'),
								array('name'=>'Guam','code'=>'GU'),
								array('name'=>'Guatemala','code'=>'GT'),
								array('name'=>'Guinea','code'=>'GN'),
								array('name'=>'Guinea-Bissau','code'=>'GW'),
								array('name'=>'Guyana','code'=>'GY'),
								array('name'=>'Haiti','code'=>'HT'),
								array('name'=>'HolySee(VaticanCity)','code'=>'VA'),
								array('name'=>'Honduras','code'=>'HN'),
								array('name'=>'HongKong','code'=>'HK'),
								array('name'=>'Hungary','code'=>'HU'),
								array('name'=>'Iceland','code'=>'IS'),
								array('name'=>'India','code'=>'IN'),
								array('name'=>'Indonesia','code'=>'ID'),
								array('name'=>'Iran','code'=>'IR'),
								array('name'=>'Iraq','code'=>'IQ'),
								array('name'=>'Ireland','code'=>'IE'),
								array('name'=>'IsleofMan','code'=>'IM'),
								array('name'=>'Israel','code'=>'IL'),
								array('name'=>'Italy','code'=>'IT'),
								array('name'=>'IvoryCoast','code'=>'CI'),
								array('name'=>'Jamaica','code'=>'JM'),
								array('name'=>'Japan','code'=>'JP'),
								array('name'=>'Jersey','code'=>'JE'),
								array('name'=>'Jordan','code'=>'JO'),
								array('name'=>'Kazakhstan','code'=>'KZ'),
								array('name'=>'Kenya','code'=>'KE'),
								array('name'=>'Kiribati','code'=>'KI'),
								array('name'=>'Kosovo','code'=>'/'),
								array('name'=>'Kuwait','code'=>'KW'),
								array('name'=>'Kyrgyzstan','code'=>'KG'),
								array('name'=>'Laos','code'=>'LA'),
								array('name'=>'Latvia','code'=>'LV'),
								array('name'=>'Lebanon','code'=>'LB'),
								array('name'=>'Lesotho','code'=>'LS'),
								array('name'=>'Liberia','code'=>'LR'),
								array('name'=>'Libya','code'=>'LY'),
								array('name'=>'Liechtenstein','code'=>'LI'),
								array('name'=>'Lithuania','code'=>'LT'),
								array('name'=>'Luxembourg','code'=>'LU'),
								array('name'=>'Macau','code'=>'MO'),
								array('name'=>'Macedonia','code'=>'MK'),
								array('name'=>'Madagascar','code'=>'MG'),
								array('name'=>'Malawi','code'=>'MW'),
								array('name'=>'Malaysia','code'=>'MY'),
								array('name'=>'Maldives','code'=>'MV'),
								array('name'=>'Mali','code'=>'ML'),
								array('name'=>'Malta','code'=>'MT'),
								array('name'=>'MarshallIslands','code'=>'MH'),
								array('name'=>'Mauritania','code'=>'MR'),
								array('name'=>'Mauritius','code'=>'MU'),
								array('name'=>'Mayotte','code'=>'YT'),
								array('name'=>'Mexico','code'=>'MX'),
								array('name'=>'Micronesia','code'=>'FM'),
								array('name'=>'Moldova','code'=>'MD'),
								array('name'=>'Monaco','code'=>'MC'),
								array('name'=>'Mongolia','code'=>'MN'),
								array('name'=>'Montenegro','code'=>'ME'),
								array('name'=>'Montserrat','code'=>'MS'),
								array('name'=>'Morocco','code'=>'MA'),
								array('name'=>'Mozambique','code'=>'MZ'),
								array('name'=>'Namibia','code'=>'NA'),
								array('name'=>'Nauru','code'=>'NR'),
								array('name'=>'Nepal','code'=>'NP'),
								array('name'=>'Netherlands','code'=>'NL'),
								array('name'=>'NetherlandsAntilles','code'=>'AN'),
								array('name'=>'NewCaledonia','code'=>'NC'),
								array('name'=>'NewZealand','code'=>'NZ'),
								array('name'=>'Nicaragua','code'=>'NI'),
								array('name'=>'Niger','code'=>'NE'),
								array('name'=>'Nigeria','code'=>'NG'),
								array('name'=>'Niue','code'=>'NU'),
								array('name'=>'NorfolkIsland','code'=>'/'),
								array('name'=>'NorthKorea','code'=>'KP'),
								array('name'=>'NorthernMarianaIslands','code'=>'MP'),
								array('name'=>'Norway','code'=>'NO'),
								array('name'=>'Oman','code'=>'OM'),
								array('name'=>'Pakistan','code'=>'PK'),
								array('name'=>'Palau','code'=>'PW'),
								array('name'=>'Panama','code'=>'PA'),
								array('name'=>'PapuaNewGuinea','code'=>'PG'),
								array('name'=>'Paraguay','code'=>'PY'),
								array('name'=>'Peru','code'=>'PE'),
								array('name'=>'Philippines','code'=>'PH'),
								array('name'=>'PitcairnIslands','code'=>'PN'),
								array('name'=>'Poland','code'=>'PL'),
								array('name'=>'Portugal','code'=>'PT'),
								array('name'=>'PuertoRico','code'=>'PR'),
								array('name'=>'Qatar','code'=>'QA'),
								array('name'=>'RepublicoftheCongo','code'=>'CG'),
								array('name'=>'Romania','code'=>'RO'),
								array('name'=>'Russia','code'=>'RU'),
								array('name'=>'Rwanda','code'=>'RW'),
								array('name'=>'SaintBarthelemy','code'=>'BL'),
								array('name'=>'SaintHelena','code'=>'SH'),
								array('name'=>'SaintKittsandNevis','code'=>'KN'),
								array('name'=>'SaintLucia','code'=>'LC'),
								array('name'=>'SaintMartin','code'=>'MF'),
								array('name'=>'SaintPierreandMiquelon','code'=>'PM'),
								array('name'=>'SaintVincentandtheGrenadines','code'=>'VC'),
								array('name'=>'Samoa','code'=>'WS'),
								array('name'=>'SanMarino','code'=>'SM'),
								array('name'=>'SaoTomeandPrincipe','code'=>'ST'),
								array('name'=>'SaudiArabia','code'=>'SA'),
								array('name'=>'Senegal','code'=>'SN'),
								array('name'=>'Serbia','code'=>'RS'),
								array('name'=>'Seychelles','code'=>'SC'),
								array('name'=>'SierraLeone','code'=>'SL'),
								array('name'=>'Singapore','code'=>'SG'),
								array('name'=>'Slovakia','code'=>'SK'),
								array('name'=>'Slovenia','code'=>'SI'),
								array('name'=>'SolomonIslands','code'=>'SB'),
								array('name'=>'Somalia','code'=>'SO'),
								array('name'=>'SouthAfrica','code'=>'ZA'),
								array('name'=>'SouthKorea','code'=>'KR'),
								array('name'=>'Spain','code'=>'ES'),
								array('name'=>'SriLanka','code'=>'LK'),
								array('name'=>'Sudan','code'=>'SD'),
								array('name'=>'Suriname','code'=>'SR'),
								array('name'=>'Svalbard','code'=>'SJ'),
								array('name'=>'Swaziland','code'=>'SZ'),
								array('name'=>'Sweden','code'=>'SE'),
								array('name'=>'Switzerland','code'=>'CH'),
								array('name'=>'Syria','code'=>'SY'),
								array('name'=>'Taiwan','code'=>'TW'),
								array('name'=>'Tajikistan','code'=>'TJ'),
								array('name'=>'Tanzania','code'=>'TZ'),
								array('name'=>'Thailand','code'=>'TH'),
								array('name'=>'Timor-Leste','code'=>'TL'),
								array('name'=>'Togo','code'=>'TG'),
								array('name'=>'Tokelau','code'=>'TK'),
								array('name'=>'Tonga','code'=>'TO'),
								array('name'=>'TrinidadandTobago','code'=>'TT'),
								array('name'=>'Tunisia','code'=>'TN'),
								array('name'=>'Turkey','code'=>'TR'),
								array('name'=>'Turkmenistan','code'=>'TM'),
								array('name'=>'TurksandCaicosIslands','code'=>'TC'),
								array('name'=>'Tuvalu','code'=>'TV'),
								array('name'=>'Uganda','code'=>'UG'),
								array('name'=>'Ukraine','code'=>'UA'),
								array('name'=>'UnitedArabEmirates','code'=>'AE'),
								array('name'=>'UnitedKingdom','code'=>'GB'),
								array('name'=>'UnitedStates','code'=>'US'),
								array('name'=>'Uruguay','code'=>'UY'),
								array('name'=>'USVirginIslands','code'=>'VI'),
								array('name'=>'Uzbekistan','code'=>'UZ'),
								array('name'=>'Vanuatu','code'=>'VU'),
								array('name'=>'Venezuela','code'=>'VE'),
								array('name'=>'Vietnam','code'=>'VN'),
								array('name'=>'WallisandFutuna','code'=>'WF'),
								array('name'=>'WestBank','code'=>'/'),
								array('name'=>'WesternSahara','code'=>'EH'),
								array('name'=>'Yemen','code'=>'YE'),
								array('name'=>'Zambia','code'=>'ZM'),
								array('name'=>'Zimbabwe','code'=>'ZW'),							
							);
        
        foreach ($lstCountries as $lst) {
            $objeto = new Country();
            $objeto->setName($lst['name']);
            $objeto->setCode($lst['code']);
            $manager->persist($objeto);            
        }        
        $manager->flush();
    }
}
