parameters:
#    test_gatb.example.class: Jaxxes\TestGatbBundle\Example

services:
#    test_gatb.example:
#        class: %test_gatb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
