parameters:
#    test_pma.example.class: Jaxxes\TestPmaBundle\Example

services:
#    test_pma.example:
#        class: %test_pma.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
