parameters:
#    definition_test.example.class: Jaxxes\DefinitionTestBundle\Example

services:
#    definition_test.example:
#        class: %definition_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
