security:
      
    role_hierarchy:
        ROLE_ADMIN: [ROLE_CONSULTANT, ROLE_USUARIO]
        
    firewalls:
        backend:
            pattern:        ^/admin
            provider:       administradores
            http_basic:     ~
 
        # Firewall de la extranet a la que se conectan los consultores
        extranet:
            pattern:        ^/proceso/consultor
            provider:       consultor
            anonymous:      ~
            form_login:
                login_path: consultor_login
                check_path: consultor_login_check
            logout:
                path:       consultor_logout
                target:     consultor_login
        frontend:
            pattern: ^/*
            provider:    usuarios
            anonymous: ~            
            form_login:                
                login_path: candidate_login
                check_path: candidate_login_check               
                #use_referer: true
                default_target_path: candidate_login_check
                #always_use_default_target_path :  true
                #target_path_parameter: candidate_bienvenida
                #failure_path: login_failure
                # post_only: true
                #username_parameter: _userCandidate 
                #password_parameter: _password

            logout:
                path: candidate_logout
                target: candidate_login
            remember_me:
                key:        cupon1234
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/candidate/sp/welcome, roles: ROLE_USUARIO }
        - { path: ^/gatb, roles: ROLE_USUARIO }  
        - { path: ^/rol/candidate/perfil, roles: ROLE_USUARIO }  
        #- { path: ^/rol/registerdefinitionrol/*, roles: ROLE_CONSULTANT }
        #- { path: ^/nivel/*, roles: ROLE_CONSULTANT }
        #- { path: ^/proceso/sp_consultor/*, roles: ROLE_CONSULTANT }
        #- { path: ^/enterprise/*, roles: ROLE_CONSULTANT }
        #- { path: ^/candidate/*, roles: ROLE_CONSULTANT }        
        - { path: ^/admin/*,         roles: ROLE_ADMIN }

    providers:
        usuarios:
            entity: { class: Jaxxes\SeleccionProcesBundle\Entity\SelectionProcessCandidate, property:usercandidate }
        consultor:
            entity: { class: Jaxxes\SeleccionProcesBundle\Entity\Consultant, property: login }                 
        administradores:
            memory:
                users:
                    eka: { password: 111, roles: ROLE_ADMIN }                    
        
    encoders:        
        Symfony\Component\Security\Core\User\User: plaintext # usado para el login del administrador  
        #Jaxxes\SeleccionProcesBundle\Entity\SelectionProcessCandidate: plaintext
        Jaxxes\SeleccionProcesBundle\Entity\SelectionProcessCandidate: { algorithm: sha512, iterations: 10 }
        Jaxxes\SeleccionProcesBundle\Entity\Consultant: { algorithm: sha512, iterations: 10 }        
