parameters:
#    enterprise.example.class: Jaxxes\EnterpriseBundle\Example

services:
#    enterprise.example:
#        class: %enterprise.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
