parameters:
#    seleccion_proces.example.class: Jaxxes\SeleccionProcesBundle\Example

services:
#    seleccion_proces.example:
#        class: %seleccion_proces.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
