parameters:
#    test_gatb_sp.example.class: Jaxxes\TestGatbSPBundle\Example

services:
#    test_gatb_sp.example:
#        class: %test_gatb_sp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
