<?php

namespace Jaxxes\TestICEBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture; 
use Symfony\Component\DependencyInjection\ContainerAwareInterface;

use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerInterface;

use Jaxxes\TestICEBundle\Entity\ICEF4100Baremo;

/**
 * Fixtures de la entidad Resume.
 * Crea el registro de la cabecera para Resume = Ficha del candidato
 */
 
// class Resumes implements FixtureInterface
 class ICEF4100Baremos extends AbstractFixture implements OrderedFixtureInterface
{
	
    public function getOrder()
    {
        return 4;
    }
    private $container;
    
    
    
    public function load(ObjectManager $manager)
    {
        $lstStructure = array(
			array('typeScale'=>'IMP','pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),
			array('typeScale'=>'IMP','pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'77'),
			array('typeScale'=>'IMP','pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'81'),
			array('typeScale'=>'IMP','pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'82'),
			array('typeScale'=>'IMP','pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'90'),
			array('typeScale'=>'IMP','pdMin'=>'21', 'pdMax'=>'22', 'ce'=>'92'),
			array('typeScale'=>'IMP','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'98'),
			array('typeScale'=>'IMP','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'100'),
			array('typeScale'=>'IMP','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'103'),
			array('typeScale'=>'IMP','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'107'),
			array('typeScale'=>'IMP','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'109'),
			array('typeScale'=>'IMP','pdMin'=>'28', 'pdMax'=>'30', 'ce'=>'113'),
			array('typeScale'=>'IMP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'114'),
			array('typeScale'=>'IMP','pdMin'=>'32', 'pdMax'=>'33', 'ce'=>'118'),
			array('typeScale'=>'IMP','pdMin'=>'34', 'pdMax'=>'35', 'ce'=>'119'),
			array('typeScale'=>'IMP','pdMin'=>'36', 'pdMax'=>'40', 'ce'=>'120'),
			array('typeScale'=>'IMN','pdMin'=>'0', 'pdMax'=>'7', 'ce'=>'65'),
			array('typeScale'=>'IMN','pdMin'=>'8', 'pdMax'=>'8', 'ce'=>'96'),
			array('typeScale'=>'IMN','pdMin'=>'9', 'pdMax'=>'9', 'ce'=>'100'),
			array('typeScale'=>'IMN','pdMin'=>'10', 'pdMax'=>'10', 'ce'=>'113'),
			array('typeScale'=>'IMN','pdMin'=>'11', 'pdMax'=>'11', 'ce'=>'116'),
			array('typeScale'=>'IMN','pdMin'=>'12', 'pdMax'=>'12', 'ce'=>'119'),
			array('typeScale'=>'IMN','pdMin'=>'13', 'pdMax'=>'35', 'ce'=>'124'),        	
			array('typeScale'=>'CM', 'pdMin'=>'0', 'pdMax'=>'22', 'ce'=>'65'),
			array('typeScale'=>'CM', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'75'),
			array('typeScale'=>'CM', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'77'),
			array('typeScale'=>'CM', 'pdMin'=>'25', 'pdMax'=>'26', 'ce'=>'78'),
			array('typeScale'=>'CM', 'pdMin'=>'27', 'pdMax'=>'29', 'ce'=>'85'),
			array('typeScale'=>'CM', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'90'),
			array('typeScale'=>'CM', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'94'),
			array('typeScale'=>'CM', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'98'),
			array('typeScale'=>'CM', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'101'),
			array('typeScale'=>'CM', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'107'),
			array('typeScale'=>'CM', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'109'),
			array('typeScale'=>'CM', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'111'),
			array('typeScale'=>'CM', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'119'),
			array('typeScale'=>'CM', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'123'),
			array('typeScale'=>'CM', 'pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'124'),						
			array('typeScale'=>'SE', 'pdMin'=>'0', 'pdMax'=>'19', 'ce'=>'65'),
			array('typeScale'=>'SE', 'pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'75'),
			array('typeScale'=>'SE', 'pdMin'=>'21', 'pdMax'=>'22', 'ce'=>'77'),
			array('typeScale'=>'SE', 'pdMin'=>'23', 'pdMax'=>'25', 'ce'=>'78'),
			array('typeScale'=>'SE', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'82'),
			array('typeScale'=>'SE', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'88'),
			array('typeScale'=>'SE', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'98'),
			array('typeScale'=>'SE', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'101'),
			array('typeScale'=>'SE', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'103'),
			array('typeScale'=>'SE', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'116'),
			array('typeScale'=>'SE', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'123'),
			array('typeScale'=>'SE', 'pdMin'=>'33', 'pdMax'=>'35', 'ce'=>'124'),
			array('typeScale'=>'AE', 'pdMin'=>'0', 'pdMax'=>'34', 'ce'=>'65'),
			array('typeScale'=>'AE', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'77'),
			array('typeScale'=>'AE', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'82'),
			array('typeScale'=>'AE', 'pdMin'=>'37', 'pdMax'=>'38', 'ce'=>'85'),
			array('typeScale'=>'AE', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'90'),
			array('typeScale'=>'AE', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'92'),
			array('typeScale'=>'AE', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'98'),
			array('typeScale'=>'AE', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'100'),
			array('typeScale'=>'AE', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'103'),
			array('typeScale'=>'AE', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'109'),
			array('typeScale'=>'AE', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'119'),
			array('typeScale'=>'AR', 'pdMin'=>'0', 'pdMax'=>'38', 'ce'=>'65'),
			array('typeScale'=>'AR', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'78'),
			array('typeScale'=>'AR', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'88'),
			array('typeScale'=>'AR', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'98'),
			array('typeScale'=>'AR', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'107'),
			array('typeScale'=>'AR', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'113'),
			array('typeScale'=>'AR', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'114'),
			array('typeScale'=>'AR', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'124'),
			array('typeScale'=>'IN', 'pdMin'=>'0', 'pdMax'=>'25', 'ce'=>'65'),
			array('typeScale'=>'IN', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'77'),
			array('typeScale'=>'IN', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'82'),
			array('typeScale'=>'IN', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'90'),
			array('typeScale'=>'IN', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'102'),
			array('typeScale'=>'IN', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'111'),
			array('typeScale'=>'IN', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'119'),
			array('typeScale'=>'IN', 'pdMin'=>'32', 'pdMax'=>'35', 'ce'=>'124'),
			array('typeScale'=>'RI', 'pdMin'=>'0', 'pdMax'=>'38', 'ce'=>'65'),
			array('typeScale'=>'RI', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'77'),
			array('typeScale'=>'RI', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'78'),
			array('typeScale'=>'RI', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'81'),
			array('typeScale'=>'RI', 'pdMin'=>'42', 'pdMax'=>'43', 'ce'=>'82'),
			array('typeScale'=>'RI', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'88'),
			array('typeScale'=>'RI', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'92'),
			array('typeScale'=>'RI', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'96'),
			array('typeScale'=>'RI', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'101'),
			array('typeScale'=>'RI', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'103'),
			array('typeScale'=>'RI', 'pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'111'),
			array('typeScale'=>'RI', 'pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'113'),
			array('typeScale'=>'RI', 'pdMin'=>'51', 'pdMax'=>'51', 'ce'=>'119'),
			array('typeScale'=>'RI', 'pdMin'=>'52', 'pdMax'=>'51', 'ce'=>'123'),
			array('typeScale'=>'RI', 'pdMin'=>'53', 'pdMax'=>'55', 'ce'=>'124'),
			array('typeScale'=>'RS', 'pdMin'=>'0', 'pdMax'=>'38', 'ce'=>'65'),
			array('typeScale'=>'RS', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'82'),
			array('typeScale'=>'RS', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'85'),
			array('typeScale'=>'RS', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'92'),
			array('typeScale'=>'RS', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'94'),
			array('typeScale'=>'RS', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'96'),
			array('typeScale'=>'RS', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'100'),
			array('typeScale'=>'RS', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'101'),
			array('typeScale'=>'RS', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'103'),
			array('typeScale'=>'RS', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'109'),
			array('typeScale'=>'RS', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'116'),
			array('typeScale'=>'RS', 'pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'120'),
			array('typeScale'=>'RS', 'pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'124'),
			array('typeScale'=>'EM','pdMin'=>'0', 'pdMax'=>'25', 'ce'=>'65'),  
			array('typeScale'=>'EM','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'77'), 
			array('typeScale'=>'EM','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'78'), 
			array('typeScale'=>'EM','pdMin'=>'28', 'pdMax'=>'29', 'ce'=>'88'), 
			array('typeScale'=>'EM','pdMin'=>'30', 'pdMax'=>'31', 'ce'=>'90'), 
			array('typeScale'=>'EM','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'92'), 
			array('typeScale'=>'EM','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'98'), 
			array('typeScale'=>'EM','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'100'), 
			array('typeScale'=>'EM','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'103'),
			array('typeScale'=>'EM','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'111'),
			array('typeScale'=>'EM','pdMin'=>'37', 'pdMax'=>'40', 'ce'=>'116'),
			array('typeScale'=>'SP','pdMin'=>'0', 'pdMax'=>'23', 'ce'=>'65'),  
			array('typeScale'=>'SP','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'75'), 
			array('typeScale'=>'SP','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'77'), 
			array('typeScale'=>'SP','pdMin'=>'26', 'pdMax'=>'27', 'ce'=>'78'), 
			array('typeScale'=>'SP','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'83'), 
			array('typeScale'=>'SP','pdMin'=>'29', 'pdMax'=>'30', 'ce'=>'85'), 
			array('typeScale'=>'SP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'88'), 
			array('typeScale'=>'SP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'94'), 
			array('typeScale'=>'SP','pdMin'=>'33', 'pdMax'=>'35', 'ce'=>'98'),
			array('typeScale'=>'SP','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'103'),
			array('typeScale'=>'SP','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'105'),
			array('typeScale'=>'SP','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'107'),
			array('typeScale'=>'SP','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'113'),
			array('typeScale'=>'SP','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'119'),
			array('typeScale'=>'PR','pdMin'=>'0', 'pdMax'=>'36', 'ce'=>'65'),  
			array('typeScale'=>'PR','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'77'), 
			array('typeScale'=>'PR','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'82'), 
			array('typeScale'=>'PR','pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'85'), 
			array('typeScale'=>'PR','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'90'), 
			array('typeScale'=>'PR','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'92'), 
			array('typeScale'=>'PR','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'98'), 
			array('typeScale'=>'PR','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'101'), 
			array('typeScale'=>'PR','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'105'), 
			array('typeScale'=>'PR','pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'111'),
			array('typeScale'=>'PR','pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'116'),
			array('typeScale'=>'PR','pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'123'),
			array('typeScale'=>'PR','pdMin'=>'49', 'pdMax'=>'50', 'ce'=>'124'),
			array('typeScale'=>'FL','pdMin'=>'0', 'pdMax'=>'20', 'ce'=>'65'),  
			array('typeScale'=>'FL','pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'75'), 
			array('typeScale'=>'FL','pdMin'=>'22', 'pdMax'=>'23', 'ce'=>'77'), 
			array('typeScale'=>'FL','pdMin'=>'24', 'pdMax'=>'25', 'ce'=>'78'), 
			array('typeScale'=>'FL','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'81'), 
			array('typeScale'=>'FL','pdMin'=>'27', 'pdMax'=>'28', 'ce'=>'82'), 
			array('typeScale'=>'FL','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'88'), 
			array('typeScale'=>'FL','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'90'), 
			array('typeScale'=>'FL','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'92'), 
			array('typeScale'=>'FL','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'96'), 
			array('typeScale'=>'FL','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'103'),
			array('typeScale'=>'FL','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'109'),
			array('typeScale'=>'FL','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'113'),
			array('typeScale'=>'FL','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'123'),
			array('typeScale'=>'FL','pdMin'=>'37', 'pdMax'=>'40', 'ce'=>'124'),
			array('typeScale'=>'TT','pdMin'=>'0', 'pdMax'=>'27', 'ce'=>'65'),    
			array('typeScale'=>'TT','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'75'),   
			array('typeScale'=>'TT','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'77'),   
			array('typeScale'=>'TT','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'78'),   
			array('typeScale'=>'TT','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'81'),   
			array('typeScale'=>'TT','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'82'),   
			array('typeScale'=>'TT','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'85'),   
			array('typeScale'=>'TT','pdMin'=>'34', 'pdMax'=>'35', 'ce'=>'88'),   
			array('typeScale'=>'TT','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'96'),   
			array('typeScale'=>'TT','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'100'),   
			array('typeScale'=>'TT','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'103'),   
			array('typeScale'=>'TT','pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'109'),   
			array('typeScale'=>'TT','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'113'),   
			array('typeScale'=>'TT','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'116'),   
			array('typeScale'=>'TT','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'118'),  
			array('typeScale'=>'TT','pdMin'=>'44', 'pdMax'=>'45', 'ce'=>'120'),  
			array('typeScale'=>'CI','pdMin'=>'0', 'pdMax'=>'25', 'ce'=>'65'),   
			array('typeScale'=>'CI','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'77'),  
			array('typeScale'=>'CI','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'81'),  
			array('typeScale'=>'CI','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'82'),  
			array('typeScale'=>'CI','pdMin'=>'29', 'pdMax'=>'32', 'ce'=>'85'),  
			array('typeScale'=>'CI','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'86'),  
			array('typeScale'=>'CI','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'88'),  
			array('typeScale'=>'CI','pdMin'=>'35', 'pdMax'=>'36', 'ce'=>'92'),  
			array('typeScale'=>'CI','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'94'),  
			array('typeScale'=>'CI','pdMin'=>'38', 'pdMax'=>'41', 'ce'=>'98'),  
			array('typeScale'=>'CI','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'105'),  
			array('typeScale'=>'CI','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'107'),  
			array('typeScale'=>'CI','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'113'),  
			array('typeScale'=>'CI','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'119'),  
			array('typeScale'=>'FE','pdMin'=>'0', 'pdMax'=>'29', 'ce'=>'65'),  
			array('typeScale'=>'FE','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'77'), 
			array('typeScale'=>'FE','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'87'), 
			array('typeScale'=>'FE','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'88'), 
			array('typeScale'=>'FE','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'90'), 
			array('typeScale'=>'FE','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'92'), 
			array('typeScale'=>'FE','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'94'), 
			array('typeScale'=>'FE','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'100'),
			array('typeScale'=>'FE','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'105'),
			array('typeScale'=>'FE','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'107'),
			array('typeScale'=>'FE','pdMin'=>'39', 'pdMax'=>'45', 'ce'=>'116'),
			array('typeScale'=>'OP','pdMin'=>'0', 'pdMax'=>'30', 'ce'=>'65'),   
			array('typeScale'=>'OP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'77'),  
			array('typeScale'=>'OP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'82'),  
			array('typeScale'=>'OP','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'88'),  
			array('typeScale'=>'OP','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'90'),  
			array('typeScale'=>'OP','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'96'),  
			array('typeScale'=>'OP','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'98'),  
			array('typeScale'=>'OP','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'105'),  
			array('typeScale'=>'OP','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'109'),  
			array('typeScale'=>'OP','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'113'),  
			array('typeScale'=>'OP','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'119'),  
			array('typeScale'=>'CERA','pdMin'=>'40', 'pdMax'=>'148', 'ce'=>'65'),  
			array('typeScale'=>'CERA','pdMin'=>'149', 'pdMax'=>'150', 'ce'=>'75'), 
			array('typeScale'=>'CERA','pdMin'=>'151', 'pdMax'=>'156', 'ce'=>'77'), 
			array('typeScale'=>'CERA','pdMin'=>'157', 'pdMax'=>'161', 'ce'=>'78'), 
			array('typeScale'=>'CERA','pdMin'=>'162', 'pdMax'=>'162', 'ce'=>'82'), 
			array('typeScale'=>'CERA','pdMin'=>'163', 'pdMax'=>'163', 'ce'=>'88'), 
			array('typeScale'=>'CERA','pdMin'=>'164', 'pdMax'=>'166', 'ce'=>'90'), 
			array('typeScale'=>'CERA','pdMin'=>'167', 'pdMax'=>'167', 'ce'=>'91'), 
			array('typeScale'=>'CERA','pdMin'=>'168', 'pdMax'=>'169', 'ce'=>'94'), 
			array('typeScale'=>'CERA','pdMin'=>'170', 'pdMax'=>'170', 'ce'=>'96'), 
			array('typeScale'=>'CERA','pdMin'=>'171', 'pdMax'=>'171', 'ce'=>'100'), 
			array('typeScale'=>'CERA','pdMin'=>'172', 'pdMax'=>'172', 'ce'=>'101'), 
			array('typeScale'=>'CERA','pdMin'=>'173', 'pdMax'=>'173', 'ce'=>'103'), 
			array('typeScale'=>'CERA','pdMin'=>'174', 'pdMax'=>'174', 'ce'=>'107'), 
			array('typeScale'=>'CERA','pdMin'=>'175', 'pdMax'=>'175', 'ce'=>'109'), 
			array('typeScale'=>'CERA','pdMin'=>'176', 'pdMax'=>'176', 'ce'=>'110'), 
			array('typeScale'=>'CERA','pdMin'=>'177', 'pdMax'=>'177', 'ce'=>'111'), 
			array('typeScale'=>'CERA','pdMin'=>'178', 'pdMax'=>'178', 'ce'=>'113'), 
			array('typeScale'=>'CERA','pdMin'=>'179', 'pdMax'=>'179', 'ce'=>'116'), 
			array('typeScale'=>'CERA','pdMin'=>'180', 'pdMax'=>'181', 'ce'=>'118'), 
			array('typeScale'=>'CERA','pdMin'=>'182', 'pdMax'=>'184', 'ce'=>'119'), 
			array('typeScale'=>'CERA','pdMin'=>'185', 'pdMax'=>'200', 'ce'=>'120'), 
			array('typeScale'=>'CEER','pdMin'=>'24', 'pdMax'=>'90', 'ce'=>'65'),   
			array('typeScale'=>'CEER','pdMin'=>'91', 'pdMax'=>'91', 'ce'=>'82'),   
			array('typeScale'=>'CEER','pdMin'=>'92', 'pdMax'=>'95', 'ce'=>'85'),   
			array('typeScale'=>'CEER','pdMin'=>'96', 'pdMax'=>'96', 'ce'=>'87'),   
			array('typeScale'=>'CEER','pdMin'=>'97', 'pdMax'=>'98', 'ce'=>'88'),   
			array('typeScale'=>'CEER','pdMin'=>'99', 'pdMax'=>'100', 'ce'=>'90'),   
			array('typeScale'=>'CEER','pdMin'=>'101', 'pdMax'=>'101', 'ce'=>'91'),   
			array('typeScale'=>'CEER','pdMin'=>'102', 'pdMax'=>'102', 'ce'=>'92'),   
			array('typeScale'=>'CEER','pdMin'=>'103', 'pdMax'=>'103', 'ce'=>'96'),   
			array('typeScale'=>'CEER','pdMin'=>'104', 'pdMax'=>'104', 'ce'=>'98'),   
			array('typeScale'=>'CEER','pdMin'=>'105', 'pdMax'=>'106', 'ce'=>'103'),   
			array('typeScale'=>'CEER','pdMin'=>'107', 'pdMax'=>'107', 'ce'=>'107'),  
			array('typeScale'=>'CEER','pdMin'=>'108', 'pdMax'=>'108', 'ce'=>'109'),
			array('typeScale'=>'CEER','pdMin'=>'109', 'pdMax'=>'110', 'ce'=>'113'),
			array('typeScale'=>'CEER','pdMin'=>'111', 'pdMax'=>'112', 'ce'=>'123'),
			array('typeScale'=>'CEER','pdMin'=>'113', 'pdMax'=>'114', 'ce'=>'124'),
			array('typeScale'=>'CEER','pdMin'=>'115', 'pdMax'=>'120', 'ce'=>'126'),
			array('typeScale'=>'CEAD','pdMin'=>'26', 'pdMax'=>'79', 'ce'=>'65'),       
			array('typeScale'=>'CEAD','pdMin'=>'80', 'pdMax'=>'81', 'ce'=>'75'),       
			array('typeScale'=>'CEAD','pdMin'=>'82', 'pdMax'=>'87', 'ce'=>'77'),       
			array('typeScale'=>'CEAD','pdMin'=>'88', 'pdMax'=>'93', 'ce'=>'78'),       
			array('typeScale'=>'CEAD','pdMin'=>'94', 'pdMax'=>'94', 'ce'=>'81'),       
			array('typeScale'=>'CEAD','pdMin'=>'95', 'pdMax'=>'97', 'ce'=>'82'),       
			array('typeScale'=>'CEAD','pdMin'=>'98', 'pdMax'=>'99', 'ce'=>'85'),       
			array('typeScale'=>'CEAD','pdMin'=>'100', 'pdMax'=>'100', 'ce'=>'87'),       
			array('typeScale'=>'CEAD','pdMin'=>'101', 'pdMax'=>'102', 'ce'=>'88'),       
			array('typeScale'=>'CEAD','pdMin'=>'103', 'pdMax'=>'104', 'ce'=>'90'),       
			array('typeScale'=>'CEAD','pdMin'=>'105', 'pdMax'=>'105', 'ce'=>'91'),       
			array('typeScale'=>'CEAD','pdMin'=>'106', 'pdMax'=>'106', 'ce'=>'94'),       
			array('typeScale'=>'CEAD','pdMin'=>'107', 'pdMax'=>'108', 'ce'=>'96'),       
			array('typeScale'=>'CEAD','pdMin'=>'109', 'pdMax'=>'110', 'ce'=>'98'),       
			array('typeScale'=>'CEAD','pdMin'=>'111', 'pdMax'=>'111', 'ce'=>'101'),       
			array('typeScale'=>'CEAD','pdMin'=>'112', 'pdMax'=>'113', 'ce'=>'103'),     
			array('typeScale'=>'CEAD','pdMin'=>'114', 'pdMax'=>'114', 'ce'=>'105'),     
			array('typeScale'=>'CEAD','pdMin'=>'115', 'pdMax'=>'115', 'ce'=>'109'),     
			array('typeScale'=>'CEAD','pdMin'=>'116', 'pdMax'=>'119', 'ce'=>'113'),    
			array('typeScale'=>'CEAD','pdMin'=>'120', 'pdMax'=>'120', 'ce'=>'114'),    
			array('typeScale'=>'CEAD','pdMin'=>'121', 'pdMax'=>'121', 'ce'=>'123'),    
			array('typeScale'=>'CEAD','pdMin'=>'122', 'pdMax'=>'130', 'ce'=>'124'),
			array('typeScale'=>'CEMT','pdMin'=>'18', 'pdMax'=>'52', 'ce'=>'65'),  
			array('typeScale'=>'CEMT','pdMin'=>'53', 'pdMax'=>'53', 'ce'=>'75'),  
			array('typeScale'=>'CEMT','pdMin'=>'54', 'pdMax'=>'55', 'ce'=>'77'),      
			array('typeScale'=>'CEMT','pdMin'=>'56', 'pdMax'=>'58', 'ce'=>'78'),  
			array('typeScale'=>'CEMT','pdMin'=>'59', 'pdMax'=>'59', 'ce'=>'82'),  
			array('typeScale'=>'CEMT','pdMin'=>'60', 'pdMax'=>'64', 'ce'=>'85'),  
			array('typeScale'=>'CEMT','pdMin'=>'65', 'pdMax'=>'65', 'ce'=>'86'),  
			array('typeScale'=>'CEMT','pdMin'=>'66', 'pdMax'=>'66', 'ce'=>'87'),  
			array('typeScale'=>'CEMT','pdMin'=>'67', 'pdMax'=>'70', 'ce'=>'88'),  
			array('typeScale'=>'CEMT','pdMin'=>'71', 'pdMax'=>'72', 'ce'=>'90'),  
			array('typeScale'=>'CEMT','pdMin'=>'73', 'pdMax'=>'73', 'ce'=>'92'),  
			array('typeScale'=>'CEMT','pdMin'=>'74', 'pdMax'=>'74', 'ce'=>'94'),  
			array('typeScale'=>'CEMT','pdMin'=>'75', 'pdMax'=>'76', 'ce'=>'96'),  
			array('typeScale'=>'CEMT','pdMin'=>'77', 'pdMax'=>'78', 'ce'=>'100'),  
			array('typeScale'=>'CEMT','pdMin'=>'79', 'pdMax'=>'79', 'ce'=>'103'),  
			array('typeScale'=>'CEMT','pdMin'=>'80', 'pdMax'=>'80', 'ce'=>'107'),  
			array('typeScale'=>'CEMT','pdMin'=>'81', 'pdMax'=>'83', 'ce'=>'109'),  
			array('typeScale'=>'CEMT','pdMin'=>'84', 'pdMax'=>'84', 'ce'=>'113'),  
			array('typeScale'=>'CEMT','pdMin'=>'85', 'pdMax'=>'85', 'ce'=>'119'),  
			array('typeScale'=>'CEMT','pdMin'=>'86', 'pdMax'=>'86', 'ce'=>'123'), 
			array('typeScale'=>'CEMT','pdMin'=>'87', 'pdMax'=>'90', 'ce'=>'124'), 
			array('typeScale'=>'CEAG','pdMin'=>'17', 'pdMax'=>'60', 'ce'=>'65'), 
			array('typeScale'=>'CEAG','pdMin'=>'61', 'pdMax'=>'61', 'ce'=>'75'), 
			array('typeScale'=>'CEAG','pdMin'=>'62', 'pdMax'=>'63', 'ce'=>'77'), 
			array('typeScale'=>'CEAG','pdMin'=>'64', 'pdMax'=>'65', 'ce'=>'78'), 
			array('typeScale'=>'CEAG','pdMin'=>'66', 'pdMax'=>'66', 'ce'=>'82'), 
			array('typeScale'=>'CEAG','pdMin'=>'67', 'pdMax'=>'67', 'ce'=>'85'), 
			array('typeScale'=>'CEAG','pdMin'=>'68', 'pdMax'=>'68', 'ce'=>'92'), 
			array('typeScale'=>'CEAG','pdMin'=>'69', 'pdMax'=>'70', 'ce'=>'96'), 
			array('typeScale'=>'CEAG','pdMin'=>'71', 'pdMax'=>'71', 'ce'=>'101'), 
			array('typeScale'=>'CEAG','pdMin'=>'72', 'pdMax'=>'72', 'ce'=>'106'), 
			array('typeScale'=>'CEAG','pdMin'=>'73', 'pdMax'=>'74', 'ce'=>'197'), 
			array('typeScale'=>'CEAG','pdMin'=>'75', 'pdMax'=>'76', 'ce'=>'113'), 
			array('typeScale'=>'CEAG','pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'114'), 
			array('typeScale'=>'CEAG','pdMin'=>'78', 'pdMax'=>'78', 'ce'=>'119'), 
			array('typeScale'=>'CEAG','pdMin'=>'79', 'pdMax'=>'85', 'ce'=>'124'),
			array('typeScale'=>'CETOTAL','pdMin'=>'117', 'pdMax'=>'414', 'ce'=>'65'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'415', 'pdMax'=>'421', 'ce'=>'75'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'422', 'pdMax'=>'441', 'ce'=>'77'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'442', 'pdMax'=>'461', 'ce'=>'78'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'462', 'pdMax'=>'463', 'ce'=>'81'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'464', 'pdMax'=>'469', 'ce'=>'82'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'470', 'pdMax'=>'471', 'ce'=>'85'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'472', 'pdMax'=>'472', 'ce'=>'87'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'473', 'pdMax'=>'475', 'ce'=>'88'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'476', 'pdMax'=>'476', 'ce'=>'90'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'477', 'pdMax'=>'481', 'ce'=>'92'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'482', 'pdMax'=>'482', 'ce'=>'93'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'483', 'pdMax'=>'488', 'ce'=>'94'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'489', 'pdMax'=>'491', 'ce'=>'96'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'492', 'pdMax'=>'492', 'ce'=>'98'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'493', 'pdMax'=>'493', 'ce'=>'99'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'494', 'pdMax'=>'496', 'ce'=>'100'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'497', 'pdMax'=>'503', 'ce'=>'103'),
			array('typeScale'=>'CETOTAL','pdMin'=>'504', 'pdMax'=>'505', 'ce'=>'105'),
			array('typeScale'=>'CETOTAL','pdMin'=>'506', 'pdMax'=>'507', 'ce'=>'106'),
			array('typeScale'=>'CETOTAL','pdMin'=>'508', 'pdMax'=>'511', 'ce'=>'107'),
			array('typeScale'=>'CETOTAL','pdMin'=>'512', 'pdMax'=>'512', 'ce'=>'108'),
			array('typeScale'=>'CETOTAL','pdMin'=>'513', 'pdMax'=>'519', 'ce'=>'109'),
			array('typeScale'=>'CETOTAL','pdMin'=>'520', 'pdMax'=>'521', 'ce'=>'113'),
			array('typeScale'=>'CETOTAL','pdMin'=>'522', 'pdMax'=>'525', 'ce'=>'116'),
			array('typeScale'=>'CETOTAL','pdMin'=>'526', 'pdMax'=>'528', 'ce'=>'118'),
			array('typeScale'=>'CETOTAL','pdMin'=>'529', 'pdMax'=>'533', 'ce'=>'119'),
			array('typeScale'=>'CETOTAL','pdMin'=>'534', 'pdMax'=>'536', 'ce'=>'120'),
			array('typeScale'=>'CETOTAL','pdMin'=>'537', 'pdMax'=>'540', 'ce'=>'123'),
			array('typeScale'=>'CETOTAL','pdMin'=>'541', 'pdMax'=>'545', 'ce'=>'124'),
			array('typeScale'=>'CETOTAL','pdMin'=>'546', 'pdMax'=>'585', 'ce'=>'126'),			
		);
         
        foreach ($lstStructure as $lst) {

            $objeto = new ICEF4100Baremo();
            $objeto->setTypeScale($lst['typeScale']);
            $objeto->setPdMin($lst['pdMin']);
            $objeto->setPdMax($lst['pdMax']);
            $objeto->setCE($lst['ce']);
            
            $manager->persist($objeto);                              
        }

        $manager->flush();    
	}
}
