<?php

namespace Jaxxes\TestICEBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture; 
use Symfony\Component\DependencyInjection\ContainerAwareInterface;

use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerInterface;

use Jaxxes\TestICEBundle\Entity\ICEF2130Baremo;

/**
 * Fixtures de la entidad Resume.
 * Crea el registro de la cabecera para Resume = Ficha del candidato
 */
 
// class Resumes implements FixtureInterface
 class ICEF2130Baremos extends AbstractFixture implements OrderedFixtureInterface
{
	
    public function getOrder()
    {
        return 4;
    }
    private $container;
    
    
    
    public function load(ObjectManager $manager)
    {
        $lstStructure = array(
        
			array('typeScale'=>'IMP','pdMin'=>'0', 'pdMax'=>'15', 'ce'=>'65'),
			array('typeScale'=>'IMP','pdMin'=>'16', 'pdMax'=>'16', 'ce'=>'68'),
			array('typeScale'=>'IMP','pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'75'),
			array('typeScale'=>'IMP','pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'81'),
			array('typeScale'=>'IMP','pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'87'),
			array('typeScale'=>'IMP','pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'90'),
			array('typeScale'=>'IMP','pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'93'),
			array('typeScale'=>'IMP','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'96'),
			array('typeScale'=>'IMP','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'100'),
			array('typeScale'=>'IMP','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'103'),
			array('typeScale'=>'IMP','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'107'),
			array('typeScale'=>'IMP','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'109'),
			array('typeScale'=>'IMP','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'111'),
			array('typeScale'=>'IMP','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'114'),
			array('typeScale'=>'IMP','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'116'),
			array('typeScale'=>'IMP','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'118'),
			array('typeScale'=>'IMP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'121'),
			array('typeScale'=>'IMP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'126'),
			array('typeScale'=>'IMP','pdMin'=>'33', 'pdMax'=>'34', 'ce'=>'130'),
			array('typeScale'=>'IMN','pdMin'=>'0', 'pdMax'=>'7', 'ce'=>'65'),    
			array('typeScale'=>'IMN','pdMin'=>'8', 'pdMax'=>'8', 'ce'=>'91'),     
			array('typeScale'=>'IMN','pdMin'=>'9', 'pdMax'=>'9', 'ce'=>'95'),   
			array('typeScale'=>'IMN','pdMin'=>'10', 'pdMax'=>'10', 'ce'=>'101'), 
			array('typeScale'=>'IMN','pdMin'=>'11', 'pdMax'=>'11', 'ce'=>'106'), 
			array('typeScale'=>'IMN','pdMin'=>'12', 'pdMax'=>'12', 'ce'=>'111'), 
			array('typeScale'=>'IMN','pdMin'=>'13', 'pdMax'=>'13', 'ce'=>'114'),
			array('typeScale'=>'IMN','pdMin'=>'14', 'pdMax'=>'14', 'ce'=>'117'),
			array('typeScale'=>'IMN','pdMin'=>'15', 'pdMax'=>'15', 'ce'=>'120'),
			array('typeScale'=>'IMN','pdMin'=>'16', 'pdMax'=>'16', 'ce'=>'124'),
			array('typeScale'=>'IMN','pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'126'),
			array('typeScale'=>'IMN','pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'128'),
			array('typeScale'=>'IMN','pdMin'=>'19', 'pdMax'=>'20', 'ce'=>'130'),
			array('typeScale'=>'IMN','pdMin'=>'21', 'pdMax'=>'35', 'ce'=>'133'),        	
			array('typeScale'=>'CM', 'pdMin'=>'0', 'pdMax'=>'19', 'ce'=>'65'),
			array('typeScale'=>'CM', 'pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'68'),
			array('typeScale'=>'CM', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'71'),
			array('typeScale'=>'CM', 'pdMin'=>'22', 'pdMax'=>'23', 'ce'=>'73'),
			array('typeScale'=>'CM', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'77'),
			array('typeScale'=>'CM', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'79'),
			array('typeScale'=>'CM', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'83'),
			array('typeScale'=>'CM', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'88'),
			array('typeScale'=>'CM', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'90'),
			array('typeScale'=>'CM', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'94'),
			array('typeScale'=>'CM', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'96'),
			array('typeScale'=>'CM', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'101'),
			array('typeScale'=>'CM', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'105'),
			array('typeScale'=>'CM', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'108'),
			array('typeScale'=>'CM', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'111'),
			array('typeScale'=>'CM', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'114'),
			array('typeScale'=>'CM', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'116'),
			array('typeScale'=>'CM', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'121'),
			array('typeScale'=>'CM', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'126'),
			array('typeScale'=>'CM', 'pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'130'),
			array('typeScale'=>'SE', 'pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),
			array('typeScale'=>'SE', 'pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'68'),
			array('typeScale'=>'SE', 'pdMin'=>'18', 'pdMax'=>'19', 'ce'=>'71'),
			array('typeScale'=>'SE', 'pdMin'=>'20', 'pdMax'=>'21', 'ce'=>'73'),
			array('typeScale'=>'SE', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'79'),
			array('typeScale'=>'SE', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'82'),
			array('typeScale'=>'SE', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'84'),
			array('typeScale'=>'SE', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'87'),
			array('typeScale'=>'SE', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'92'),
			array('typeScale'=>'SE', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'96'),
			array('typeScale'=>'SE', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'100'),
			array('typeScale'=>'SE', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'102'),
			array('typeScale'=>'SE', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'106'),
			array('typeScale'=>'SE', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'111'),
			array('typeScale'=>'SE', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'116'),
			array('typeScale'=>'SE', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'120'),
			array('typeScale'=>'SE', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'123'),
			array('typeScale'=>'SE', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'128'),
			array('typeScale'=>'AE', 'pdMin'=>'0', 'pdMax'=>'24', 'ce'=>'65'),
			array('typeScale'=>'AE', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'68'),
			array('typeScale'=>'AE', 'pdMin'=>'26', 'pdMax'=>'27', 'ce'=>'71'),
			array('typeScale'=>'AE', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'73'),
			array('typeScale'=>'AE', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'75'),
			array('typeScale'=>'AE', 'pdMin'=>'30', 'pdMax'=>'31', 'ce'=>'77'),
			array('typeScale'=>'AE', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'79'),
			array('typeScale'=>'AE', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'80'),
			array('typeScale'=>'AE', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'82'),
			array('typeScale'=>'AE', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'85'),
			array('typeScale'=>'AE', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'88'),
			array('typeScale'=>'AE', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'90'),
			array('typeScale'=>'AE', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'92'),
			array('typeScale'=>'AE', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'96'),
			array('typeScale'=>'AE', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'100'),
			array('typeScale'=>'AE', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'103'),
			array('typeScale'=>'AE', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'106'),
			array('typeScale'=>'AE', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'110'),
			array('typeScale'=>'AE', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'113'),
			array('typeScale'=>'AE', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'118'),
			array('typeScale'=>'AR', 'pdMin'=>'0', 'pdMax'=>'24', 'ce'=>'65'),
			array('typeScale'=>'AR', 'pdMin'=>'25', 'pdMax'=>'29', 'ce'=>'68'),
			array('typeScale'=>'AR', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'73'),
			array('typeScale'=>'AR', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'75'),
			array('typeScale'=>'AR', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'77'),
			array('typeScale'=>'AR', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'80'),
			array('typeScale'=>'AR', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'81'),
			array('typeScale'=>'AR', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'83'),
			array('typeScale'=>'AR', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'88'),
			array('typeScale'=>'AR', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'90'),
			array('typeScale'=>'AR', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'94'),
			array('typeScale'=>'AR', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'96'),
			array('typeScale'=>'AR', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'100'),
			array('typeScale'=>'AR', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'103'),
			array('typeScale'=>'AR', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'108'),
			array('typeScale'=>'AR', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'112'),
			array('typeScale'=>'AR', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'116'),
			array('typeScale'=>'AR', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'123'),
			array('typeScale'=>'IN', 'pdMin'=>'0', 'pdMax'=>'18', 'ce'=>'65'),
			array('typeScale'=>'IN', 'pdMin'=>'19', 'pdMax'=>'20', 'ce'=>'68'),
			array('typeScale'=>'IN', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'71'),
			array('typeScale'=>'IN', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'73'),
			array('typeScale'=>'IN', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'75'),
			array('typeScale'=>'IN', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'79'),
			array('typeScale'=>'IN', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'83'),
			array('typeScale'=>'IN', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'88'),
			array('typeScale'=>'IN', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'91'),
			array('typeScale'=>'IN', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'94'),
			array('typeScale'=>'IN', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'98'),
			array('typeScale'=>'IN', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'104'),
			array('typeScale'=>'IN', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'109'),
			array('typeScale'=>'IN', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'114'),
			array('typeScale'=>'IN', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'118'),
			array('typeScale'=>'IN', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'123'),
			array('typeScale'=>'IN', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'130'),
			array('typeScale'=>'RI', 'pdMin'=>'0', 'pdMax'=>'33', 'ce'=>'65'),
			array('typeScale'=>'RI', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'68'),
			array('typeScale'=>'RI', 'pdMin'=>'35', 'pdMax'=>'36', 'ce'=>'71'),
			array('typeScale'=>'RI', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'75'),
			array('typeScale'=>'RI', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'79'),
			array('typeScale'=>'RI', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'81'),
			array('typeScale'=>'RI', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'84'),
			array('typeScale'=>'RI', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'87'),
			array('typeScale'=>'RI', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'90'),
			array('typeScale'=>'RI', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'93'),
			array('typeScale'=>'RI', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'95'),
			array('typeScale'=>'RI', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'98'),
			array('typeScale'=>'RI', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'100'),
			array('typeScale'=>'RI', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'103'),
			array('typeScale'=>'RI', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'106'),
			array('typeScale'=>'RI', 'pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'109'),
			array('typeScale'=>'RI', 'pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'111'),
			array('typeScale'=>'RI', 'pdMin'=>'51', 'pdMax'=>'51', 'ce'=>'115'),
			array('typeScale'=>'RI', 'pdMin'=>'52', 'pdMax'=>'52', 'ce'=>'117'),
			array('typeScale'=>'RI', 'pdMin'=>'53', 'pdMax'=>'53', 'ce'=>'123'),
			array('typeScale'=>'RI', 'pdMin'=>'54', 'pdMax'=>'54', 'ce'=>'128'),
			array('typeScale'=>'RI', 'pdMin'=>'55', 'pdMax'=>'55', 'ce'=>'133'),
			array('typeScale'=>'RS', 'pdMin'=>'0', 'pdMax'=>'33', 'ce'=>'65'),
			array('typeScale'=>'RS', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'71'),
			array('typeScale'=>'RS', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'75'),
			array('typeScale'=>'RS', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'77'),			
			array('typeScale'=>'RS', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'80'),
			array('typeScale'=>'RS', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'85'),
			array('typeScale'=>'RS', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'90'),
			array('typeScale'=>'RS', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'92'),
			array('typeScale'=>'RS', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'95'),
			array('typeScale'=>'RS', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'98'),
			array('typeScale'=>'RS', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'101'),
			array('typeScale'=>'RS', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'105'),
			array('typeScale'=>'RS', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'107'),
			array('typeScale'=>'RS', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'111'),
			array('typeScale'=>'RS', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'115'),
			array('typeScale'=>'RS', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'118'),
			array('typeScale'=>'RS', 'pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'122'),
			array('typeScale'=>'RS', 'pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'128'),
			array('typeScale'=>'EM','pdMin'=>'0', 'pdMax'=>'21', 'ce'=>'65'),  
			array('typeScale'=>'EM','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'68'), 
			array('typeScale'=>'EM','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'71'), 
			array('typeScale'=>'EM','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'73'), 
			array('typeScale'=>'EM','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'77'), 
			array('typeScale'=>'EM','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'80'), 
			array('typeScale'=>'EM','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'85'), 
			array('typeScale'=>'EM','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'89'),
			array('typeScale'=>'EM','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'92'),
			array('typeScale'=>'EM','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'95'),
			array('typeScale'=>'EM','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'99'), 
			array('typeScale'=>'EM','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'102'), 
			array('typeScale'=>'EM','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'105'), 
			array('typeScale'=>'EM','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'107'),
			array('typeScale'=>'EM','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'111'),
			array('typeScale'=>'EM','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'115'),
			array('typeScale'=>'EM','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'118'),
			array('typeScale'=>'EM','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'120'),
			array('typeScale'=>'EM','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'126'),
			array('typeScale'=>'EM','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'130'),
			array('typeScale'=>'SP','pdMin'=>'0', 'pdMax'=>'22', 'ce'=>'65'),  
			array('typeScale'=>'SP','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'68'),  
			array('typeScale'=>'SP','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'71'), 
			array('typeScale'=>'SP','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'73'), 
			array('typeScale'=>'SP','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'77'), 
			array('typeScale'=>'SP','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'78'), 
			array('typeScale'=>'SP','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'81'), 
			array('typeScale'=>'SP','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'84'),
			array('typeScale'=>'SP','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'88'),  
			array('typeScale'=>'SP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'92'), 
			array('typeScale'=>'SP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'95'), 
			array('typeScale'=>'SP','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'98'), 
			array('typeScale'=>'SP','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'102'), 
			array('typeScale'=>'SP','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'105'), 
			array('typeScale'=>'SP','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'109'),
			array('typeScale'=>'SP','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'113'),
			array('typeScale'=>'SP','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'116'),
			array('typeScale'=>'SP','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'120'),
			array('typeScale'=>'SP','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'130'),
			array('typeScale'=>'PR','pdMin'=>'0', 'pdMax'=>'29', 'ce'=>'65'),  
			array('typeScale'=>'PR','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'68'), 
			array('typeScale'=>'PR','pdMin'=>'31', 'pdMax'=>'33', 'ce'=>'71'), 
			array('typeScale'=>'PR','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'75'),
			array('typeScale'=>'PR','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'79'),
			array('typeScale'=>'PR','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'82'),
			array('typeScale'=>'PR','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'85'),
			array('typeScale'=>'PR','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'87'),
			array('typeScale'=>'PR','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'88'),
			array('typeScale'=>'PR','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'91'),
			array('typeScale'=>'PR','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'93'),
			array('typeScale'=>'PR','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'96'),
			array('typeScale'=>'PR','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'99'),
			array('typeScale'=>'PR','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'102'),
			array('typeScale'=>'PR','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'106'),
			array('typeScale'=>'PR','pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'110'),
			array('typeScale'=>'PR','pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'115'),
			array('typeScale'=>'PR','pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'118'),
			array('typeScale'=>'PR','pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'124'),
			array('typeScale'=>'PR','pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'130'),
			array('typeScale'=>'FL','pdMin'=>'0', 'pdMax'=>'19', 'ce'=>'65'),    
			array('typeScale'=>'FL','pdMin'=>'20', 'pdMax'=>'21', 'ce'=>'68'),   
			array('typeScale'=>'FL','pdMin'=>'22', 'pdMax'=>'23', 'ce'=>'71'),   
			array('typeScale'=>'FL','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'73'),   
			array('typeScale'=>'FL','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'78'),   
			array('typeScale'=>'FL','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'82'),   
			array('typeScale'=>'FL','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'87'),
			array('typeScale'=>'FL','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'91'),
			array('typeScale'=>'FL','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'94'),
			array('typeScale'=>'FL','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'98'),   
			array('typeScale'=>'FL','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'101'),   
			array('typeScale'=>'FL','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'106'),   
			array('typeScale'=>'FL','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'109'),  
			array('typeScale'=>'FL','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'112'),  
			array('typeScale'=>'FL','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'115'),  
			array('typeScale'=>'FL','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'119'),  
			array('typeScale'=>'FL','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'121'),  
			array('typeScale'=>'FL','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'126'),  
			array('typeScale'=>'FL','pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'130'),
			array('typeScale'=>'TT','pdMin'=>'0', 'pdMax'=>'20', 'ce'=>'65'),    
			array('typeScale'=>'TT','pdMin'=>'21', 'pdMax'=>'23', 'ce'=>'68'),   
			array('typeScale'=>'TT','pdMin'=>'24', 'pdMax'=>'25', 'ce'=>'71'),   
			array('typeScale'=>'TT','pdMin'=>'26', 'pdMax'=>'27', 'ce'=>'73'),   
			array('typeScale'=>'TT','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'79'),
			array('typeScale'=>'FL','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'80'), 
			array('typeScale'=>'FL','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'82'), 
			array('typeScale'=>'FL','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'86'),
			array('typeScale'=>'TT','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'90'),   
			array('typeScale'=>'TT','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'92'),
			array('typeScale'=>'TT','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'95'),      
			array('typeScale'=>'TT','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'98'),   
			array('typeScale'=>'TT','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'100'),   
			array('typeScale'=>'TT','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'104'),  
			array('typeScale'=>'TT','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'108'),
			array('typeScale'=>'TT','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'110'),    
			array('typeScale'=>'TT','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'113'),  
			array('typeScale'=>'TT','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'118'),  
			array('typeScale'=>'TT','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'121'),  
			array('typeScale'=>'TT','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'124'),  
			array('typeScale'=>'TT','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'130'),
			array('typeScale'=>'CI','pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),  
			array('typeScale'=>'CI','pdMin'=>'17', 'pdMax'=>'19', 'ce'=>'68'), 
			array('typeScale'=>'CI','pdMin'=>'20', 'pdMax'=>'23', 'ce'=>'71'), 
			array('typeScale'=>'CI','pdMin'=>'24', 'pdMax'=>'26', 'ce'=>'75'), 
			array('typeScale'=>'CI','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'77'), 
			array('typeScale'=>'CI','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'78'),   
			array('typeScale'=>'CI','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'79'),
			array('typeScale'=>'CI','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'80'),
			array('typeScale'=>'CI','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'81'),
			array('typeScale'=>'CI','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'85'),
			array('typeScale'=>'CI','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'86'), 
			array('typeScale'=>'CI','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'88'), 
			array('typeScale'=>'CI','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'90'), 
			array('typeScale'=>'CI','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'93'), 
			array('typeScale'=>'CI','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'96'), 
			array('typeScale'=>'CI','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'99'), 
			array('typeScale'=>'CI','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'102'), 
			array('typeScale'=>'CI','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'104'), 
			array('typeScale'=>'CI','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'107'), 
			array('typeScale'=>'CI','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'111'),
			array('typeScale'=>'CI','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'117'),
			array('typeScale'=>'CI','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'123'),
			array('typeScale'=>'CI','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'130'),
			array('typeScale'=>'FE','pdMin'=>'0', 'pdMax'=>'24', 'ce'=>'65'),  
			array('typeScale'=>'FE','pdMin'=>'25', 'pdMax'=>'26', 'ce'=>'68'), 
			array('typeScale'=>'FE','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'73'), 
			array('typeScale'=>'FE','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'77'), 
			array('typeScale'=>'FE','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'79'), 
			array('typeScale'=>'FE','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'82'), 
			array('typeScale'=>'FE','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'84'), 
			array('typeScale'=>'FE','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'88'), 
			array('typeScale'=>'FE','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'91'), 
			array('typeScale'=>'FE','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'94'), 
			array('typeScale'=>'FE','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'98'), 
			array('typeScale'=>'FE','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'103'), 
			array('typeScale'=>'FE','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'106'), 
			array('typeScale'=>'FE','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'111'),
			array('typeScale'=>'FE','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'115'),
			array('typeScale'=>'FE','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'119'),
			array('typeScale'=>'FE','pdMin'=>'41', 'pdMax'=>'45', 'ce'=>'124'),
			array('typeScale'=>'OP','pdMin'=>'0', 'pdMax'=>'22', 'ce'=>'65'),   
			array('typeScale'=>'OP','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'77'),  
			array('typeScale'=>'OP','pdMin'=>'24', 'pdMax'=>'25', 'ce'=>'82'),  
			array('typeScale'=>'OP','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'73'),  
			array('typeScale'=>'OP','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'77'),  
			array('typeScale'=>'OP','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'78'),  
			array('typeScale'=>'OP','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'81'),  
			array('typeScale'=>'OP','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'83'),  
			array('typeScale'=>'OP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'86'), 
			array('typeScale'=>'OP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'91'), 
			array('typeScale'=>'OP','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'95'), 
			array('typeScale'=>'OP','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'98'), 
			array('typeScale'=>'OP','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'101'),  
			array('typeScale'=>'OP','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'106'),  
			array('typeScale'=>'OP','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'109'), 
			array('typeScale'=>'OP','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'113'), 
			array('typeScale'=>'OP','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'118'), 
			array('typeScale'=>'OP','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'128'), 
			array('typeScale'=>'CERA','pdMin'=>'40', 'pdMax'=>'113', 'ce'=>'65'),   
			array('typeScale'=>'CERA','pdMin'=>'114', 'pdMax'=>'119', 'ce'=>'68'),  
			array('typeScale'=>'CERA','pdMin'=>'120', 'pdMax'=>'130', 'ce'=>'71'),  
			array('typeScale'=>'CERA','pdMin'=>'131', 'pdMax'=>'132', 'ce'=>'73'),  
			array('typeScale'=>'CERA','pdMin'=>'133', 'pdMax'=>'134', 'ce'=>'75'),  
			array('typeScale'=>'CERA','pdMin'=>'135', 'pdMax'=>'136', 'ce'=>'77'),  
			array('typeScale'=>'CERA','pdMin'=>'137', 'pdMax'=>'139', 'ce'=>'78'),  
			array('typeScale'=>'CERA','pdMin'=>'140', 'pdMax'=>'142', 'ce'=>'79'),  
			array('typeScale'=>'CERA','pdMin'=>'143', 'pdMax'=>'143', 'ce'=>'80'),  
			array('typeScale'=>'CERA','pdMin'=>'144', 'pdMax'=>'146', 'ce'=>'82'),  
			array('typeScale'=>'CERA','pdMin'=>'147', 'pdMax'=>'147', 'ce'=>'83'), 
			array('typeScale'=>'CERA','pdMin'=>'148', 'pdMax'=>'148', 'ce'=>'84'), 
			array('typeScale'=>'CERA','pdMin'=>'149', 'pdMax'=>'150', 'ce'=>'85'), 
			array('typeScale'=>'CERA','pdMin'=>'151', 'pdMax'=>'151', 'ce'=>'86'), 
			array('typeScale'=>'CERA','pdMin'=>'152', 'pdMax'=>'152', 'ce'=>'87'), 
			array('typeScale'=>'CERA','pdMin'=>'153', 'pdMax'=>'153', 'ce'=>'88'), 
			array('typeScale'=>'CERA','pdMin'=>'154', 'pdMax'=>'155', 'ce'=>'89'), 
			array('typeScale'=>'CERA','pdMin'=>'156', 'pdMax'=>'156', 'ce'=>'90'), 
			array('typeScale'=>'CERA','pdMin'=>'157', 'pdMax'=>'157', 'ce'=>'91'), 
			array('typeScale'=>'CERA','pdMin'=>'158', 'pdMax'=>'159', 'ce'=>'92'), 
			array('typeScale'=>'CERA','pdMin'=>'160', 'pdMax'=>'160', 'ce'=>'93'),
			array('typeScale'=>'CERA','pdMin'=>'161', 'pdMax'=>'162', 'ce'=>'94'),
			array('typeScale'=>'CERA','pdMin'=>'163', 'pdMax'=>'164', 'ce'=>'96'),
			array('typeScale'=>'CERA','pdMin'=>'165', 'pdMax'=>'165', 'ce'=>'98'),
			array('typeScale'=>'CERA','pdMin'=>'166', 'pdMax'=>'166', 'ce'=>'99'),
			array('typeScale'=>'CERA','pdMin'=>'167', 'pdMax'=>'167', 'ce'=>'100'),
			array('typeScale'=>'CERA','pdMin'=>'168', 'pdMax'=>'168', 'ce'=>'101'),
			array('typeScale'=>'CERA','pdMin'=>'169', 'pdMax'=>'169', 'ce'=>'102'),
			array('typeScale'=>'CERA','pdMin'=>'170', 'pdMax'=>'170', 'ce'=>'103'),
			array('typeScale'=>'CERA','pdMin'=>'171', 'pdMax'=>'171', 'ce'=>'105'),
			array('typeScale'=>'CERA','pdMin'=>'172', 'pdMax'=>'172', 'ce'=>'106'),
			array('typeScale'=>'CERA','pdMin'=>'173', 'pdMax'=>'173', 'ce'=>'107'),
			array('typeScale'=>'CERA','pdMin'=>'174', 'pdMax'=>'174', 'ce'=>'108'),
			array('typeScale'=>'CERA','pdMin'=>'175', 'pdMax'=>'175', 'ce'=>'110'),
			array('typeScale'=>'CERA','pdMin'=>'176', 'pdMax'=>'176', 'ce'=>'111'),
			array('typeScale'=>'CERA','pdMin'=>'177', 'pdMax'=>'177', 'ce'=>'112'),
			array('typeScale'=>'CERA','pdMin'=>'178', 'pdMax'=>'178', 'ce'=>'113'),
			array('typeScale'=>'CERA','pdMin'=>'179', 'pdMax'=>'179', 'ce'=>'114'),
			array('typeScale'=>'CERA','pdMin'=>'180', 'pdMax'=>'180', 'ce'=>'115'),
			array('typeScale'=>'CERA','pdMin'=>'181', 'pdMax'=>'182', 'ce'=>'116'),
			array('typeScale'=>'CERA','pdMin'=>'183', 'pdMax'=>'183', 'ce'=>'118'),
			array('typeScale'=>'CERA','pdMin'=>'184', 'pdMax'=>'184', 'ce'=>'119'),
			array('typeScale'=>'CERA','pdMin'=>'185', 'pdMax'=>'185', 'ce'=>'120'),
			array('typeScale'=>'CERA','pdMin'=>'186', 'pdMax'=>'186', 'ce'=>'123'),
			array('typeScale'=>'CERA','pdMin'=>'187', 'pdMax'=>'187', 'ce'=>'124'),
			array('typeScale'=>'CERA','pdMin'=>'188', 'pdMax'=>'188', 'ce'=>'128'),
			array('typeScale'=>'CERA','pdMin'=>'189', 'pdMax'=>'190', 'ce'=>'130'),
			array('typeScale'=>'CERA','pdMin'=>'191', 'pdMax'=>'200', 'ce'=>'133'),
			array('typeScale'=>'CEER','pdMin'=>'24', 'pdMax'=>'77', 'ce'=>'65'),    
			array('typeScale'=>'CEER','pdMin'=>'78', 'pdMax'=>'81', 'ce'=>'68'),    
			array('typeScale'=>'CEER','pdMin'=>'82', 'pdMax'=>'83', 'ce'=>'71'),    
			array('typeScale'=>'CEER','pdMin'=>'84', 'pdMax'=>'85', 'ce'=>'73'),    
			array('typeScale'=>'CEER','pdMin'=>'86', 'pdMax'=>'86', 'ce'=>'77'),    
			array('typeScale'=>'CEER','pdMin'=>'87', 'pdMax'=>'87', 'ce'=>'79'),    
			array('typeScale'=>'CEER','pdMin'=>'88', 'pdMax'=>'88', 'ce'=>'81'),    
			array('typeScale'=>'CEER','pdMin'=>'89', 'pdMax'=>'89', 'ce'=>'84'),    
			array('typeScale'=>'CEER','pdMin'=>'90', 'pdMax'=>'90', 'ce'=>'85'),    
			array('typeScale'=>'CEER','pdMin'=>'91', 'pdMax'=>'91', 'ce'=>'88'),    
			array('typeScale'=>'CEER','pdMin'=>'92', 'pdMax'=>'92', 'ce'=>'89'),    
			array('typeScale'=>'CEER','pdMin'=>'93', 'pdMax'=>'93', 'ce'=>'90'),    
			array('typeScale'=>'CEER','pdMin'=>'94', 'pdMax'=>'95', 'ce'=>'92'),   
			array('typeScale'=>'CEER','pdMin'=>'96', 'pdMax'=>'96', 'ce'=>'94'), 
			array('typeScale'=>'CEER','pdMin'=>'97', 'pdMax'=>'97', 'ce'=>'96'), 
			array('typeScale'=>'CEER','pdMin'=>'98', 'pdMax'=>'98', 'ce'=>'98'), 
			array('typeScale'=>'CEER','pdMin'=>'99', 'pdMax'=>'100', 'ce'=>'100'), 
			array('typeScale'=>'CEER','pdMin'=>'101', 'pdMax'=>'101', 'ce'=>'101'), 
			array('typeScale'=>'CEER','pdMin'=>'102', 'pdMax'=>'102', 'ce'=>'103'), 
			array('typeScale'=>'CEER','pdMin'=>'103', 'pdMax'=>'103', 'ce'=>'104'), 
			array('typeScale'=>'CEER','pdMin'=>'104', 'pdMax'=>'104', 'ce'=>'106'), 
			array('typeScale'=>'CEER','pdMin'=>'105', 'pdMax'=>'105', 'ce'=>'107'), 
			array('typeScale'=>'CEER','pdMin'=>'106', 'pdMax'=>'106', 'ce'=>'109'), 
			array('typeScale'=>'CEER','pdMin'=>'107', 'pdMax'=>'107', 'ce'=>'110'), 
			array('typeScale'=>'CEER','pdMin'=>'108', 'pdMax'=>'108', 'ce'=>'113'), 
			array('typeScale'=>'CEER','pdMin'=>'109', 'pdMax'=>'109', 'ce'=>'115'), 
			array('typeScale'=>'CEER','pdMin'=>'110', 'pdMax'=>'110', 'ce'=>'117'), 
			array('typeScale'=>'CEER','pdMin'=>'111', 'pdMax'=>'111', 'ce'=>'119'), 
			array('typeScale'=>'CEER','pdMin'=>'112', 'pdMax'=>'112', 'ce'=>'120'), 
			array('typeScale'=>'CEER','pdMin'=>'113', 'pdMax'=>'113', 'ce'=>'122'), 
			array('typeScale'=>'CEER','pdMin'=>'114', 'pdMax'=>'114', 'ce'=>'123'), 
			array('typeScale'=>'CEER','pdMin'=>'115', 'pdMax'=>'115', 'ce'=>'126'), 
			array('typeScale'=>'CEER','pdMin'=>'116', 'pdMax'=>'116', 'ce'=>'128'), 
			array('typeScale'=>'CEER','pdMin'=>'117', 'pdMax'=>'118', 'ce'=>'130'), 
			array('typeScale'=>'CEER','pdMin'=>'119', 'pdMax'=>'120', 'ce'=>'133'), 
			array('typeScale'=>'CEAD','pdMin'=>'26', 'pdMax'=>'74', 'ce'=>'65'),      
			array('typeScale'=>'CEAD','pdMin'=>'75', 'pdMax'=>'81', 'ce'=>'68'),      
			array('typeScale'=>'CEAD','pdMin'=>'82', 'pdMax'=>'83', 'ce'=>'71'),      
			array('typeScale'=>'CEAD','pdMin'=>'84', 'pdMax'=>'86', 'ce'=>'73'),      
			array('typeScale'=>'CEAD','pdMin'=>'87', 'pdMax'=>'88', 'ce'=>'77'),      
			array('typeScale'=>'CEAD','pdMin'=>'89', 'pdMax'=>'90', 'ce'=>'78'), 
			array('typeScale'=>'CEAD','pdMin'=>'91', 'pdMax'=>'91', 'ce'=>'79'),      
			array('typeScale'=>'CEAD','pdMin'=>'92', 'pdMax'=>'92', 'ce'=>'81'),      
			array('typeScale'=>'CEAD','pdMin'=>'93', 'pdMax'=>'93', 'ce'=>'82'),      
			array('typeScale'=>'CEAD','pdMin'=>'94', 'pdMax'=>'94', 'ce'=>'84'),      
			array('typeScale'=>'CEAD','pdMin'=>'95', 'pdMax'=>'95', 'ce'=>'85'),      
			array('typeScale'=>'CEAD','pdMin'=>'96', 'pdMax'=>'96', 'ce'=>'86'),      
			array('typeScale'=>'CEAD','pdMin'=>'97', 'pdMax'=>'97', 'ce'=>'87'),      
			array('typeScale'=>'CEAD','pdMin'=>'98', 'pdMax'=>'98', 'ce'=>'88'),      
			array('typeScale'=>'CEAD','pdMin'=>'99', 'pdMax'=>'99', 'ce'=>'89'),      
			array('typeScale'=>'CEAD','pdMin'=>'100', 'pdMax'=>'100', 'ce'=>'92'),    
			array('typeScale'=>'CEAD','pdMin'=>'101', 'pdMax'=>'101', 'ce'=>'93'),    
			array('typeScale'=>'CEAD','pdMin'=>'102', 'pdMax'=>'102', 'ce'=>'94'),    
			array('typeScale'=>'CEAD','pdMin'=>'103', 'pdMax'=>'103', 'ce'=>'96'),   
			array('typeScale'=>'CEAD','pdMin'=>'104', 'pdMax'=>'104', 'ce'=>'97'),   
			array('typeScale'=>'CEAD','pdMin'=>'105', 'pdMax'=>'105', 'ce'=>'98'),
			array('typeScale'=>'CEAD','pdMin'=>'106', 'pdMax'=>'107', 'ce'=>'100'),   
			array('typeScale'=>'CEAD','pdMin'=>'108', 'pdMax'=>'108', 'ce'=>'102'),   
			array('typeScale'=>'CEAD','pdMin'=>'109', 'pdMax'=>'109', 'ce'=>'104'),   
			array('typeScale'=>'CEAD','pdMin'=>'110', 'pdMax'=>'110', 'ce'=>'105'),   
			array('typeScale'=>'CEAD','pdMin'=>'111', 'pdMax'=>'111', 'ce'=>'107'),   
			array('typeScale'=>'CEAD','pdMin'=>'112', 'pdMax'=>'112', 'ce'=>'109'),   
			array('typeScale'=>'CEAD','pdMin'=>'113', 'pdMax'=>'113', 'ce'=>'110'),   
			array('typeScale'=>'CEAD','pdMin'=>'114', 'pdMax'=>'114', 'ce'=>'111'),   
			array('typeScale'=>'CEAD','pdMin'=>'115', 'pdMax'=>'115', 'ce'=>'113'),   
			array('typeScale'=>'CEAD','pdMin'=>'116', 'pdMax'=>'116', 'ce'=>'116'),   
			array('typeScale'=>'CEAD','pdMin'=>'117', 'pdMax'=>'117', 'ce'=>'117'),   
			array('typeScale'=>'CEAD','pdMin'=>'118', 'pdMax'=>'118', 'ce'=>'119'),   
			array('typeScale'=>'CEAD','pdMin'=>'119', 'pdMax'=>'119', 'ce'=>'122'),   
			array('typeScale'=>'CEAD','pdMin'=>'120', 'pdMax'=>'120', 'ce'=>'123'),   
			array('typeScale'=>'CEAD','pdMin'=>'121', 'pdMax'=>'121', 'ce'=>'126'),   
			array('typeScale'=>'CEAD','pdMin'=>'122', 'pdMax'=>'122', 'ce'=>'128'),
			array('typeScale'=>'CEAD','pdMin'=>'123', 'pdMax'=>'130', 'ce'=>'133'), 
			array('typeScale'=>'CEMT','pdMin'=>'18', 'pdMax'=>'42', 'ce'=>'65'),  
			array('typeScale'=>'CEMT','pdMin'=>'43', 'pdMax'=>'48', 'ce'=>'68'),  
			array('typeScale'=>'CEMT','pdMin'=>'49', 'pdMax'=>'52', 'ce'=>'71'),       
			array('typeScale'=>'CEMT','pdMin'=>'53', 'pdMax'=>'54', 'ce'=>'73'),  
			array('typeScale'=>'CEMT','pdMin'=>'55', 'pdMax'=>'55', 'ce'=>'75'),  
			array('typeScale'=>'CEMT','pdMin'=>'56', 'pdMax'=>'56', 'ce'=>'77'),  
			array('typeScale'=>'CEMT','pdMin'=>'57', 'pdMax'=>'58', 'ce'=>'78'),  
			array('typeScale'=>'CEMT','pdMin'=>'59', 'pdMax'=>'60', 'ce'=>'79'),  
			array('typeScale'=>'CEMT','pdMin'=>'61', 'pdMax'=>'61', 'ce'=>'81'),  
			array('typeScale'=>'CEMT','pdMin'=>'62', 'pdMax'=>'62', 'ce'=>'82'),  
			array('typeScale'=>'CEMT','pdMin'=>'63', 'pdMax'=>'63', 'ce'=>'84'),  
			array('typeScale'=>'CEMT','pdMin'=>'64', 'pdMax'=>'64', 'ce'=>'85'),  
			array('typeScale'=>'CEMT','pdMin'=>'65', 'pdMax'=>'65', 'ce'=>'86'),  
			array('typeScale'=>'CEMT','pdMin'=>'66', 'pdMax'=>'66', 'ce'=>'89'),  
			array('typeScale'=>'CEMT','pdMin'=>'67', 'pdMax'=>'67', 'ce'=>'90'),  
			array('typeScale'=>'CEMT','pdMin'=>'68', 'pdMax'=>'68', 'ce'=>'92'),  
			array('typeScale'=>'CEMT','pdMin'=>'69', 'pdMax'=>'69', 'ce'=>'93'),  
			array('typeScale'=>'CEMT','pdMin'=>'70', 'pdMax'=>'70', 'ce'=>'95'),  
			array('typeScale'=>'CEMT','pdMin'=>'71', 'pdMax'=>'71', 'ce'=>'96'),  
			array('typeScale'=>'CEMT','pdMin'=>'72', 'pdMax'=>'72', 'ce'=>'98'), 
			array('typeScale'=>'CEMT','pdMin'=>'73', 'pdMax'=>'73', 'ce'=>'100'), 
			array('typeScale'=>'CEMT','pdMin'=>'74', 'pdMax'=>'74', 'ce'=>'101'), 
			array('typeScale'=>'CEMT','pdMin'=>'75', 'pdMax'=>'75', 'ce'=>'103'), 
			array('typeScale'=>'CEMT','pdMin'=>'76', 'pdMax'=>'76', 'ce'=>'104'), 
			array('typeScale'=>'CEMT','pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'106'), 
			array('typeScale'=>'CEMT','pdMin'=>'78', 'pdMax'=>'78', 'ce'=>'107'), 
			array('typeScale'=>'CEMT','pdMin'=>'79', 'pdMax'=>'79', 'ce'=>'109'), 
			array('typeScale'=>'CEMT','pdMin'=>'80', 'pdMax'=>'80', 'ce'=>'112'),
			array('typeScale'=>'CEMT','pdMin'=>'81', 'pdMax'=>'82', 'ce'=>'116'), 
			array('typeScale'=>'CEMT','pdMin'=>'83', 'pdMax'=>'83', 'ce'=>'118'),
			array('typeScale'=>'CEMT','pdMin'=>'84', 'pdMax'=>'84', 'ce'=>'122'),
			array('typeScale'=>'CEMT','pdMin'=>'85', 'pdMax'=>'85', 'ce'=>'124'),
			array('typeScale'=>'CEMT','pdMin'=>'86', 'pdMax'=>'86', 'ce'=>'128'),
			array('typeScale'=>'CEMT','pdMin'=>'87', 'pdMax'=>'90', 'ce'=>'133'),
			array('typeScale'=>'CEAG','pdMin'=>'17', 'pdMax'=>'49', 'ce'=>'65'),  
			array('typeScale'=>'CEAG','pdMin'=>'50', 'pdMax'=>'52', 'ce'=>'68'),  
			array('typeScale'=>'CEAG','pdMin'=>'53', 'pdMax'=>'53', 'ce'=>'71'),  
			array('typeScale'=>'CEAG','pdMin'=>'54', 'pdMax'=>'55', 'ce'=>'73'),
			array('typeScale'=>'CEAG','pdMin'=>'56', 'pdMax'=>'56', 'ce'=>'75'),  
			array('typeScale'=>'CEAG','pdMin'=>'57', 'pdMax'=>'57', 'ce'=>'77'),  
			array('typeScale'=>'CEAG','pdMin'=>'58', 'pdMax'=>'58', 'ce'=>'78'),  
			array('typeScale'=>'CEAG','pdMin'=>'59', 'pdMax'=>'59', 'ce'=>'79'),  
			array('typeScale'=>'CEAG','pdMin'=>'60', 'pdMax'=>'60', 'ce'=>'81'),  
			array('typeScale'=>'CEAG','pdMin'=>'61', 'pdMax'=>'61', 'ce'=>'83'),  
			array('typeScale'=>'CEAG','pdMin'=>'62', 'pdMax'=>'62', 'ce'=>'85'),  
			array('typeScale'=>'CEAG','pdMin'=>'63', 'pdMax'=>'63', 'ce'=>'87'),  
			array('typeScale'=>'CEAG','pdMin'=>'64', 'pdMax'=>'64', 'ce'=>'90'),  
			array('typeScale'=>'CEAG','pdMin'=>'65', 'pdMax'=>'65', 'ce'=>'91'),  
			array('typeScale'=>'CEAG','pdMin'=>'66', 'pdMax'=>'66', 'ce'=>'93'), 
			array('typeScale'=>'CEAG','pdMin'=>'67', 'pdMax'=>'67', 'ce'=>'95'), 
			array('typeScale'=>'CEAG','pdMin'=>'68', 'pdMax'=>'68', 'ce'=>'97'), 
			array('typeScale'=>'CEAG','pdMin'=>'69', 'pdMax'=>'69', 'ce'=>'99'), 
			array('typeScale'=>'CEAG','pdMin'=>'70', 'pdMax'=>'70', 'ce'=>'101'), 
			array('typeScale'=>'CEAG','pdMin'=>'71', 'pdMax'=>'71', 'ce'=>'103'), 
			array('typeScale'=>'CEAG','pdMin'=>'72', 'pdMax'=>'72', 'ce'=>'106'), 
			array('typeScale'=>'CEAG','pdMin'=>'73', 'pdMax'=>'73', 'ce'=>'107'), 
			array('typeScale'=>'CEAG','pdMin'=>'74', 'pdMax'=>'74', 'ce'=>'110'), 
			array('typeScale'=>'CEAG','pdMin'=>'75', 'pdMax'=>'75', 'ce'=>'114'), 
			array('typeScale'=>'CEAG','pdMin'=>'76', 'pdMax'=>'76', 'ce'=>'115'), 
			array('typeScale'=>'CEAG','pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'119'), 
			array('typeScale'=>'CEAG','pdMin'=>'78', 'pdMax'=>'78', 'ce'=>'122'), 
			array('typeScale'=>'CEAG','pdMin'=>'79', 'pdMax'=>'79', 'ce'=>'128'), 
			array('typeScale'=>'CEAG','pdMin'=>'80', 'pdMax'=>'80', 'ce'=>'130'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'117', 'pdMax'=>'361', 'ce'=>'65'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'362', 'pdMax'=>'373', 'ce'=>'68'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'374', 'pdMax'=>'383', 'ce'=>'71'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'384', 'pdMax'=>'392', 'ce'=>'73'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'393', 'pdMax'=>'393', 'ce'=>'75'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'394', 'pdMax'=>'403', 'ce'=>'77'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'404', 'pdMax'=>'413', 'ce'=>'78'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'414', 'pdMax'=>'420', 'ce'=>'79'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'421', 'pdMax'=>'422', 'ce'=>'80'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'423', 'pdMax'=>'427', 'ce'=>'81'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'428', 'pdMax'=>'431', 'ce'=>'82'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'432', 'pdMax'=>'434', 'ce'=>'83'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'435', 'pdMax'=>'437', 'ce'=>'84'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'438', 'pdMax'=>'441', 'ce'=>'85'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'442', 'pdMax'=>'443', 'ce'=>'86'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'444', 'pdMax'=>'445', 'ce'=>'87'),  
			array('typeScale'=>'CETOTAL','pdMin'=>'446', 'pdMax'=>'449', 'ce'=>'88'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'450', 'pdMax'=>'552', 'ce'=>'89'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'453', 'pdMax'=>'555', 'ce'=>'90'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'456', 'pdMax'=>'559', 'ce'=>'91'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'460', 'pdMax'=>'561', 'ce'=>'92'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'462', 'pdMax'=>'462', 'ce'=>'93'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'463', 'pdMax'=>'466', 'ce'=>'94'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'467', 'pdMax'=>'469', 'ce'=>'95'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'470', 'pdMax'=>'472', 'ce'=>'96'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'473', 'pdMax'=>'473', 'ce'=>'97'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'474', 'pdMax'=>'474', 'ce'=>'98'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'479', 'pdMax'=>'479', 'ce'=>'99'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'480', 'pdMax'=>'481', 'ce'=>'100'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'482', 'pdMax'=>'485', 'ce'=>'101'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'486', 'pdMax'=>'491', 'ce'=>'103'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'492', 'pdMax'=>'494', 'ce'=>'104'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'495', 'pdMax'=>'495', 'ce'=>'105'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'496', 'pdMax'=>'498', 'ce'=>'106'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'499', 'pdMax'=>'501', 'ce'=>'107'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'502', 'pdMax'=>'503', 'ce'=>'108'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'504', 'pdMax'=>'506', 'ce'=>'109'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'507', 'pdMax'=>'509', 'ce'=>'110'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'510', 'pdMax'=>'512', 'ce'=>'111'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'513', 'pdMax'=>'513', 'ce'=>'112'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'514', 'pdMax'=>'514', 'ce'=>'113'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'515', 'pdMax'=>'517', 'ce'=>'115'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'518', 'pdMax'=>'521', 'ce'=>'116'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'522', 'pdMax'=>'522', 'ce'=>'117'),
			array('typeScale'=>'CETOTAL','pdMin'=>'523', 'pdMax'=>'527', 'ce'=>'118'),
			array('typeScale'=>'CETOTAL','pdMin'=>'528', 'pdMax'=>'528', 'ce'=>'119'),
			array('typeScale'=>'CETOTAL','pdMin'=>'529', 'pdMax'=>'529', 'ce'=>'120'),
			array('typeScale'=>'CETOTAL','pdMin'=>'530', 'pdMax'=>'530', 'ce'=>'121'),
			array('typeScale'=>'CETOTAL','pdMin'=>'531', 'pdMax'=>'531', 'ce'=>'122'),
			array('typeScale'=>'CETOTAL','pdMin'=>'532', 'pdMax'=>'533', 'ce'=>'123'),
			array('typeScale'=>'CETOTAL','pdMin'=>'534', 'pdMax'=>'536', 'ce'=>'124'),
			array('typeScale'=>'CETOTAL','pdMin'=>'537', 'pdMax'=>'539', 'ce'=>'126'),
			array('typeScale'=>'CETOTAL','pdMin'=>'540', 'pdMax'=>'541', 'ce'=>'128'),
			array('typeScale'=>'CETOTAL','pdMin'=>'542', 'pdMax'=>'548', 'ce'=>'130'),
			array('typeScale'=>'CETOTAL','pdMin'=>'549', 'pdMax'=>'585', 'ce'=>'133'),
			
		);
         
        foreach ($lstStructure as $lst) {

            $objeto = new ICEF2130Baremo();
            $objeto->setTypeScale($lst['typeScale']);
            $objeto->setPdMin($lst['pdMin']);
            $objeto->setPdMax($lst['pdMax']);
            $objeto->setCE($lst['ce']);
            
            $manager->persist($objeto);                              
        }

        $manager->flush();    
	}
}
