<?php

namespace Jaxxes\TestICEBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture; 
use Symfony\Component\DependencyInjection\ContainerAwareInterface;

use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerInterface;

use Jaxxes\TestICEBundle\Entity\ICEF1620Baremo;

/**
 * Fixtures de la entidad Resume.
 * Crea el registro de la cabecera para Resume = Ficha del candidato
 */
 
// class Resumes implements FixtureInterface
 class ICEF1620Baremos extends AbstractFixture implements OrderedFixtureInterface
{
	
    public function getOrder()
    {
        return 4;
    }
    private $container;
    
    
    
    public function load(ObjectManager $manager)
    {
        $lstStructure = array(
			array('typeScale'=>'IMP','pdMin'=>'0', 'pdMax'=>'13', 'ce'=>'65'),   
			array('typeScale'=>'IMP','pdMin'=>'14', 'pdMax'=>'14', 'ce'=>'68'),  
			array('typeScale'=>'IMP','pdMin'=>'15', 'pdMax'=>'15', 'ce'=>'71'),  
			array('typeScale'=>'IMP','pdMin'=>'16', 'pdMax'=>'16', 'ce'=>'73'),  
			array('typeScale'=>'IMP','pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'79'),  
			array('typeScale'=>'IMP','pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'82'),  
			array('typeScale'=>'IMP','pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'85'),  
			array('typeScale'=>'IMP','pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'90'),  
			array('typeScale'=>'IMP','pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'92'),  
			array('typeScale'=>'IMP','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'96'),  
			array('typeScale'=>'IMP','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'100'), 
			array('typeScale'=>'IMP','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'104'), 
			array('typeScale'=>'IMP','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'107'), 
			array('typeScale'=>'IMP','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'111'), 
			array('typeScale'=>'IMP','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'113'), 
			array('typeScale'=>'IMP','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'117'), 
			array('typeScale'=>'IMP','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'119'), 
			array('typeScale'=>'IMP','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'120'), 
			array('typeScale'=>'IMP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'122'), 
			array('typeScale'=>'IMP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'124'), 
			array('typeScale'=>'IMP','pdMin'=>'33', 'pdMax'=>'40', 'ce'=>'130'), 
			array('typeScale'=>'IMN','pdMin'=>'0', 'pdMax'=>'7', 'ce'=>'65'),    
			array('typeScale'=>'IMN','pdMin'=>'8', 'pdMax'=>'8', 'ce'=>'82'),     
			array('typeScale'=>'IMN','pdMin'=>'9', 'pdMax'=>'9', 'ce'=>'92'),    
			array('typeScale'=>'IMN','pdMin'=>'10', 'pdMax'=>'10', 'ce'=>'97'),  
			array('typeScale'=>'IMN','pdMin'=>'11', 'pdMax'=>'11', 'ce'=>'100'), 
			array('typeScale'=>'IMN','pdMin'=>'12', 'pdMax'=>'12', 'ce'=>'104'), 
			array('typeScale'=>'IMN','pdMin'=>'13', 'pdMax'=>'13', 'ce'=>'109'), 
			array('typeScale'=>'IMN','pdMin'=>'14', 'pdMax'=>'14', 'ce'=>'110'), 
			array('typeScale'=>'IMN','pdMin'=>'15', 'pdMax'=>'15', 'ce'=>'113'), 
			array('typeScale'=>'IMN','pdMin'=>'16', 'pdMax'=>'16', 'ce'=>'116'), 
			array('typeScale'=>'IMN','pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'118'), 
			array('typeScale'=>'IMN','pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'123'), 
			array('typeScale'=>'IMN','pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'124'), 
			array('typeScale'=>'IMN','pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'126'), 
			array('typeScale'=>'IMN','pdMin'=>'21', 'pdMax'=>'35', 'ce'=>'128'),         
			array('typeScale'=>'CM', 'pdMin'=>'0', 'pdMax'=>'13', 'ce'=>'65'),
			array('typeScale'=>'CM', 'pdMin'=>'14', 'pdMax'=>'17', 'ce'=>'68'),
			array('typeScale'=>'CM', 'pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'71'),
			array('typeScale'=>'CM', 'pdMin'=>'19', 'pdMax'=>'20', 'ce'=>'73'),
			array('typeScale'=>'CM', 'pdMin'=>'21', 'pdMax'=>'22', 'ce'=>'75'),
			array('typeScale'=>'CM', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'81'),			
			array('typeScale'=>'CM', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'82'),
			array('typeScale'=>'CM', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'85'),
			array('typeScale'=>'CM', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'86'),
			array('typeScale'=>'CM', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'91'),
			array('typeScale'=>'CM', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'94'),
			array('typeScale'=>'CM', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'95'),
			array('typeScale'=>'CM', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'98'),
			array('typeScale'=>'CM', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'102'),
			array('typeScale'=>'CM', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'108'),
			array('typeScale'=>'CM', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'111'),
			array('typeScale'=>'CM', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'113'),
			array('typeScale'=>'CM', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'116'),
			array('typeScale'=>'CM', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'120'),
			array('typeScale'=>'CM', 'pdMin'=>'37', 'pdMax'=>'40', 'ce'=>'128'),
			array('typeScale'=>'SE', 'pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),
			array('typeScale'=>'SE', 'pdMin'=>'17', 'pdMax'=>'19', 'ce'=>'68'),
			array('typeScale'=>'SE', 'pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'77'),
			array('typeScale'=>'SE', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'81'),
			array('typeScale'=>'SE', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'82'),
			array('typeScale'=>'SE', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'85'),
			array('typeScale'=>'SE', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'89'),
			array('typeScale'=>'SE', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'92'),
			array('typeScale'=>'SE', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'95'),
			array('typeScale'=>'SE', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'99'),
			array('typeScale'=>'SE', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'101'),
			array('typeScale'=>'SE', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'105'),
			array('typeScale'=>'SE', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'108'),
			array('typeScale'=>'SE', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'112'),
			array('typeScale'=>'SE', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'120'),
			array('typeScale'=>'SE', 'pdMin'=>'33', 'pdMax'=>'35', 'ce'=>'124'),
			array('typeScale'=>'AE', 'pdMin'=>'0', 'pdMax'=>'14', 'ce'=>'65'),
			array('typeScale'=>'AE', 'pdMin'=>'15', 'pdMax'=>'16', 'ce'=>'68'),
			array('typeScale'=>'AE', 'pdMin'=>'17', 'pdMax'=>'21', 'ce'=>'71'),
			array('typeScale'=>'AE', 'pdMin'=>'22', 'pdMax'=>'25', 'ce'=>'75'),
			array('typeScale'=>'AE', 'pdMin'=>'26', 'pdMax'=>'27', 'ce'=>'77'),
			array('typeScale'=>'AE', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'78'),
			array('typeScale'=>'AE', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'80'),			
			array('typeScale'=>'AE', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'82'),
			array('typeScale'=>'AE', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'83'),
			array('typeScale'=>'AE', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'86'),
			array('typeScale'=>'AE', 'pdMin'=>'33', 'pdMax'=>'34', 'ce'=>'88'),
			array('typeScale'=>'AE', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'89'),		
			array('typeScale'=>'AE', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'91'),
			array('typeScale'=>'AE', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'94'),
			array('typeScale'=>'AE', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'97'),
			array('typeScale'=>'AE', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'101'),
			array('typeScale'=>'AE', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'103'),
			array('typeScale'=>'AE', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'105'),
			array('typeScale'=>'AE', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'108'),
			array('typeScale'=>'AE', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'111'),
			array('typeScale'=>'AE', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'113'),
			array('typeScale'=>'AE', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'122'),
			array('typeScale'=>'AR', 'pdMin'=>'0', 'pdMax'=>'24', 'ce'=>'65'),
			array('typeScale'=>'AR', 'pdMin'=>'25', 'pdMax'=>'27', 'ce'=>'68'),
			array('typeScale'=>'AR', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'71'),
			array('typeScale'=>'AR', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'73'),
			array('typeScale'=>'AR', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'77'),
			array('typeScale'=>'AR', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'78'),
			array('typeScale'=>'AR', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'79'),
			array('typeScale'=>'AR', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'82'),
			array('typeScale'=>'AR', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'84'),
			array('typeScale'=>'AR', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'89'),
			array('typeScale'=>'AR', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'90'),
			array('typeScale'=>'AR', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'96'),
			array('typeScale'=>'AR', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'98'),
			array('typeScale'=>'AR', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'101'),
			array('typeScale'=>'AR', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'104'),
			array('typeScale'=>'AR', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'106'),
			array('typeScale'=>'AR', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'110'),
			array('typeScale'=>'AR', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'113'),
			array('typeScale'=>'AR', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'118'),
			array('typeScale'=>'AR', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'126'),
			array('typeScale'=>'IN', 'pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),
			array('typeScale'=>'IN', 'pdMin'=>'17', 'pdMax'=>'20', 'ce'=>'71'),
			array('typeScale'=>'IN', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'73'),
			array('typeScale'=>'IN', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'77'),
			array('typeScale'=>'IN', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'81'),
			array('typeScale'=>'IN', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'85'),
			array('typeScale'=>'IN', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'88'),
			array('typeScale'=>'IN', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'90'),
			array('typeScale'=>'IN', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'95'),
			array('typeScale'=>'IN', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'99'),
			array('typeScale'=>'IN', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'103'),
			array('typeScale'=>'IN', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'107'),
			array('typeScale'=>'IN', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'111'),
			array('typeScale'=>'IN', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'113'),
			array('typeScale'=>'IN', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'119'),
			array('typeScale'=>'IN', 'pdMin'=>'34', 'pdMax'=>'35', 'ce'=>'122'),
			array('typeScale'=>'RI', 'pdMin'=>'0', 'pdMax'=>'27', 'ce'=>'65'),
			array('typeScale'=>'RI', 'pdMin'=>'28', 'pdMax'=>'30', 'ce'=>'68'),
			array('typeScale'=>'RI', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'71'),
			array('typeScale'=>'RI', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'73'),
			array('typeScale'=>'RI', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'75'),
			array('typeScale'=>'RI', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'77'),
			array('typeScale'=>'RI', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'78'),
			array('typeScale'=>'RI', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'79'),
			array('typeScale'=>'RI', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'81'),
			array('typeScale'=>'RI', 'pdMin'=>'38', 'pdMax'=>'39', 'ce'=>'82'),
			array('typeScale'=>'RI', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'84'),
			array('typeScale'=>'RI', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'86'),
			array('typeScale'=>'RI', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'88'),
			array('typeScale'=>'RI', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'92'),
			array('typeScale'=>'RI', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'96'),
			array('typeScale'=>'RI', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'99'),
			array('typeScale'=>'RI', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'100'),
			array('typeScale'=>'RI', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'102'),
			array('typeScale'=>'RI', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'107'),
			array('typeScale'=>'RI', 'pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'109'),
			array('typeScale'=>'RI', 'pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'113'),
			array('typeScale'=>'RI', 'pdMin'=>'51', 'pdMax'=>'51', 'ce'=>'117'),
			array('typeScale'=>'RI', 'pdMin'=>'52', 'pdMax'=>'52', 'ce'=>'121'),
			array('typeScale'=>'RI', 'pdMin'=>'53', 'pdMax'=>'55', 'ce'=>'130'),
			array('typeScale'=>'RS', 'pdMin'=>'0', 'pdMax'=>'32', 'ce'=>'65'),
			array('typeScale'=>'RS', 'pdMin'=>'33', 'pdMax'=>'35', 'ce'=>'68'),
			array('typeScale'=>'RS', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'71'),
			array('typeScale'=>'RS', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'75'),
			array('typeScale'=>'RS', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'81'),
			array('typeScale'=>'RS', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'85'),
			array('typeScale'=>'RS', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'88'),
			array('typeScale'=>'RS', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'91'),
			array('typeScale'=>'RS', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'94'),
			array('typeScale'=>'RS', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'100'),
			array('typeScale'=>'RS', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'105'),
			array('typeScale'=>'RS', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'110'),
			array('typeScale'=>'RS', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'115'),
			array('typeScale'=>'RS', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'118'),
			array('typeScale'=>'RS', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'124'),
			array('typeScale'=>'RS', 'pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'126'),						
			array('typeScale'=>'RS', 'pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'130'),
			array('typeScale'=>'EM','pdMin'=>'0', 'pdMax'=>'22', 'ce'=>'65'),  
			array('typeScale'=>'EM','pdMin'=>'23', 'pdMax'=>'24', 'ce'=>'71'), 
			array('typeScale'=>'EM','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'73'), 
			array('typeScale'=>'EM','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'75'), 
			array('typeScale'=>'EM','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'77'), 
			array('typeScale'=>'EM','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'82'), 
			array('typeScale'=>'EM','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'86'), 
			array('typeScale'=>'EM','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'91'), 
			array('typeScale'=>'EM','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'96'), 
			array('typeScale'=>'EM','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'99'),
			array('typeScale'=>'EM','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'104'),
			array('typeScale'=>'EM','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'106'),
			array('typeScale'=>'EM','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'111'),
			array('typeScale'=>'EM','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'116'),
			array('typeScale'=>'EM','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'118'),
			array('typeScale'=>'EM','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'122'),
			array('typeScale'=>'EM','pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'130'),
			array('typeScale'=>'SP','pdMin'=>'0', 'pdMax'=>'18', 'ce'=>'65'),  
			array('typeScale'=>'SP','pdMin'=>'19', 'pdMax'=>'21', 'ce'=>'68'), 
			array('typeScale'=>'SP','pdMin'=>'22', 'pdMax'=>'23', 'ce'=>'71'), 
			array('typeScale'=>'SP','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'73'), 
			array('typeScale'=>'SP','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'77'), 
			array('typeScale'=>'SP','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'81'), 
			array('typeScale'=>'SP','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'83'), 
			array('typeScale'=>'SP','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'85'), 
			array('typeScale'=>'SP','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'86'), 
			array('typeScale'=>'SP','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'90'), 
			array('typeScale'=>'SP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'92'), 
			array('typeScale'=>'SP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'95'), 
			array('typeScale'=>'SP','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'102'), 
			array('typeScale'=>'SP','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'105'),
			array('typeScale'=>'SP','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'109'),
			array('typeScale'=>'SP','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'111'),
			array('typeScale'=>'SP','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'115'),
			array('typeScale'=>'SP','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'119'),
			array('typeScale'=>'SP','pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'128'),
			array('typeScale'=>'PR','pdMin'=>'0', 'pdMax'=>'23', 'ce'=>'65'),  
			array('typeScale'=>'PR','pdMin'=>'24', 'pdMax'=>'29', 'ce'=>'68'), 
			array('typeScale'=>'PR','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'71'), 
			array('typeScale'=>'PR','pdMin'=>'31', 'pdMax'=>'32', 'ce'=>'73'), 
			array('typeScale'=>'PR','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'75'), 
			array('typeScale'=>'PR','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'79'), 
			array('typeScale'=>'PR','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'81'), 
			array('typeScale'=>'PR','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'82'), 
			array('typeScale'=>'PR','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'85'), 
			array('typeScale'=>'PR','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'90'), 
			array('typeScale'=>'PR','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'92'), 
			array('typeScale'=>'PR','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'95'), 
			array('typeScale'=>'PR','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'97'), 
			array('typeScale'=>'PR','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'98'), 
			array('typeScale'=>'PR','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'100'), 
			array('typeScale'=>'PR','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'104'),
			array('typeScale'=>'PR','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'108'),
			array('typeScale'=>'PR','pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'112'),
			array('typeScale'=>'PR','pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'116'),
			array('typeScale'=>'PR','pdMin'=>'48', 'pdMax'=>'50', 'ce'=>'118'),
			array('typeScale'=>'FL','pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),  
			array('typeScale'=>'FL','pdMin'=>'17', 'pdMax'=>'18', 'ce'=>'68'), 
			array('typeScale'=>'FL','pdMin'=>'19', 'pdMax'=>'20', 'ce'=>'71'), 
			array('typeScale'=>'FL','pdMin'=>'21', 'pdMax'=>'22', 'ce'=>'73'),
			array('typeScale'=>'FL','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'77'), 
			array('typeScale'=>'FL','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'80'), 
			array('typeScale'=>'FL','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'85'), 
			array('typeScale'=>'FL','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'86'), 
			array('typeScale'=>'FL','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'91'), 
			array('typeScale'=>'FL','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'94'), 
			array('typeScale'=>'FL','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'99'),
			array('typeScale'=>'FL','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'102'),
			array('typeScale'=>'FL','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'105'),
			array('typeScale'=>'FL','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'110'),
			array('typeScale'=>'FL','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'113'),
			array('typeScale'=>'FL','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'118'),
			array('typeScale'=>'FL','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'119'),
			array('typeScale'=>'FL','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'128'), 
			array('typeScale'=>'FL','pdMin'=>'37', 'pdMax'=>'40', 'ce'=>'130'),
			array('typeScale'=>'TT','pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),   
			array('typeScale'=>'TT','pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'68'),       
			array('typeScale'=>'TT','pdMin'=>'18', 'pdMax'=>'19', 'ce'=>'71'),  
			array('typeScale'=>'TT','pdMin'=>'20', 'pdMax'=>'21', 'ce'=>'73'),  
			array('typeScale'=>'TT','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'75'),  
			array('typeScale'=>'FL','pdMin'=>'23', 'pdMax'=>'24', 'ce'=>'77'),  
			array('typeScale'=>'FL','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'78'),  
			array('typeScale'=>'FL','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'80'),  
			array('typeScale'=>'TT','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'83'),  
			array('typeScale'=>'TT','pdMin'=>'28', 'pdMax'=>'29', 'ce'=>'85'),
			array('typeScale'=>'TT','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'89'),  
			array('typeScale'=>'TT','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'91'), 
			array('typeScale'=>'TT','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'94'), 
			array('typeScale'=>'TT','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'98'), 
			array('typeScale'=>'TT','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'99'), 
			array('typeScale'=>'TT','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'102'), 
			array('typeScale'=>'TT','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'105'), 
			array('typeScale'=>'TT','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'109'), 
			array('typeScale'=>'TT','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'113'), 
			array('typeScale'=>'TT','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'116'), 
			array('typeScale'=>'TT','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'118'), 
			array('typeScale'=>'TT','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'119'), 
			array('typeScale'=>'TT','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'123'), 
			array('typeScale'=>'TT','pdMin'=>'43', 'pdMax'=>'45', 'ce'=>'126'), 
			array('typeScale'=>'CI','pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),   
			array('typeScale'=>'CI','pdMin'=>'17', 'pdMax'=>'18', 'ce'=>'68'),  
			array('typeScale'=>'CI','pdMin'=>'19', 'pdMax'=>'21', 'ce'=>'71'),  
			array('typeScale'=>'CI','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'73'),  
			array('typeScale'=>'CI','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'75'),  
			array('typeScale'=>'CI','pdMin'=>'24', 'pdMax'=>'25', 'ce'=>'77'),  
			array('typeScale'=>'CI','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'82'),  
			array('typeScale'=>'CI','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'84'),  
			array('typeScale'=>'CI','pdMin'=>'28', 'pdMax'=>'29', 'ce'=>'85'), 
			array('typeScale'=>'CI','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'86'),  
			array('typeScale'=>'CI','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'87'),  
			array('typeScale'=>'CI','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'88'),  
			array('typeScale'=>'CI','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'90'),  
			array('typeScale'=>'CI','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'91'),  
			array('typeScale'=>'CI','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'95'),  
			array('typeScale'=>'CI','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'98'),  
			array('typeScale'=>'CI','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'100'), 
			array('typeScale'=>'CI','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'104'), 
			array('typeScale'=>'CI','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'105'), 
			array('typeScale'=>'CI','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'109'), 
			array('typeScale'=>'CI','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'111'), 
			array('typeScale'=>'CI','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'113'), 
			array('typeScale'=>'CI','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'119'), 
			array('typeScale'=>'CI','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'124'), 
			array('typeScale'=>'CI','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'130'), 
			array('typeScale'=>'FE','pdMin'=>'0', 'pdMax'=>'22', 'ce'=>'65'),   
			array('typeScale'=>'FE','pdMin'=>'23', 'pdMax'=>'25', 'ce'=>'68'),  
			array('typeScale'=>'FE','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'71'),  
			array('typeScale'=>'FE','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'77'),  
			array('typeScale'=>'FE','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'79'),  
			array('typeScale'=>'FE','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'82'),  
			array('typeScale'=>'FE','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'83'),  
			array('typeScale'=>'FE','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'85'),  
			array('typeScale'=>'FE','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'88'),  
			array('typeScale'=>'FE','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'91'),  
			array('typeScale'=>'FE','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'94'),  
			array('typeScale'=>'FE','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'100'),  
			array('typeScale'=>'FE','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'103'),
			array('typeScale'=>'FE','pdMin'=>'37', 'pdMax'=>'38', 'ce'=>'109'),  
			array('typeScale'=>'FE','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'113'), 
			array('typeScale'=>'FE','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'119'), 
			array('typeScale'=>'FE','pdMin'=>'41', 'pdMax'=>'45', 'ce'=>'128'), 
			array('typeScale'=>'OP','pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),   
			array('typeScale'=>'OP','pdMin'=>'17', 'pdMax'=>'18', 'ce'=>'68'),  
			array('typeScale'=>'OP','pdMin'=>'19', 'pdMax'=>'20', 'ce'=>'71'),  
			array('typeScale'=>'OP','pdMin'=>'21', 'pdMax'=>'22', 'ce'=>'73'),  
			array('typeScale'=>'OP','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'75'),  
			array('typeScale'=>'OP','pdMin'=>'24', 'pdMax'=>'25', 'ce'=>'79'),  
			array('typeScale'=>'OP','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'80'),  
			array('typeScale'=>'OP','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'81'),  
			array('typeScale'=>'OP','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'82'),  
			array('typeScale'=>'OP','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'86'),  
			array('typeScale'=>'OP','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'89'),  
			array('typeScale'=>'OP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'91'),  
			array('typeScale'=>'OP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'93'), 
			array('typeScale'=>'OP','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'96'), 
			array('typeScale'=>'OP','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'101'), 
			array('typeScale'=>'OP','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'103'), 
			array('typeScale'=>'OP','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'108'), 
			array('typeScale'=>'OP','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'112'),  
			array('typeScale'=>'OP','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'118'), 
			array('typeScale'=>'OP','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'122'), 
			array('typeScale'=>'OP','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'128'), 
			array('typeScale'=>'CERA','pdMin'=>'40', 'pdMax'=>'91', 'ce'=>'65'),  
			array('typeScale'=>'CERA','pdMin'=>'92', 'pdMax'=>'108', 'ce'=>'68'), 
			array('typeScale'=>'CERA','pdMin'=>'109', 'pdMax'=>'113', 'ce'=>'71'), 
			array('typeScale'=>'CERA','pdMin'=>'114', 'pdMax'=>'116', 'ce'=>'73'), 
			array('typeScale'=>'CERA','pdMin'=>'117', 'pdMax'=>'122', 'ce'=>'75'), 
			array('typeScale'=>'CERA','pdMin'=>'123', 'pdMax'=>'128', 'ce'=>'77'), 
			array('typeScale'=>'CERA','pdMin'=>'129', 'pdMax'=>'130', 'ce'=>'78'), 
			array('typeScale'=>'CERA','pdMin'=>'131', 'pdMax'=>'131', 'ce'=>'79'), 
			array('typeScale'=>'CERA','pdMin'=>'132', 'pdMax'=>'133', 'ce'=>'80'), 
			array('typeScale'=>'CERA','pdMin'=>'134', 'pdMax'=>'135', 'ce'=>'81'), 
			array('typeScale'=>'CERA','pdMin'=>'136', 'pdMax'=>'137', 'ce'=>'82'), 
			array('typeScale'=>'CERA','pdMin'=>'138', 'pdMax'=>'138', 'ce'=>'83'), 
			array('typeScale'=>'CERA','pdMin'=>'139', 'pdMax'=>'141', 'ce'=>'85'), 
			array('typeScale'=>'CERA','pdMin'=>'142', 'pdMax'=>'144', 'ce'=>'86'), 
			array('typeScale'=>'CERA','pdMin'=>'145', 'pdMax'=>'145', 'ce'=>'87'), 
			array('typeScale'=>'CERA','pdMin'=>'146', 'pdMax'=>'146', 'ce'=>'88'), 
			array('typeScale'=>'CERA','pdMin'=>'147', 'pdMax'=>'147', 'ce'=>'89'), 
			array('typeScale'=>'CERA','pdMin'=>'148', 'pdMax'=>'150', 'ce'=>'90'), 
			array('typeScale'=>'CERA','pdMin'=>'151', 'pdMax'=>'151', 'ce'=>'91'), 
			array('typeScale'=>'CERA','pdMin'=>'152', 'pdMax'=>'153', 'ce'=>'92'), 
			array('typeScale'=>'CERA','pdMin'=>'154', 'pdMax'=>'156', 'ce'=>'93'), 
			array('typeScale'=>'CERA','pdMin'=>'157', 'pdMax'=>'159', 'ce'=>'94'), 
			array('typeScale'=>'CERA','pdMin'=>'160', 'pdMax'=>'160', 'ce'=>'96'), 
			array('typeScale'=>'CERA','pdMin'=>'161', 'pdMax'=>'161', 'ce'=>'99'), 
			array('typeScale'=>'CERA','pdMin'=>'162', 'pdMax'=>'162', 'ce'=>'100'), 
			array('typeScale'=>'CERA','pdMin'=>'163', 'pdMax'=>'163', 'ce'=>'101'),
			array('typeScale'=>'CERA','pdMin'=>'164', 'pdMax'=>'164', 'ce'=>'102'),
			array('typeScale'=>'CERA','pdMin'=>'165', 'pdMax'=>'165', 'ce'=>'104'),
			array('typeScale'=>'CERA','pdMin'=>'166', 'pdMax'=>'168', 'ce'=>'106'),
			array('typeScale'=>'CERA','pdMin'=>'169', 'pdMax'=>'170', 'ce'=>'107'),
			array('typeScale'=>'CERA','pdMin'=>'171', 'pdMax'=>'171', 'ce'=>'109'),
			array('typeScale'=>'CERA','pdMin'=>'172', 'pdMax'=>'172', 'ce'=>'110'),
			array('typeScale'=>'CERA','pdMin'=>'173', 'pdMax'=>'173', 'ce'=>'112'),
			array('typeScale'=>'CERA','pdMin'=>'174', 'pdMax'=>'175', 'ce'=>'113'),
			array('typeScale'=>'CERA','pdMin'=>'176', 'pdMax'=>'176', 'ce'=>'114'),
			array('typeScale'=>'CERA','pdMin'=>'177', 'pdMax'=>'178', 'ce'=>'115'),
			array('typeScale'=>'CERA','pdMin'=>'179', 'pdMax'=>'179', 'ce'=>'116'),
			array('typeScale'=>'CERA','pdMin'=>'180', 'pdMax'=>'180', 'ce'=>'117'),
			array('typeScale'=>'CERA','pdMin'=>'181', 'pdMax'=>'181', 'ce'=>'119'),
			array('typeScale'=>'CERA','pdMin'=>'182', 'pdMax'=>'182', 'ce'=>'120'),
			array('typeScale'=>'CERA','pdMin'=>'183', 'pdMax'=>'183', 'ce'=>'121'),
			array('typeScale'=>'CERA','pdMin'=>'184', 'pdMax'=>'184', 'ce'=>'122'),
			array('typeScale'=>'CERA','pdMin'=>'185', 'pdMax'=>'185', 'ce'=>'123'),
			array('typeScale'=>'CERA','pdMin'=>'186', 'pdMax'=>'186', 'ce'=>'124'),
			array('typeScale'=>'CERA','pdMin'=>'187', 'pdMax'=>'188', 'ce'=>'126'),
			array('typeScale'=>'CERA','pdMin'=>'189', 'pdMax'=>'200', 'ce'=>'128'),
			array('typeScale'=>'CEER','pdMin'=>'24', 'pdMax'=>'76', 'ce'=>'65'),    
			array('typeScale'=>'CEER','pdMin'=>'77', 'pdMax'=>'80', 'ce'=>'68'),    
			array('typeScale'=>'CEER','pdMin'=>'81', 'pdMax'=>'81', 'ce'=>'81'),    
			array('typeScale'=>'CEER','pdMin'=>'82', 'pdMax'=>'82', 'ce'=>'83'),    
			array('typeScale'=>'CEER','pdMin'=>'83', 'pdMax'=>'84', 'ce'=>'75'),    
			array('typeScale'=>'CEER','pdMin'=>'85', 'pdMax'=>'85', 'ce'=>'77'),    
			array('typeScale'=>'CEER','pdMin'=>'86', 'pdMax'=>'86', 'ce'=>'79'),    
			array('typeScale'=>'CEER','pdMin'=>'87', 'pdMax'=>'87', 'ce'=>'80'),    
			array('typeScale'=>'CEER','pdMin'=>'88', 'pdMax'=>'88', 'ce'=>'81'),    
			array('typeScale'=>'CEER','pdMin'=>'89', 'pdMax'=>'90', 'ce'=>'82'),    
			array('typeScale'=>'CEER','pdMin'=>'91', 'pdMax'=>'91', 'ce'=>'85'),    
			array('typeScale'=>'CEER','pdMin'=>'92', 'pdMax'=>'92', 'ce'=>'86'),    
			array('typeScale'=>'CEER','pdMin'=>'93', 'pdMax'=>'93', 'ce'=>'88'),   
			array('typeScale'=>'CEER','pdMin'=>'94', 'pdMax'=>'94', 'ce'=>'90'), 
			array('typeScale'=>'CEER','pdMin'=>'95', 'pdMax'=>'95', 'ce'=>'92'),
			array('typeScale'=>'CEER','pdMin'=>'96', 'pdMax'=>'97', 'ce'=>'94'),
			array('typeScale'=>'CEER','pdMin'=>'98', 'pdMax'=>'98', 'ce'=>'96'), 
			array('typeScale'=>'CEER','pdMin'=>'99', 'pdMax'=>'99', 'ce'=>'97'), 
			array('typeScale'=>'CEER','pdMin'=>'100', 'pdMax'=>'100', 'ce'=>'99'), 
			array('typeScale'=>'CEER','pdMin'=>'101', 'pdMax'=>'101', 'ce'=>'100'), 
			array('typeScale'=>'CEER','pdMin'=>'102', 'pdMax'=>'102', 'ce'=>'103'), 
			array('typeScale'=>'CEER','pdMin'=>'103', 'pdMax'=>'103', 'ce'=>'105'), 
			array('typeScale'=>'CEER','pdMin'=>'104', 'pdMax'=>'104', 'ce'=>'106'), 
			array('typeScale'=>'CEER','pdMin'=>'105', 'pdMax'=>'105', 'ce'=>'109'), 
			array('typeScale'=>'CEER','pdMin'=>'106', 'pdMax'=>'106', 'ce'=>'111'), 
			array('typeScale'=>'CEER','pdMin'=>'107', 'pdMax'=>'107', 'ce'=>'113'), 
			array('typeScale'=>'CEER','pdMin'=>'108', 'pdMax'=>'108', 'ce'=>'116'), 
			array('typeScale'=>'CEER','pdMin'=>'109', 'pdMax'=>'109', 'ce'=>'118'), 
			array('typeScale'=>'CEER','pdMin'=>'110', 'pdMax'=>'110', 'ce'=>'119'), 
			array('typeScale'=>'CEER','pdMin'=>'111', 'pdMax'=>'111', 'ce'=>'124'), 
			array('typeScale'=>'CEER','pdMin'=>'112', 'pdMax'=>'112', 'ce'=>'126'), 
			array('typeScale'=>'CEER','pdMin'=>'113', 'pdMax'=>'113', 'ce'=>'128'), 
			array('typeScale'=>'CEER','pdMin'=>'114', 'pdMax'=>'120', 'ce'=>'130'), 
			array('typeScale'=>'CEAD','pdMin'=>'26', 'pdMax'=>'70', 'ce'=>'65'),   
			array('typeScale'=>'CEAD','pdMin'=>'71', 'pdMax'=>'74', 'ce'=>'68'),   
			array('typeScale'=>'CEAD','pdMin'=>'75', 'pdMax'=>'78', 'ce'=>'71'),   
			array('typeScale'=>'CEAD','pdMin'=>'79', 'pdMax'=>'82', 'ce'=>'73'),   
			array('typeScale'=>'CEAD','pdMin'=>'83', 'pdMax'=>'84', 'ce'=>'75'), 
			array('typeScale'=>'CEAD','pdMin'=>'85', 'pdMax'=>'85', 'ce'=>'77'),   
			array('typeScale'=>'CEAD','pdMin'=>'86', 'pdMax'=>'86', 'ce'=>'78'),   
			array('typeScale'=>'CEAD','pdMin'=>'87', 'pdMax'=>'87', 'ce'=>'79'),   
			array('typeScale'=>'CEAD','pdMin'=>'88', 'pdMax'=>'88', 'ce'=>'82'),   
			array('typeScale'=>'CEAD','pdMin'=>'89', 'pdMax'=>'90', 'ce'=>'84'),   
			array('typeScale'=>'CEAD','pdMin'=>'91', 'pdMax'=>'91', 'ce'=>'85'),   
			array('typeScale'=>'CEAD','pdMin'=>'92', 'pdMax'=>'92', 'ce'=>'86'),   
			array('typeScale'=>'CEAD','pdMin'=>'93', 'pdMax'=>'93', 'ce'=>'88'),   
			array('typeScale'=>'CEAD','pdMin'=>'94', 'pdMax'=>'95', 'ce'=>'89'),
			array('typeScale'=>'CEAD','pdMin'=>'96', 'pdMax'=>'96', 'ce'=>'90'),   
			array('typeScale'=>'CEAD','pdMin'=>'97', 'pdMax'=>'97', 'ce'=>'91'), 
			array('typeScale'=>'CEAD','pdMin'=>'98', 'pdMax'=>'98', 'ce'=>'92'), 
			array('typeScale'=>'CEAD','pdMin'=>'99', 'pdMax'=>'100', 'ce'=>'94'), 
			array('typeScale'=>'CEAD','pdMin'=>'101', 'pdMax'=>'101', 'ce'=>'96'), 
			array('typeScale'=>'CEAD','pdMin'=>'102', 'pdMax'=>'102', 'ce'=>'99'), 
			array('typeScale'=>'CEAD','pdMin'=>'103', 'pdMax'=>'103', 'ce'=>'100'),
			array('typeScale'=>'CEAD','pdMin'=>'104', 'pdMax'=>'104', 'ce'=>'101'),
			array('typeScale'=>'CEAD','pdMin'=>'105', 'pdMax'=>'105', 'ce'=>'102'),
			array('typeScale'=>'CEAD','pdMin'=>'106', 'pdMax'=>'106', 'ce'=>'103'),
			array('typeScale'=>'CEAD','pdMin'=>'107', 'pdMax'=>'107', 'ce'=>'104'),
			array('typeScale'=>'CEAD','pdMin'=>'108', 'pdMax'=>'109', 'ce'=>'106'),
			array('typeScale'=>'CEAD','pdMin'=>'110', 'pdMax'=>'110', 'ce'=>'107'),
			array('typeScale'=>'CEAD','pdMin'=>'111', 'pdMax'=>'111', 'ce'=>'110'),
			array('typeScale'=>'CEAD','pdMin'=>'112', 'pdMax'=>'112', 'ce'=>'112'),
			array('typeScale'=>'CEAD','pdMin'=>'113', 'pdMax'=>'113', 'ce'=>'115'),
			array('typeScale'=>'CEAD','pdMin'=>'114', 'pdMax'=>'114', 'ce'=>'116'),
			array('typeScale'=>'CEAD','pdMin'=>'115', 'pdMax'=>'115', 'ce'=>'118'),
			array('typeScale'=>'CEAD','pdMin'=>'116', 'pdMax'=>'116', 'ce'=>'121'),
			array('typeScale'=>'CEAD','pdMin'=>'117', 'pdMax'=>'117', 'ce'=>'124'), 
			array('typeScale'=>'CEAD','pdMin'=>'118', 'pdMax'=>'119', 'ce'=>'126'),
			array('typeScale'=>'CEAD','pdMin'=>'120', 'pdMax'=>'121', 'ce'=>'128'),
			array('typeScale'=>'CEAD','pdMin'=>'122', 'pdMax'=>'130', 'ce'=>'130'),
			array('typeScale'=>'CEMT','pdMin'=>'18', 'pdMax'=>'40', 'ce'=>'65'),  
			array('typeScale'=>'CEMT','pdMin'=>'41', 'pdMax'=>'42', 'ce'=>'71'),  
			array('typeScale'=>'CEMT','pdMin'=>'43', 'pdMax'=>'45', 'ce'=>'75'),       
			array('typeScale'=>'CEMT','pdMin'=>'46', 'pdMax'=>'49', 'ce'=>'77'),  
			array('typeScale'=>'CEMT','pdMin'=>'50', 'pdMax'=>'53', 'ce'=>'78'),  
			array('typeScale'=>'CEMT','pdMin'=>'54', 'pdMax'=>'56', 'ce'=>'79'),  
			array('typeScale'=>'CEMT','pdMin'=>'57', 'pdMax'=>'57', 'ce'=>'80'),  
			array('typeScale'=>'CEMT','pdMin'=>'58', 'pdMax'=>'59', 'ce'=>'82'),  
			array('typeScale'=>'CEMT','pdMin'=>'60', 'pdMax'=>'61', 'ce'=>'86'),  
			array('typeScale'=>'CEMT','pdMin'=>'62', 'pdMax'=>'62', 'ce'=>'90'),  
			array('typeScale'=>'CEMT','pdMin'=>'63', 'pdMax'=>'63', 'ce'=>'92'),  
			array('typeScale'=>'CEMT','pdMin'=>'64', 'pdMax'=>'64', 'ce'=>'93'),  
			array('typeScale'=>'CEMT','pdMin'=>'65', 'pdMax'=>'65', 'ce'=>'95'),  
			array('typeScale'=>'CEMT','pdMin'=>'66', 'pdMax'=>'67', 'ce'=>'96'),  
			array('typeScale'=>'CEMT','pdMin'=>'68', 'pdMax'=>'69', 'ce'=>'97'),  
			array('typeScale'=>'CEMT','pdMin'=>'70', 'pdMax'=>'70', 'ce'=>'98'),
			array('typeScale'=>'CEMT','pdMin'=>'71', 'pdMax'=>'71', 'ce'=>'100'),  
			array('typeScale'=>'CEMT','pdMin'=>'72', 'pdMax'=>'72', 'ce'=>'101'),  
			array('typeScale'=>'CEMT','pdMin'=>'73', 'pdMax'=>'73', 'ce'=>'104'),  
			array('typeScale'=>'CEMT','pdMin'=>'74', 'pdMax'=>'74', 'ce'=>'105'), 
			array('typeScale'=>'CEMT','pdMin'=>'75', 'pdMax'=>'75', 'ce'=>'107'), 
			array('typeScale'=>'CEMT','pdMin'=>'76', 'pdMax'=>'76', 'ce'=>'109'), 
			array('typeScale'=>'CEMT','pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'110'), 
			array('typeScale'=>'CEMT','pdMin'=>'78', 'pdMax'=>'78', 'ce'=>'112'), 
			array('typeScale'=>'CEMT','pdMin'=>'79', 'pdMax'=>'79', 'ce'=>'115'), 
			array('typeScale'=>'CEMT','pdMin'=>'80', 'pdMax'=>'80', 'ce'=>'116'), 
			array('typeScale'=>'CEMT','pdMin'=>'81', 'pdMax'=>'81', 'ce'=>'120'), 
			array('typeScale'=>'CEMT','pdMin'=>'82', 'pdMax'=>'82', 'ce'=>'121'),
			array('typeScale'=>'CEMT','pdMin'=>'83', 'pdMax'=>'83', 'ce'=>'122'), 
			array('typeScale'=>'CEMT','pdMin'=>'84', 'pdMax'=>'84', 'ce'=>'128'),
			array('typeScale'=>'CEMT','pdMin'=>'85', 'pdMax'=>'90', 'ce'=>'130'),
			array('typeScale'=>'CEAG','pdMin'=>'17', 'pdMax'=>'40', 'ce'=>'65'),  
			array('typeScale'=>'CEAG','pdMin'=>'41', 'pdMax'=>'42', 'ce'=>'68'),  
			array('typeScale'=>'CEAG','pdMin'=>'43', 'pdMax'=>'47', 'ce'=>'71'),  
			array('typeScale'=>'CEAG','pdMin'=>'48', 'pdMax'=>'49', 'ce'=>'73'),  
			array('typeScale'=>'CEAG','pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'75'),  
			array('typeScale'=>'CEAG','pdMin'=>'51', 'pdMax'=>'51', 'ce'=>'77'),  
			array('typeScale'=>'CEAG','pdMin'=>'52', 'pdMax'=>'53', 'ce'=>'78'),  
			array('typeScale'=>'CEAG','pdMin'=>'54', 'pdMax'=>'54', 'ce'=>'79'),  
			array('typeScale'=>'CEAG','pdMin'=>'55', 'pdMax'=>'55', 'ce'=>'81'),  
			array('typeScale'=>'CEAG','pdMin'=>'56', 'pdMax'=>'58', 'ce'=>'82'),  
			array('typeScale'=>'CEAG','pdMin'=>'59', 'pdMax'=>'59', 'ce'=>'83'),  
			array('typeScale'=>'CEAG','pdMin'=>'60', 'pdMax'=>'61', 'ce'=>'86'),  
			array('typeScale'=>'CEAG','pdMin'=>'62', 'pdMax'=>'63', 'ce'=>'87'),  
			array('typeScale'=>'CEAG','pdMin'=>'64', 'pdMax'=>'64', 'ce'=>'88'),  
			array('typeScale'=>'CEAG','pdMin'=>'65', 'pdMax'=>'65', 'ce'=>'90'),  
			array('typeScale'=>'CEAG','pdMin'=>'66', 'pdMax'=>'66', 'ce'=>'94'),  
			array('typeScale'=>'CEAG','pdMin'=>'67', 'pdMax'=>'67', 'ce'=>'96'),  
			array('typeScale'=>'CEAG','pdMin'=>'68', 'pdMax'=>'68', 'ce'=>'99'),  
			array('typeScale'=>'CEAG','pdMin'=>'69', 'pdMax'=>'79', 'ce'=>'101'), 
			array('typeScale'=>'CEAG','pdMin'=>'70', 'pdMax'=>'70', 'ce'=>'104'), 
			array('typeScale'=>'CEAG','pdMin'=>'71', 'pdMax'=>'72', 'ce'=>'105'), 
			array('typeScale'=>'CEAG','pdMin'=>'73', 'pdMax'=>'73', 'ce'=>'110'), 
			array('typeScale'=>'CEAG','pdMin'=>'74', 'pdMax'=>'74', 'ce'=>'112'), 
			array('typeScale'=>'CEAG','pdMin'=>'75', 'pdMax'=>'75', 'ce'=>'115'), 
			array('typeScale'=>'CEAG','pdMin'=>'76', 'pdMax'=>'76', 'ce'=>'118'), 
			array('typeScale'=>'CEAG','pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'121'), 
			array('typeScale'=>'CEAG','pdMin'=>'78', 'pdMax'=>'85', 'ce'=>'130'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'117', 'pdMax'=>'319', 'ce'=>'65'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'320', 'pdMax'=>'342', 'ce'=>'68'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'343', 'pdMax'=>'350', 'ce'=>'71'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'351', 'pdMax'=>'361', 'ce'=>'73'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'362', 'pdMax'=>'370', 'ce'=>'75'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'371', 'pdMax'=>'375', 'ce'=>'77'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'376', 'pdMax'=>'487', 'ce'=>'78'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'388', 'pdMax'=>'401', 'ce'=>'79'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'402', 'pdMax'=>'403', 'ce'=>'80'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'404', 'pdMax'=>'405', 'ce'=>'81'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'406', 'pdMax'=>'410', 'ce'=>'82'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'411', 'pdMax'=>'411', 'ce'=>'84'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'412', 'pdMax'=>'413', 'ce'=>'85'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'414', 'pdMax'=>'426', 'ce'=>'86'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'427', 'pdMax'=>'429', 'ce'=>'87'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'430', 'pdMax'=>'434', 'ce'=>'88'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'435', 'pdMax'=>'443', 'ce'=>'89'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'444', 'pdMax'=>'447', 'ce'=>'90'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'448', 'pdMax'=>'450', 'ce'=>'91'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'451', 'pdMax'=>'452', 'ce'=>'92'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'453', 'pdMax'=>'454', 'ce'=>'93'),
			array('typeScale'=>'CETOTAL','pdMin'=>'455', 'pdMax'=>'459', 'ce'=>'94'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'460', 'pdMax'=>'460', 'ce'=>'95'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'461', 'pdMax'=>'465', 'ce'=>'96'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'466', 'pdMax'=>'467', 'ce'=>'97'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'468', 'pdMax'=>'469', 'ce'=>'98'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'470', 'pdMax'=>'472', 'ce'=>'99'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'473', 'pdMax'=>'476', 'ce'=>'100'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'477', 'pdMax'=>'479', 'ce'=>'101'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'480', 'pdMax'=>'481', 'ce'=>'102'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'482', 'pdMax'=>'482', 'ce'=>'103'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'483', 'pdMax'=>'483', 'ce'=>'104'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'484', 'pdMax'=>'484', 'ce'=>'106'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'485', 'pdMax'=>'485', 'ce'=>'107'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'486', 'pdMax'=>'487', 'ce'=>'108'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'488', 'pdMax'=>'493', 'ce'=>'109'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'494', 'pdMax'=>'496', 'ce'=>'110'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'497', 'pdMax'=>'498', 'ce'=>'111'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'499', 'pdMax'=>'501', 'ce'=>'112'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'502', 'pdMax'=>'504', 'ce'=>'113'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'505', 'pdMax'=>'506', 'ce'=>'114'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'507', 'pdMax'=>'508', 'ce'=>'115'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'509', 'pdMax'=>'509', 'ce'=>'116'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'510', 'pdMax'=>'511', 'ce'=>'117'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'512', 'pdMax'=>'515', 'ce'=>'118'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'516', 'pdMax'=>'518', 'ce'=>'119'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'519', 'pdMax'=>'521', 'ce'=>'120'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'522', 'pdMax'=>'523', 'ce'=>'121'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'524', 'pdMax'=>'526', 'ce'=>'122'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'527', 'pdMax'=>'529', 'ce'=>'123'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'530', 'pdMax'=>'532', 'ce'=>'124'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'533', 'pdMax'=>'535', 'ce'=>'126'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'536', 'pdMax'=>'540', 'ce'=>'128'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'541', 'pdMax'=>'585', 'ce'=>'130'),			
		);
         
        foreach ($lstStructure as $lst) {

            $objeto = new ICEF1620Baremo();
            $objeto->setTypeScale($lst['typeScale']);
            $objeto->setPdMin($lst['pdMin']);
            $objeto->setPdMax($lst['pdMax']);
            $objeto->setCE($lst['ce']);
            
            $manager->persist($objeto);                              
        }

        $manager->flush();    
	}
}
