<?php

namespace Jaxxes\TestICEBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture; 
use Symfony\Component\DependencyInjection\ContainerAwareInterface;

use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerInterface;

use Jaxxes\TestICEBundle\Entity\ICEM2130Baremo;

/**
 * Fixtures de la entidad Resume.
 * Crea el registro de la cabecera para Resume = Ficha del candidato
 */
 
// class Resumes implements FixtureInterface
 class ICEM2130Baremos extends AbstractFixture implements OrderedFixtureInterface
{
	
    public function getOrder()
    {
        return 4;
    }
    private $container;
    
    
    
    public function load(ObjectManager $manager)
    {
        $lstStructure = array(				
			array('typeScale'=>'IMP','pdMin'=>'35', 'pdMax'=>'40', 'ce'=>'133'),
			array('typeScale'=>'IMP','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'130'),
			array('typeScale'=>'IMP','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'128'),
			array('typeScale'=>'IMP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'124'),
			array('typeScale'=>'IMP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'122'),
			array('typeScale'=>'IMP','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'120'),
			array('typeScale'=>'IMP','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'117'),
			array('typeScale'=>'IMP','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'115'),
			array('typeScale'=>'IMP','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'111'),
			array('typeScale'=>'IMP','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'108'),
			array('typeScale'=>'IMP','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'106'),
			array('typeScale'=>'IMP','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'103'),
			array('typeScale'=>'IMP','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'100'),
			array('typeScale'=>'IMP','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'95'),
			array('typeScale'=>'IMP','pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'91'),
			array('typeScale'=>'IMP','pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'88'),
			array('typeScale'=>'IMP','pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'84'),
			array('typeScale'=>'IMP','pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'80'),
			array('typeScale'=>'IMP','pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'77'),
			array('typeScale'=>'IMP','pdMin'=>'16', 'pdMax'=>'16', 'ce'=>'71'),
			array('typeScale'=>'IMP','pdMin'=>'15', 'pdMax'=>'15', 'ce'=>'68'),
			array('typeScale'=>'IMP','pdMin'=>'0',  'pdMax'=>'14', 'ce'=>'65'),
			array('typeScale'=>'IMN','pdMin'=>'21', 'pdMax'=>'35', 'ce'=>'133'),
			array('typeScale'=>'IMN','pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'128'),
			array('typeScale'=>'IMN','pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'126'),
			array('typeScale'=>'IMN','pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'124'),
			array('typeScale'=>'IMN','pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'122'),
			array('typeScale'=>'IMN','pdMin'=>'16', 'pdMax'=>'16', 'ce'=>'120'),
			array('typeScale'=>'IMN','pdMin'=>'15', 'pdMax'=>'15', 'ce'=>'116'),
			array('typeScale'=>'IMN','pdMin'=>'14', 'pdMax'=>'14', 'ce'=>'114'),
			array('typeScale'=>'IMN','pdMin'=>'13', 'pdMax'=>'13', 'ce'=>'111'),
			array('typeScale'=>'IMN','pdMin'=>'12', 'pdMax'=>'12', 'ce'=>'108'),
			array('typeScale'=>'IMN','pdMin'=>'11', 'pdMax'=>'11', 'ce'=>'103'),
			array('typeScale'=>'IMN','pdMin'=>'10', 'pdMax'=>'10', 'ce'=>'99' ),
			array('typeScale'=>'IMN','pdMin'=>'9',  'pdMax'=>'9', 'ce'=>'93'  ),
			array('typeScale'=>'IMN','pdMin'=>'8',  'pdMax'=>'8', 'ce'=>'89'  ),
			array('typeScale'=>'IMN','pdMin'=>'0',  'pdMax'=>'7', 'ce'=>'65'  ),
			array('typeScale'=>'CM','pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'133'),
			array('typeScale'=>'CM','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'126'),
			array('typeScale'=>'CM','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'124'),
			array('typeScale'=>'CM','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'120'),
			array('typeScale'=>'CM','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'116'),
			array('typeScale'=>'CM','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'112'),
			array('typeScale'=>'CM','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'109'),
			array('typeScale'=>'CM','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'106'),
			array('typeScale'=>'CM','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'103'),
			array('typeScale'=>'CM','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'100'),
			array('typeScale'=>'CM','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'97' ),
			array('typeScale'=>'CM','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'92' ),
			array('typeScale'=>'CM','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'89' ),
			array('typeScale'=>'CM','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'85' ),
			array('typeScale'=>'CM','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'82' ),
			array('typeScale'=>'CM','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'79' ),
			array('typeScale'=>'CM','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'75' ),
			array('typeScale'=>'CM','pdMin'=>'21', 'pdMax'=>'22', 'ce'=>'71' ),
			array('typeScale'=>'CM','pdMin'=>'19', 'pdMax'=>'20', 'ce'=>'68' ),
			array('typeScale'=>'CM','pdMin'=>'0',  'pdMax'=>'18', 'ce'=>'65'  ),
			array('typeScale'=>'SE','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'133'),
			array('typeScale'=>'SE','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'128'),
			array('typeScale'=>'SE','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'124'),
			array('typeScale'=>'SE','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'120'),
			array('typeScale'=>'SE','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'115'),
			array('typeScale'=>'SE','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'110'),
			array('typeScale'=>'SE','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'106'),
			array('typeScale'=>'SE','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'101'),
			array('typeScale'=>'SE','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'96' ),
			array('typeScale'=>'SE','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'93' ),
			array('typeScale'=>'SE','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'90' ),
			array('typeScale'=>'SE','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'87' ),
			array('typeScale'=>'SE','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'83' ),
			array('typeScale'=>'SE','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'79' ),
			array('typeScale'=>'SE','pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'75' ),
			array('typeScale'=>'SE','pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'71' ),
			array('typeScale'=>'SE','pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'68' ),
			array('typeScale'=>'SE','pdMin'=>'0',  'pdMax'=>'18', 'ce'=>'65' ), 
			array('typeScale'=>'AE','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'118'),
			array('typeScale'=>'AE','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'113'),
			array('typeScale'=>'AE','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'109'),
			array('typeScale'=>'AE','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'105'),
			array('typeScale'=>'AE','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'102'),
			array('typeScale'=>'AE','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'98' ),
			array('typeScale'=>'AE','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'95' ),
			array('typeScale'=>'AE','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'92' ),
			array('typeScale'=>'AE','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'90' ),
			array('typeScale'=>'AE','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'88' ),
			array('typeScale'=>'AE','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'85' ),
			array('typeScale'=>'AE','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'82' ),
			array('typeScale'=>'AE','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'79' ),
			array('typeScale'=>'AE','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'78' ),
			array('typeScale'=>'AE','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'77' ),
			array('typeScale'=>'AE','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'75' ),
			array('typeScale'=>'AE','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'73' ),
			array('typeScale'=>'AE','pdMin'=>'25', 'pdMax'=>'28', 'ce'=>'71' ),
			array('typeScale'=>'AE','pdMin'=>'21', 'pdMax'=>'24', 'ce'=>'68' ),
			array('typeScale'=>'AE','pdMin'=>'0',  'pdMax'=>'20', 'ce'=>'65' ),
			array('typeScale'=>'AR','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'123'),
			array('typeScale'=>'AR','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'118'),
			array('typeScale'=>'AR','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'113'),
			array('typeScale'=>'AR','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'110'),
			array('typeScale'=>'AR','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'105'),
			array('typeScale'=>'AR','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'101'),
			array('typeScale'=>'AR','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'98' ),
			array('typeScale'=>'AR','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'95' ),
			array('typeScale'=>'AR','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'92' ),
			array('typeScale'=>'AR','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'89' ),
			array('typeScale'=>'AR','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'86' ),
			array('typeScale'=>'AR','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'82' ),
			array('typeScale'=>'AR','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'81' ),
			array('typeScale'=>'AR','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'79' ),
			array('typeScale'=>'AR','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'77' ),
			array('typeScale'=>'AR','pdMin'=>'29', 'pdMax'=>'30', 'ce'=>'73' ),
			array('typeScale'=>'AR','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'71' ),
			array('typeScale'=>'AR','pdMin'=>'24', 'pdMax'=>'27', 'ce'=>'68' ),
			array('typeScale'=>'AR','pdMin'=>'0',  'pdMax'=>'23', 'ce'=>'65' ),
			array('typeScale'=>'IN','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'130' ),
			array('typeScale'=>'IN','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'128' ),
			array('typeScale'=>'IN','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'119' ),
			array('typeScale'=>'IN','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'115' ),
			array('typeScale'=>'IN','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'111' ),
			array('typeScale'=>'IN','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'106' ),
			array('typeScale'=>'IN','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'101' ),
			array('typeScale'=>'IN','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'96'  ),
			array('typeScale'=>'IN','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'93'  ),
			array('typeScale'=>'IN','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'90'  ),
			array('typeScale'=>'IN','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'86'  ),
			array('typeScale'=>'IN','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'82'  ),
			array('typeScale'=>'IN','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'78'  ),
			array('typeScale'=>'IN','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'75'  ),
			array('typeScale'=>'IN','pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'71'  ),
			array('typeScale'=>'IN','pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'68'  ),
			array('typeScale'=>'IN','pdMin'=>'0', 'pdMax'=>'19', 'ce'=>'65'   ),
			array('typeScale'=>'RI','pdMin'=>'54', 'pdMax'=>'55', 'ce'=>'133' ),
			array('typeScale'=>'RI','pdMin'=>'53', 'pdMax'=>'53', 'ce'=>'126' ),
			array('typeScale'=>'RI','pdMin'=>'52', 'pdMax'=>'52', 'ce'=>'123' ),
			array('typeScale'=>'RI','pdMin'=>'51', 'pdMax'=>'51', 'ce'=>'120' ),
			array('typeScale'=>'RI','pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'118' ),
			array('typeScale'=>'RI','pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'114' ),
			array('typeScale'=>'RI','pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'110' ),
			array('typeScale'=>'RI','pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'107' ),
			array('typeScale'=>'RI','pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'104' ),
			array('typeScale'=>'RI','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'101' ),
			array('typeScale'=>'RI','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'98'  ),
			array('typeScale'=>'RI','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'96'  ),
			array('typeScale'=>'RI','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'92'  ),
			array('typeScale'=>'RI','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'90'  ),
			array('typeScale'=>'RI','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'89'  ),
			array('typeScale'=>'RI','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'86'  ),
			array('typeScale'=>'RI','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'85'  ),
			array('typeScale'=>'RI','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'82'  ),
			array('typeScale'=>'RI','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'80'  ),
			array('typeScale'=>'RI','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'79'  ),
			array('typeScale'=>'RI','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'77'  ),
			array('typeScale'=>'RI','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'75'  ),
			array('typeScale'=>'RI','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'73'  ),
			array('typeScale'=>'RI','pdMin'=>'30', 'pdMax'=>'31', 'ce'=>'71'  ),
			array('typeScale'=>'RI','pdMin'=>'26', 'pdMax'=>'29', 'ce'=>'68'  ),
			array('typeScale'=>'RI','pdMin'=>'0',  'pdMax'=>'25', 'ce'=>'65'  ),
			array('typeScale'=>'RS','pdMin'=>'49', 'pdMax'=>'50', 'ce'=>'130' ),
			array('typeScale'=>'RS','pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'128' ),
			array('typeScale'=>'RS','pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'124' ),
			array('typeScale'=>'RS','pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'119' ),
			array('typeScale'=>'RS','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'114' ),
			array('typeScale'=>'RS','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'110' ),
			array('typeScale'=>'RS','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'107' ),
			array('typeScale'=>'RS','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'102' ),
			array('typeScale'=>'RS','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'98'  ),
			array('typeScale'=>'RS','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'94'  ),
			array('typeScale'=>'RS','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'91'  ),
			array('typeScale'=>'RS','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'89'  ),
			array('typeScale'=>'RS','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'84'  ),
			array('typeScale'=>'RS','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'81'  ),
			array('typeScale'=>'RS','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'78'  ),
			array('typeScale'=>'RS','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'73'  ),
			array('typeScale'=>'RS','pdMin'=>'32', 'pdMax'=>'33', 'ce'=>'71'  ),
			array('typeScale'=>'RS','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'68'  ),
			array('typeScale'=>'RS','pdMin'=>'0',  'pdMax'=>'30', 'ce'=>'65'  ),                                    
			array('typeScale'=>'EM','pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'133' ),
			array('typeScale'=>'EM','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'128' ),
			array('typeScale'=>'EM','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'124' ),
			array('typeScale'=>'EM','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'121' ),
			array('typeScale'=>'EM','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'118' ),
			array('typeScale'=>'EM','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'115' ),
			array('typeScale'=>'EM','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'112' ),
			array('typeScale'=>'EM','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'109' ),
			array('typeScale'=>'EM','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'104' ),
			array('typeScale'=>'EM','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'101' ),
			array('typeScale'=>'EM','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'98'  ),
			array('typeScale'=>'EM','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'94'  ),
			array('typeScale'=>'EM','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'91'  ),
			array('typeScale'=>'EM','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'87'  ),
			array('typeScale'=>'EM','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'84'  ),
			array('typeScale'=>'EM','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'81'  ),
			array('typeScale'=>'EM','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'78'  ),
			array('typeScale'=>'EM','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'75'  ),
			array('typeScale'=>'EM','pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'71'  ),
			array('typeScale'=>'EM','pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'68'  ),
			array('typeScale'=>'EM','pdMin'=>'0',  'pdMax'=>'19', 'ce'=>'65'  ),
			array('typeScale'=>'SP','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'126'),
			array('typeScale'=>'SP','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'120'),
			array('typeScale'=>'SP','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'114'),
			array('typeScale'=>'SP','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'110'),
			array('typeScale'=>'SP','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'107'),
			array('typeScale'=>'SP','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'103'),
			array('typeScale'=>'SP','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'100'),
			array('typeScale'=>'SP','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'96' ),
			array('typeScale'=>'SP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'93' ),
			array('typeScale'=>'SP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'91' ),
			array('typeScale'=>'SP','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'87' ),
			array('typeScale'=>'SP','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'84' ),
			array('typeScale'=>'SP','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'82' ),
			array('typeScale'=>'SP','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'81' ),
			array('typeScale'=>'SP','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'78' ),
			array('typeScale'=>'SP','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'75' ),
			array('typeScale'=>'SP','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'73' ),
			array('typeScale'=>'SP','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'71' ),
			array('typeScale'=>'SP','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'68' ),
			array('typeScale'=>'SP','pdMin'=>'0',  'pdMax'=>'21', 'ce'=>'65' ),
			array('typeScale'=>'PR','pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'128' ),
			array('typeScale'=>'PR','pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'124' ),
			array('typeScale'=>'PR','pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'118' ),
			array('typeScale'=>'PR','pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'114' ),
			array('typeScale'=>'PR','pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'111' ),
			array('typeScale'=>'PR','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'108' ),
			array('typeScale'=>'PR','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'104' ),
			array('typeScale'=>'PR','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'101' ),
			array('typeScale'=>'PR','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'98'  ),
			array('typeScale'=>'PR','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'95'  ),
			array('typeScale'=>'PR','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'92'  ),
			array('typeScale'=>'PR','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'90'  ),
			array('typeScale'=>'PR','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'87'  ),
			array('typeScale'=>'PR','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'85'  ),
			array('typeScale'=>'PR','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'82'  ),
			array('typeScale'=>'PR','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'81'  ),
			array('typeScale'=>'PR','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'80'  ),
			array('typeScale'=>'PR','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'78'  ),
			array('typeScale'=>'PR','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'77'  ),
			array('typeScale'=>'PR','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'75'  ),
			array('typeScale'=>'PR','pdMin'=>'29', 'pdMax'=>'30', 'ce'=>'71'  ),
			array('typeScale'=>'PR','pdMin'=>'26', 'pdMax'=>'28', 'ce'=>'68'  ),
			array('typeScale'=>'PR','pdMin'=>'0',  'pdMax'=>'25', 'ce'=>'65'  ),
			array('typeScale'=>'FL','pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'133'),
			array('typeScale'=>'FL','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'128'),
			array('typeScale'=>'FL','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'123'),
			array('typeScale'=>'FL','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'121'),
			array('typeScale'=>'FL','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'118'),
			array('typeScale'=>'FL','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'114'),
			array('typeScale'=>'FL','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'111'),
			array('typeScale'=>'FL','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'107'),
			array('typeScale'=>'FL','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'103'),
			array('typeScale'=>'FL','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'98' ),
			array('typeScale'=>'FL','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'96' ),
			array('typeScale'=>'FL','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'91' ),
			array('typeScale'=>'FL','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'88' ),
			array('typeScale'=>'FL','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'85' ),
			array('typeScale'=>'FL','pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'82' ),
			array('typeScale'=>'FL','pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'79' ),
			array('typeScale'=>'FL','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'75' ),
			array('typeScale'=>'FL','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'73' ),
			array('typeScale'=>'FL','pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'71' ),
			array('typeScale'=>'FL','pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'68' ),
			array('typeScale'=>'FL','pdMin'=>'0',  'pdMax'=>'17', 'ce'=>'65' ),
			array('typeScale'=>'TT','pdMin'=>'44', 'pdMax'=>'45', 'ce'=>'130' ),
			array('typeScale'=>'TT','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'126' ),
			array('typeScale'=>'TT','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'121' ),
			array('typeScale'=>'TT','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'117' ),
			array('typeScale'=>'TT','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'114' ),
			array('typeScale'=>'TT','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'110' ),
			array('typeScale'=>'TT','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'106' ),
			array('typeScale'=>'TT','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'103' ),
			array('typeScale'=>'TT','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'100' ),
			array('typeScale'=>'TT','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'97'  ),
			array('typeScale'=>'TT','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'94'  ),
			array('typeScale'=>'TT','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'93'  ),
			array('typeScale'=>'TT','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'90'  ),
			array('typeScale'=>'TT','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'86'  ),
			array('typeScale'=>'TT','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'83'  ),
			array('typeScale'=>'TT','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'80'  ),
			array('typeScale'=>'TT','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'79'  ),
			array('typeScale'=>'TT','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'77'  ),
			array('typeScale'=>'TT','pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'75'  ),
			array('typeScale'=>'TT','pdMin'=>'23', 'pdMax'=>'25', 'ce'=>'73'  ),
			array('typeScale'=>'TT','pdMin'=>'20', 'pdMax'=>'22', 'ce'=>'71'  ),
			array('typeScale'=>'TT','pdMin'=>'16', 'pdMax'=>'19', 'ce'=>'68'  ),
			array('typeScale'=>'TT','pdMin'=>'0',  'pdMax'=>'15', 'ce'=>'65'  ),
			array('typeScale'=>'CI','pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'130' ),
			array('typeScale'=>'CI','pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'121' ),
			array('typeScale'=>'CI','pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'115' ),
			array('typeScale'=>'CI','pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'110' ),
			array('typeScale'=>'CI','pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'106' ),
			array('typeScale'=>'CI','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'102' ),
			array('typeScale'=>'CI','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'100' ),
			array('typeScale'=>'CI','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'97'  ),
			array('typeScale'=>'CI','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'95'  ),
			array('typeScale'=>'CI','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'92'  ),
			array('typeScale'=>'CI','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'90'  ),
			array('typeScale'=>'CI','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'88'  ),
			array('typeScale'=>'CI','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'85'  ),
			array('typeScale'=>'CI','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'82'  ),
			array('typeScale'=>'CI','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'80'  ),
			array('typeScale'=>'CI','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'79'  ),
			array('typeScale'=>'CI','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'78'  ),
			array('typeScale'=>'CI','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'75'  ),
			array('typeScale'=>'CI','pdMin'=>'26', 'pdMax'=>'27', 'ce'=>'73'  ),
			array('typeScale'=>'CI','pdMin'=>'23', 'pdMax'=>'25', 'ce'=>'71'  ),
			array('typeScale'=>'CI','pdMin'=>'20', 'pdMax'=>'22', 'ce'=>'68'  ),
			array('typeScale'=>'CI','pdMin'=>'0',  'pdMax'=>'19', 'ce'=>'65'  ),
			array('typeScale'=>'FE','pdMin'=>'41', 'pdMax'=>'45', 'ce'=>'130'),
			array('typeScale'=>'FE','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'123'),
			array('typeScale'=>'FE','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'117'),
			array('typeScale'=>'FE','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'113'),
			array('typeScale'=>'FE','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'108'),
			array('typeScale'=>'FE','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'104'),
			array('typeScale'=>'FE','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'100'),
			array('typeScale'=>'FE','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'94' ),
			array('typeScale'=>'FE','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'92' ),
			array('typeScale'=>'FE','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'89' ),
			array('typeScale'=>'FE','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'85' ),
			array('typeScale'=>'FE','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'82' ),
			array('typeScale'=>'FE','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'79' ),
			array('typeScale'=>'FE','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'78' ),
			array('typeScale'=>'FE','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'75' ),
			array('typeScale'=>'FE','pdMin'=>'25', 'pdMax'=>'26', 'ce'=>'73' ),
			array('typeScale'=>'FE','pdMin'=>'23', 'pdMax'=>'24', 'ce'=>'71' ),
			array('typeScale'=>'FE','pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'68' ),
			array('typeScale'=>'FE','pdMin'=>'0',  'pdMax'=>'21', 'ce'=>'65' ),
			array('typeScale'=>'OP','pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'123'),
			array('typeScale'=>'OP','pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'118'),
			array('typeScale'=>'OP','pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'114'),
			array('typeScale'=>'OP','pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'109'),
			array('typeScale'=>'OP','pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'105'),
			array('typeScale'=>'OP','pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'101'),
			array('typeScale'=>'OP','pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'97' ),
			array('typeScale'=>'OP','pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'93' ),
			array('typeScale'=>'OP','pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'89' ),
			array('typeScale'=>'OP','pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'86' ),
			array('typeScale'=>'OP','pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'82' ),
			array('typeScale'=>'OP','pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'81' ),
			array('typeScale'=>'OP','pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'78' ),
			array('typeScale'=>'OP','pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'77' ),
			array('typeScale'=>'OP','pdMin'=>'24', 'pdMax'=>'26', 'ce'=>'73' ),
			array('typeScale'=>'OP','pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'71' ),
			array('typeScale'=>'OP','pdMin'=>'19', 'pdMax'=>'22', 'ce'=>'68' ),
			array('typeScale'=>'OP','pdMin'=>'0', 'pdMax'=>'18', 'ce'=>'65'  ),
			array('typeScale'=>'CERA','pdMin'=>'189', 'pdMax'=>'200', 'ce'=>'133' ),
			array('typeScale'=>'CERA','pdMin'=>'188', 'pdMax'=>'188', 'ce'=>'130' ),
			array('typeScale'=>'CERA','pdMin'=>'186', 'pdMax'=>'187', 'ce'=>'128' ),
			array('typeScale'=>'CERA','pdMin'=>'185', 'pdMax'=>'185', 'ce'=>'126' ),
			array('typeScale'=>'CERA','pdMin'=>'184', 'pdMax'=>'184', 'ce'=>'123' ),
			array('typeScale'=>'CERA','pdMin'=>'183', 'pdMax'=>'183', 'ce'=>'122' ),
			array('typeScale'=>'CERA','pdMin'=>'182', 'pdMax'=>'182', 'ce'=>'120' ),
			array('typeScale'=>'CERA','pdMin'=>'181', 'pdMax'=>'181', 'ce'=>'119' ),
			array('typeScale'=>'CERA','pdMin'=>'180', 'pdMax'=>'180', 'ce'=>'117' ),
			array('typeScale'=>'CERA','pdMin'=>'179', 'pdMax'=>'179', 'ce'=>'116' ),
			array('typeScale'=>'CERA','pdMin'=>'178', 'pdMax'=>'178', 'ce'=>'114' ),
			array('typeScale'=>'CERA','pdMin'=>'177', 'pdMax'=>'177', 'ce'=>'113' ),
			array('typeScale'=>'CERA','pdMin'=>'176', 'pdMax'=>'176', 'ce'=>'111' ),
			array('typeScale'=>'CERA','pdMin'=>'175', 'pdMax'=>'175', 'ce'=>'110' ),
			array('typeScale'=>'CERA','pdMin'=>'173', 'pdMax'=>'174', 'ce'=>'109' ),
			array('typeScale'=>'CERA','pdMin'=>'172', 'pdMax'=>'172', 'ce'=>'107' ),
			array('typeScale'=>'CERA','pdMin'=>'170', 'pdMax'=>'171', 'ce'=>'106' ),
			array('typeScale'=>'CERA','pdMin'=>'169', 'pdMax'=>'169', 'ce'=>'104' ),
			array('typeScale'=>'CERA','pdMin'=>'168', 'pdMax'=>'168', 'ce'=>'103' ),
			array('typeScale'=>'CERA','pdMin'=>'167', 'pdMax'=>'167', 'ce'=>'101' ),
			array('typeScale'=>'CERA','pdMin'=>'165', 'pdMax'=>'166', 'ce'=>'100' ),
			array('typeScale'=>'CERA','pdMin'=>'164', 'pdMax'=>'164', 'ce'=>'99'  ),
			array('typeScale'=>'CERA','pdMin'=>'163', 'pdMax'=>'163', 'ce'=>'98'  ),
			array('typeScale'=>'CERA','pdMin'=>'162', 'pdMax'=>'162', 'ce'=>'97'  ),
			array('typeScale'=>'CERA','pdMin'=>'160', 'pdMax'=>'161', 'ce'=>'96'  ),
			array('typeScale'=>'CERA','pdMin'=>'159', 'pdMax'=>'159', 'ce'=>'95'  ),
			array('typeScale'=>'CERA','pdMin'=>'158', 'pdMax'=>'158', 'ce'=>'94'  ),
			array('typeScale'=>'CERA','pdMin'=>'157', 'pdMax'=>'157', 'ce'=>'93'  ),
			array('typeScale'=>'CERA','pdMin'=>'155', 'pdMax'=>'156', 'ce'=>'92'  ),
			array('typeScale'=>'CERA','pdMin'=>'154', 'pdMax'=>'154', 'ce'=>'91'  ),
			array('typeScale'=>'CERA','pdMin'=>'153', 'pdMax'=>'153', 'ce'=>'90'  ),
			array('typeScale'=>'CERA','pdMin'=>'152', 'pdMax'=>'152', 'ce'=>'89'  ),
			array('typeScale'=>'CERA','pdMin'=>'152', 'pdMax'=>'152', 'ce'=>'88'  ),
			array('typeScale'=>'CERA','pdMin'=>'150', 'pdMax'=>'150', 'ce'=>'87'  ),
			array('typeScale'=>'CERA','pdMin'=>'148', 'pdMax'=>'149', 'ce'=>'86'  ),
			array('typeScale'=>'CERA','pdMin'=>'147', 'pdMax'=>'147', 'ce'=>'85'  ),
			array('typeScale'=>'CERA','pdMin'=>'146', 'pdMax'=>'146', 'ce'=>'84'  ),
			array('typeScale'=>'CERA','pdMin'=>'145', 'pdMax'=>'145', 'ce'=>'83'  ),
			array('typeScale'=>'CERA','pdMin'=>'142', 'pdMax'=>'144', 'ce'=>'82'  ),
			array('typeScale'=>'CERA','pdMin'=>'140', 'pdMax'=>'141', 'ce'=>'81'  ),
			array('typeScale'=>'CERA','pdMin'=>'136', 'pdMax'=>'139', 'ce'=>'80'  ),
			array('typeScale'=>'CERA','pdMin'=>'135', 'pdMax'=>'135', 'ce'=>'78'  ),
			array('typeScale'=>'CERA','pdMin'=>'132', 'pdMax'=>'134', 'ce'=>'77'  ),
			array('typeScale'=>'CERA','pdMin'=>'129', 'pdMax'=>'131', 'ce'=>'75'  ),
			array('typeScale'=>'CERA','pdMin'=>'126', 'pdMax'=>'128', 'ce'=>'73'  ),
			array('typeScale'=>'CERA','pdMin'=>'123', 'pdMax'=>'125', 'ce'=>'71'  ),
			array('typeScale'=>'CERA','pdMin'=>'111', 'pdMax'=>'122', 'ce'=>'68'  ),
			array('typeScale'=>'CERA','pdMin'=>'40',  'pdMax'=>'110', 'ce'=>'65'  ),
			array('typeScale'=>'CEER','pdMin'=>'115', 'pdMax'=>'120', 'ce'=>'133'),
			array('typeScale'=>'CEER','pdMin'=>'113', 'pdMax'=>'114', 'ce'=>'130'),
			array('typeScale'=>'CEER','pdMin'=>'112', 'pdMax'=>'112', 'ce'=>'128'),
			array('typeScale'=>'CEER','pdMin'=>'111', 'pdMax'=>'111', 'ce'=>'126'),
			array('typeScale'=>'CEER','pdMin'=>'110', 'pdMax'=>'110', 'ce'=>'124'),
			array('typeScale'=>'CEER','pdMin'=>'109', 'pdMax'=>'109', 'ce'=>'123'),
			array('typeScale'=>'CEER','pdMin'=>'108', 'pdMax'=>'108', 'ce'=>'121'),
			array('typeScale'=>'CEER','pdMin'=>'107', 'pdMax'=>'107', 'ce'=>'118'),
			array('typeScale'=>'CEER','pdMin'=>'106', 'pdMax'=>'106', 'ce'=>'116'),
			array('typeScale'=>'CEER','pdMin'=>'105', 'pdMax'=>'105', 'ce'=>'115'),
			array('typeScale'=>'CEER','pdMin'=>'104', 'pdMax'=>'104', 'ce'=>'113'),
			array('typeScale'=>'CEER','pdMin'=>'103', 'pdMax'=>'103', 'ce'=>'111'),
			array('typeScale'=>'CEER','pdMin'=>'102', 'pdMax'=>'102', 'ce'=>'109'),
			array('typeScale'=>'CEER','pdMin'=>'101', 'pdMax'=>'101', 'ce'=>'107'),
			array('typeScale'=>'CEER','pdMin'=>'100', 'pdMax'=>'100', 'ce'=>'105'),
			array('typeScale'=>'CEER','pdMin'=>'99', 'pdMax'=>'99', 'ce'=>'104'),
			array('typeScale'=>'CEER','pdMin'=>'98', 'pdMax'=>'98', 'ce'=>'101'),
			array('typeScale'=>'CEER','pdMin'=>'97', 'pdMax'=>'97', 'ce'=>'100'),
			array('typeScale'=>'CEER','pdMin'=>'96', 'pdMax'=>'96', 'ce'=>'98'),
			array('typeScale'=>'CEER','pdMin'=>'95', 'pdMax'=>'95', 'ce'=>'97'),
			array('typeScale'=>'CEER','pdMin'=>'94', 'pdMax'=>'94', 'ce'=>'96'),
			array('typeScale'=>'CEER','pdMin'=>'93', 'pdMax'=>'93', 'ce'=>'94'),
			array('typeScale'=>'CEER','pdMin'=>'92', 'pdMax'=>'92', 'ce'=>'93'),
			array('typeScale'=>'CEER','pdMin'=>'91', 'pdMax'=>'91', 'ce'=>'92'),
			array('typeScale'=>'CEER','pdMin'=>'90', 'pdMax'=>'90', 'ce'=>'91'),
			array('typeScale'=>'CEER','pdMin'=>'89', 'pdMax'=>'89', 'ce'=>'88'),
			array('typeScale'=>'CEER','pdMin'=>'88', 'pdMax'=>'88', 'ce'=>'86'),
			array('typeScale'=>'CEER','pdMin'=>'87', 'pdMax'=>'87', 'ce'=>'85'),
			array('typeScale'=>'CEER','pdMin'=>'86', 'pdMax'=>'86', 'ce'=>'84'),
			array('typeScale'=>'CEER','pdMin'=>'85', 'pdMax'=>'85', 'ce'=>'82'),
			array('typeScale'=>'CEER','pdMin'=>'84', 'pdMax'=>'84', 'ce'=>'81'),
			array('typeScale'=>'CEER','pdMin'=>'83', 'pdMax'=>'83', 'ce'=>'80'),
			array('typeScale'=>'CEER','pdMin'=>'82', 'pdMax'=>'82', 'ce'=>'79'),
			array('typeScale'=>'CEER','pdMin'=>'81', 'pdMax'=>'81', 'ce'=>'78'),
			array('typeScale'=>'CEER','pdMin'=>'80', 'pdMax'=>'80', 'ce'=>'77'),
			array('typeScale'=>'CEER','pdMin'=>'78', 'pdMax'=>'79', 'ce'=>'75'),
			array('typeScale'=>'CEER','pdMin'=>'76', 'pdMax'=>'77', 'ce'=>'73'),
			array('typeScale'=>'CEER','pdMin'=>'75', 'pdMax'=>'75', 'ce'=>'71'),
			array('typeScale'=>'CEER','pdMin'=>'71', 'pdMax'=>'74', 'ce'=>'68'),
			array('typeScale'=>'CEER','pdMin'=>'24', 'pdMax'=>'70', 'ce'=>'65'),
			array('typeScale'=>'CEAD','pdMin'=>'125', 'pdMax'=>'130', 'ce'=>'133'),
			array('typeScale'=>'CEAD','pdMin'=>'123', 'pdMax'=>'124', 'ce'=>'130'),
			array('typeScale'=>'CEAD','pdMin'=>'122', 'pdMax'=>'122', 'ce'=>'126'),
			array('typeScale'=>'CEAD','pdMin'=>'121', 'pdMax'=>'121', 'ce'=>'124'),
			array('typeScale'=>'CEAD','pdMin'=>'119', 'pdMax'=>'120', 'ce'=>'122'),
			array('typeScale'=>'CEAD','pdMin'=>'118', 'pdMax'=>'118', 'ce'=>'119'),
			array('typeScale'=>'CEAD','pdMin'=>'117', 'pdMax'=>'117', 'ce'=>'117'),
			array('typeScale'=>'CEAD','pdMin'=>'116', 'pdMax'=>'116', 'ce'=>'116'),
			array('typeScale'=>'CEAD','pdMin'=>'115', 'pdMax'=>'115', 'ce'=>'115'),
			array('typeScale'=>'CEAD','pdMin'=>'114', 'pdMax'=>'114', 'ce'=>'112'),
			array('typeScale'=>'CEAD','pdMin'=>'113', 'pdMax'=>'113', 'ce'=>'110'),
			array('typeScale'=>'CEAD','pdMin'=>'112', 'pdMax'=>'112', 'ce'=>'109'),
			array('typeScale'=>'CEAD','pdMin'=>'111', 'pdMax'=>'111', 'ce'=>'107'),
			array('typeScale'=>'CEAD','pdMin'=>'110', 'pdMax'=>'110', 'ce'=>'105'),
			array('typeScale'=>'CEAD','pdMin'=>'109', 'pdMax'=>'109', 'ce'=>'104'),
			array('typeScale'=>'CEAD','pdMin'=>'108', 'pdMax'=>'108', 'ce'=>'103'),
			array('typeScale'=>'CEAD','pdMin'=>'107', 'pdMax'=>'107', 'ce'=>'102'),
			array('typeScale'=>'CEAD','pdMin'=>'106', 'pdMax'=>'106', 'ce'=>'101'),
			array('typeScale'=>'CEAD','pdMin'=>'105', 'pdMax'=>'105', 'ce'=>'99' ),
			array('typeScale'=>'CEAD','pdMin'=>'104', 'pdMax'=>'104', 'ce'=>'97' ),
			array('typeScale'=>'CEAD','pdMin'=>'102', 'pdMax'=>'103', 'ce'=>'96' ),
			array('typeScale'=>'CEAD','pdMin'=>'101', 'pdMax'=>'101', 'ce'=>'94' ),
			array('typeScale'=>'CEAD','pdMin'=>'100', 'pdMax'=>'100', 'ce'=>'93' ),
			array('typeScale'=>'CEAD','pdMin'=>'99',	'pdMax'=>'99',	'ce'=>'92' ),  
			array('typeScale'=>'CEAD','pdMin'=>'98',	'pdMax'=>'98',	'ce'=>'90' ),  
			array('typeScale'=>'CEAD','pdMin'=>'97',	'pdMax'=>'97',	'ce'=>'88' ),  
			array('typeScale'=>'CEAD','pdMin'=>'96',	'pdMax'=>'96',	'ce'=>'86' ),  
			array('typeScale'=>'CEAD','pdMin'=>'95',	'pdMax'=>'95',	'ce'=>'85' ),  
			array('typeScale'=>'CEAD','pdMin'=>'93',	'pdMax'=>'94',	'ce'=>'84' ),  
			array('typeScale'=>'CEAD','pdMin'=>'91',	'pdMax'=>'92',	'ce'=>'82' ),  
			array('typeScale'=>'CEAD','pdMin'=>'90',	'pdMax'=>'90',	'ce'=>'81' ),  
			array('typeScale'=>'CEAD','pdMin'=>'89',	'pdMax'=>'89',	'ce'=>'79' ),  
			array('typeScale'=>'CEAD','pdMin'=>'87',	'pdMax'=>'88',	'ce'=>'78' ),  
			array('typeScale'=>'CEAD','pdMin'=>'86',	'pdMax'=>'86',	'ce'=>'77' ),  
			array('typeScale'=>'CEAD','pdMin'=>'84',	'pdMax'=>'85',	'ce'=>'75' ),  
			array('typeScale'=>'CEAD','pdMin'=>'77',	'pdMax'=>'83',	'ce'=>'73' ),  
			array('typeScale'=>'CEAD','pdMin'=>'74',	'pdMax'=>'76',	'ce'=>'71' ),  
			array('typeScale'=>'CEAD','pdMin'=>'70',	'pdMax'=>'73',	'ce'=>'68' ),  
			array('typeScale'=>'CEAD','pdMin'=>'26',	'pdMax'=>'69',	'ce'=>'65' ),                                                                       
			array('typeScale'=>'CEMT','pdMin'=>'88', 'pdMax'=>'90', 'ce'=>'130'),                                                                     
			array('typeScale'=>'CEMT','pdMin'=>'87', 'pdMax'=>'87', 'ce'=>'126'),                                                                     
			array('typeScale'=>'CEMT','pdMin'=>'86', 'pdMax'=>'86', 'ce'=>'124'),                                                                     
			array('typeScale'=>'CEMT','pdMin'=>'85', 'pdMax'=>'85', 'ce'=>'123'),
			array('typeScale'=>'CEMT','pdMin'=>'84', 'pdMax'=>'84', 'ce'=>'120'),
			array('typeScale'=>'CEMT','pdMin'=>'83', 'pdMax'=>'83', 'ce'=>'118'),
			array('typeScale'=>'CEMT','pdMin'=>'82', 'pdMax'=>'82', 'ce'=>'116'),
			array('typeScale'=>'CEMT','pdMin'=>'81', 'pdMax'=>'81', 'ce'=>'114'),
			array('typeScale'=>'CEMT','pdMin'=>'80', 'pdMax'=>'80', 'ce'=>'112'),
			array('typeScale'=>'CEMT','pdMin'=>'79', 'pdMax'=>'79', 'ce'=>'110'),
			array('typeScale'=>'CEMT','pdMin'=>'78', 'pdMax'=>'78', 'ce'=>'108'),
			array('typeScale'=>'CEMT','pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'106'),
			array('typeScale'=>'CEMT','pdMin'=>'76', 'pdMax'=>'76', 'ce'=>'103'),
			array('typeScale'=>'CEMT','pdMin'=>'75', 'pdMax'=>'75', 'ce'=>'101'),
			array('typeScale'=>'CEMT','pdMin'=>'74', 'pdMax'=>'74', 'ce'=>'99' ),
			array('typeScale'=>'CEMT','pdMin'=>'72', 'pdMax'=>'73', 'ce'=>'96' ),
			array('typeScale'=>'CEMT','pdMin'=>'71', 'pdMax'=>'71', 'ce'=>'94' ),
			array('typeScale'=>'CEMT','pdMin'=>'70', 'pdMax'=>'70', 'ce'=>'93' ),
			array('typeScale'=>'CEMT','pdMin'=>'69', 'pdMax'=>'69', 'ce'=>'91' ),
			array('typeScale'=>'CEMT','pdMin'=>'68', 'pdMax'=>'68', 'ce'=>'89' ),
			array('typeScale'=>'CEMT','pdMin'=>'67', 'pdMax'=>'67', 'ce'=>'88' ),
			array('typeScale'=>'CEMT','pdMin'=>'66', 'pdMax'=>'66', 'ce'=>'86' ),
			array('typeScale'=>'CEMT','pdMin'=>'65', 'pdMax'=>'65', 'ce'=>'85' ),
			array('typeScale'=>'CEMT','pdMin'=>'64', 'pdMax'=>'64', 'ce'=>'84' ),
			array('typeScale'=>'CEMT','pdMin'=>'63', 'pdMax'=>'63', 'ce'=>'83' ),
			array('typeScale'=>'CEMT','pdMin'=>'62', 'pdMax'=>'62', 'ce'=>'82' ),
			array('typeScale'=>'CEMT','pdMin'=>'61', 'pdMax'=>'61', 'ce'=>'81' ),
			array('typeScale'=>'CEMT','pdMin'=>'60', 'pdMax'=>'60', 'ce'=>'80' ),
			array('typeScale'=>'CEMT','pdMin'=>'58', 'pdMax'=>'59', 'ce'=>'79' ),
			array('typeScale'=>'CEMT','pdMin'=>'55', 'pdMax'=>'57', 'ce'=>'77' ),
			array('typeScale'=>'CEMT','pdMin'=>'54', 'pdMax'=>'54', 'ce'=>'75' ),
			array('typeScale'=>'CEMT','pdMin'=>'50', 'pdMax'=>'53', 'ce'=>'73' ),
			array('typeScale'=>'CEMT','pdMin'=>'45', 'pdMax'=>'49', 'ce'=>'71' ),
			array('typeScale'=>'CEMT','pdMin'=>'36', 'pdMax'=>'44', 'ce'=>'68' ),
			array('typeScale'=>'CEMT','pdMin'=>'18', 'pdMax'=>'35', 'ce'=>'65' ),
			array('typeScale'=>'CEAG','pdMin'=>'79', 'pdMax'=>'85', 'ce'=>'130'),
			array('typeScale'=>'CEAG','pdMin'=>'78', 'pdMax'=>'78', 'ce'=>'126'),
			array('typeScale'=>'CEAG','pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'122'),
			array('typeScale'=>'CEAG','pdMin'=>'76', 'pdMax'=>'76', 'ce'=>'117'),
			array('typeScale'=>'CEAG','pdMin'=>'75', 'pdMax'=>'75', 'ce'=>'114'),
			array('typeScale'=>'CEAG','pdMin'=>'74', 'pdMax'=>'74', 'ce'=>'112'),
			array('typeScale'=>'CEAG','pdMin'=>'73', 'pdMax'=>'73', 'ce'=>'109'),
			array('typeScale'=>'CEAG','pdMin'=>'72', 'pdMax'=>'72', 'ce'=>'106'),
			array('typeScale'=>'CEAG','pdMin'=>'71', 'pdMax'=>'71', 'ce'=>'103'),
			array('typeScale'=>'CEAG','pdMin'=>'70', 'pdMax'=>'70', 'ce'=>'101'),
			array('typeScale'=>'CEAG','pdMin'=>'69', 'pdMax'=>'69', 'ce'=>'99' ),
			array('typeScale'=>'CEAG','pdMin'=>'68', 'pdMax'=>'68', 'ce'=>'96' ),
			array('typeScale'=>'CEAG','pdMin'=>'67', 'pdMax'=>'67', 'ce'=>'94' ),
			array('typeScale'=>'CEAG','pdMin'=>'66', 'pdMax'=>'66', 'ce'=>'92' ),
			array('typeScale'=>'CEAG','pdMin'=>'65', 'pdMax'=>'65', 'ce'=>'90' ),
			array('typeScale'=>'CEAG','pdMin'=>'64', 'pdMax'=>'64', 'ce'=>'88' ),
			array('typeScale'=>'CEAG','pdMin'=>'63', 'pdMax'=>'63', 'ce'=>'87' ),
			array('typeScale'=>'CEAG','pdMin'=>'62', 'pdMax'=>'62', 'ce'=>'84' ),
			array('typeScale'=>'CEAG','pdMin'=>'61', 'pdMax'=>'61', 'ce'=>'83' ),
			array('typeScale'=>'CEAG','pdMin'=>'59', 'pdMax'=>'60', 'ce'=>'82' ),
			array('typeScale'=>'CEAG','pdMin'=>'58', 'pdMax'=>'58', 'ce'=>'80' ),
			array('typeScale'=>'CEAG','pdMin'=>'57', 'pdMax'=>'57', 'ce'=>'79' ),
			array('typeScale'=>'CEAG','pdMin'=>'56', 'pdMax'=>'56', 'ce'=>'78' ),
			array('typeScale'=>'CEAG','pdMin'=>'54', 'pdMax'=>'55', 'ce'=>'77' ),
			array('typeScale'=>'CEAG','pdMin'=>'52', 'pdMax'=>'53', 'ce'=>'75' ),
			array('typeScale'=>'CEAG','pdMin'=>'51', 'pdMax'=>'51', 'ce'=>'73' ),
			array('typeScale'=>'CEAG','pdMin'=>'49', 'pdMax'=>'50', 'ce'=>'71' ),
			array('typeScale'=>'CEAG','pdMin'=>'45', 'pdMax'=>'48', 'ce'=>'68' ),
			array('typeScale'=>'CEAG','pdMin'=>'17', 'pdMax'=>'44', 'ce'=>'65' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'546', 'pdMax'=>'585', 'ce'=>'133' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'542', 'pdMax'=>'545', 'ce'=>'130' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'533', 'pdMax'=>'541', 'ce'=>'128' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'536', 'pdMax'=>'537', 'ce'=>'126' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'534', 'pdMax'=>'535', 'ce'=>'124' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'530', 'pdMax'=>'533', 'ce'=>'123' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'526', 'pdMax'=>'529', 'ce'=>'122' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'525', 'pdMax'=>'525', 'ce'=>'121' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'524', 'pdMax'=>'524', 'ce'=>'120' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'522', 'pdMax'=>'523', 'ce'=>'119' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'517', 'pdMax'=>'521', 'ce'=>'118' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'516', 'pdMax'=>'516', 'ce'=>'117' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'512', 'pdMax'=>'515', 'ce'=>'116' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'508', 'pdMax'=>'511', 'ce'=>'115' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'507', 'pdMax'=>'507', 'ce'=>'114' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'506', 'pdMax'=>'506', 'ce'=>'113' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'504', 'pdMax'=>'505', 'ce'=>'112' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'502', 'pdMax'=>'503', 'ce'=>'111' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'501', 'pdMax'=>'501', 'ce'=>'110' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'498', 'pdMax'=>'500', 'ce'=>'109' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'495', 'pdMax'=>'497', 'ce'=>'108' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'493', 'pdMax'=>'494', 'ce'=>'107' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'491', 'pdMax'=>'492', 'ce'=>'106' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'490', 'pdMax'=>'490', 'ce'=>'105' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'487', 'pdMax'=>'489', 'ce'=>'104' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'485', 'pdMax'=>'486', 'ce'=>'103' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'482', 'pdMax'=>'484', 'ce'=>'102' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'479', 'pdMax'=>'481', 'ce'=>'101' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'476', 'pdMax'=>'478', 'ce'=>'100' ),
			array('typeScale'=>'CETOTAL','pdMin'=>'473', 'pdMax'=>'475', 'ce'=>'99'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'470', 'pdMax'=>'472', 'ce'=>'98'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'466', 'pdMax'=>'469', 'ce'=>'96'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'465', 'pdMax'=>'465', 'ce'=>'95'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'460', 'pdMax'=>'464', 'ce'=>'94'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'457', 'pdMax'=>'459', 'ce'=>'93'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'453', 'pdMax'=>'456', 'ce'=>'92'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'450', 'pdMax'=>'452', 'ce'=>'91'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'448', 'pdMax'=>'449', 'ce'=>'90'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'441', 'pdMax'=>'447', 'ce'=>'89'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'438', 'pdMax'=>'440', 'ce'=>'88'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'436', 'pdMax'=>'437', 'ce'=>'87'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'432', 'pdMax'=>'435', 'ce'=>'86'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'429', 'pdMax'=>'431', 'ce'=>'85'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'428', 'pdMax'=>'428', 'ce'=>'84'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'427', 'pdMax'=>'427', 'ce'=>'83'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'420', 'pdMax'=>'426', 'ce'=>'82'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'418', 'pdMax'=>'419', 'ce'=>'81'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'409', 'pdMax'=>'417', 'ce'=>'80'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'405', 'pdMax'=>'408', 'ce'=>'79'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'401', 'pdMax'=>'404', 'ce'=>'78'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'391', 'pdMax'=>'400', 'ce'=>'77'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'383', 'pdMax'=>'390', 'ce'=>'75'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'367', 'pdMax'=>'382', 'ce'=>'73'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'346', 'pdMax'=>'366', 'ce'=>'71'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'322', 'pdMax'=>'345', 'ce'=>'68'  ),
			array('typeScale'=>'CETOTAL','pdMin'=>'117', 'pdMax'=>'321', 'ce'=>'65'  ),			
		);
         
        foreach ($lstStructure as $lst) {

            $objeto = new ICEM2130Baremo();
            $objeto->setTypeScale($lst['typeScale']);
            $objeto->setPdMin($lst['pdMin']);
            $objeto->setPdMax($lst['pdMax']);
            $objeto->setCE($lst['ce']);
            
            $manager->persist($objeto);                              
        }

        $manager->flush();    
	}
}
