<?php

namespace Jaxxes\TestICEBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture; 
use Symfony\Component\DependencyInjection\ContainerAwareInterface;

use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerInterface;

use Jaxxes\TestICEBundle\Entity\ICEM1620Baremo;

/**
 * Fixtures de la entidad Resume.
 * Crea el registro de la cabecera para Resume = Ficha del candidato
 */
 
// class Resumes implements FixtureInterface
 class ICEM1620Baremos extends AbstractFixture implements OrderedFixtureInterface
{
	
    public function getOrder()
    {
        return 4;
    }
    private $container;
    
    
    
    public function load(ObjectManager $manager)
    {
        $lstStructure = array(	
			array('typeScale'=>'IMP', 'pdMin'=>'0', 'pdMax'=>'15', 'ce'=>'65'),
			array('typeScale'=>'IMP', 'pdMin'=>'16', 'pdMax'=>'17', 'ce'=>'68'),
			array('typeScale'=>'IMP', 'pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'77'),
			array('typeScale'=>'IMP', 'pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'84'),
			array('typeScale'=>'IMP', 'pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'86'),
			array('typeScale'=>'IMP', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'90'),
			array('typeScale'=>'IMP', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'92'),
			array('typeScale'=>'IMP', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'96'),
			array('typeScale'=>'IMP', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'101'),
			array('typeScale'=>'IMP', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'104'),
			array('typeScale'=>'IMP', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'106'),
			array('typeScale'=>'IMP', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'111'),
			array('typeScale'=>'IMP', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'115'),
			array('typeScale'=>'IMP', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'117'),
			array('typeScale'=>'IMP', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'120'),
			array('typeScale'=>'IMP', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'122'),
			array('typeScale'=>'IMP', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'124'),
			array('typeScale'=>'IMP', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'126'),
			array('typeScale'=>'IMP', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'128'),
			array('typeScale'=>'IMP', 'pdMin'=>'35', 'pdMax'=>'40', 'ce'=>'130'),			
			array('typeScale'=>'IMN', 'pdMin'=>'0', 'pdMax'=>'7', 'ce'=>'65'),
			array('typeScale'=>'IMN', 'pdMin'=>'8', 'pdMax'=>'8', 'ce'=>'81'),
			array('typeScale'=>'IMN', 'pdMin'=>'9', 'pdMax'=>'9', 'ce'=>'91'),
			array('typeScale'=>'IMN', 'pdMin'=>'10', 'pdMax'=>'10', 'ce'=>'97'),
			array('typeScale'=>'IMN', 'pdMin'=>'11', 'pdMax'=>'11', 'ce'=>'100'),
			array('typeScale'=>'IMN', 'pdMin'=>'12', 'pdMax'=>'12', 'ce'=>'102'),
			array('typeScale'=>'IMN', 'pdMin'=>'13', 'pdMax'=>'13', 'ce'=>'107'),
			array('typeScale'=>'IMN', 'pdMin'=>'14', 'pdMax'=>'14', 'ce'=>'108'),
			array('typeScale'=>'IMN', 'pdMin'=>'15', 'pdMax'=>'15', 'ce'=>'111'),
			array('typeScale'=>'IMN', 'pdMin'=>'16', 'pdMax'=>'16', 'ce'=>'114'),
			array('typeScale'=>'IMN', 'pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'116'),
			array('typeScale'=>'IMN', 'pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'118'),
			array('typeScale'=>'IMN', 'pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'122'),
			array('typeScale'=>'IMN', 'pdMin'=>'20', 'pdMax'=>'21', 'ce'=>'123'),
			array('typeScale'=>'IMN', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'124'),
			array('typeScale'=>'IMN', 'pdMin'=>'23', 'pdMax'=>'25', 'ce'=>'128'),
			array('typeScale'=>'IMN', 'pdMin'=>'26', 'pdMax'=>'27', 'ce'=>'130'),
			array('typeScale'=>'IMN', 'pdMin'=>'28', 'pdMax'=>'35', 'ce'=>'133'),		
			array('typeScale'=>'CM', 'pdMin'=>'0', 'pdMax'=>'17', 'ce'=>'65'),
			array('typeScale'=>'CM', 'pdMin'=>'18', 'pdMax'=>'20', 'ce'=>'68'),
			array('typeScale'=>'CM', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'73'),
			array('typeScale'=>'CM', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'78'),
			array('typeScale'=>'CM', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'79'),
			array('typeScale'=>'CM', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'81'),
			array('typeScale'=>'CM', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'83'),
			array('typeScale'=>'CM', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'88'),
			array('typeScale'=>'CM', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'92'),
			array('typeScale'=>'CM', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'96'),
			array('typeScale'=>'CM', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'99'),
			array('typeScale'=>'CM', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'101'),
			array('typeScale'=>'CM', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'103'),
			array('typeScale'=>'CM', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'107'),
			array('typeScale'=>'CM', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'111'),
			array('typeScale'=>'CM', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'115'),
			array('typeScale'=>'CM', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'119'),
			array('typeScale'=>'CM', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'123'),
			array('typeScale'=>'CM', 'pdMin'=>'37', 'pdMax'=>'40', 'ce'=>'133'),
			array('typeScale'=>'SE', 'pdMin'=>'0', 'pdMax'=>'14', 'ce'=>'65'),
			array('typeScale'=>'SE', 'pdMin'=>'15', 'pdMax'=>'17', 'ce'=>'68'),
			array('typeScale'=>'SE', 'pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'71'),
			array('typeScale'=>'SE', 'pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'73'),
			array('typeScale'=>'SE', 'pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'77'),
			array('typeScale'=>'SE', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'81'),
			array('typeScale'=>'SE', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'84'),
			array('typeScale'=>'SE', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'85'),
			array('typeScale'=>'SE', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'89'),
			array('typeScale'=>'SE', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'91'),
			array('typeScale'=>'SE', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'94'),
			array('typeScale'=>'SE', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'98'),
			array('typeScale'=>'SE', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'102'),
			array('typeScale'=>'SE', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'106'),
			array('typeScale'=>'SE', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'109'),
			array('typeScale'=>'SE', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'112'),
			array('typeScale'=>'SE', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'118'),
			array('typeScale'=>'SE', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'124'),
			array('typeScale'=>'SE', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'130'),
			array('typeScale'=>'SE', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'133'),
			array('typeScale'=>'AE', 'pdMin'=>'0', 'pdMax'=>'12', 'ce'=>'65'),
			array('typeScale'=>'AE', 'pdMin'=>'13', 'pdMax'=>'23', 'ce'=>'68'),
			array('typeScale'=>'AE', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'71'),
			array('typeScale'=>'AE', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'73'),
			array('typeScale'=>'AE', 'pdMin'=>'26', 'pdMax'=>'27', 'ce'=>'75'),
			array('typeScale'=>'AE', 'pdMin'=>'28', 'pdMax'=>'29', 'ce'=>'77'),
			array('typeScale'=>'AE', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'79'),
			array('typeScale'=>'AE', 'pdMin'=>'31', 'pdMax'=>'32', 'ce'=>'80'),
			array('typeScale'=>'AE', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'81'),
			array('typeScale'=>'AE', 'pdMin'=>'34', 'pdMax'=>'35', 'ce'=>'82'),
			array('typeScale'=>'AE', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'85'),
			array('typeScale'=>'AE', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'86'),
			array('typeScale'=>'AE', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'90'),
			array('typeScale'=>'AE', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'94'),
			array('typeScale'=>'AE', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'99'),
			array('typeScale'=>'AE', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'102'),
			array('typeScale'=>'AE', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'104'),
			array('typeScale'=>'AE', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'109'),
			array('typeScale'=>'AE', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'112'),
			array('typeScale'=>'AE', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'119'),
			array('typeScale'=>'AR', 'pdMin'=>'0', 'pdMax'=>'23', 'ce'=>'65'),
			array('typeScale'=>'AR', 'pdMin'=>'24', 'pdMax'=>'26', 'ce'=>'68'),
			array('typeScale'=>'AR', 'pdMin'=>'27', 'pdMax'=>'28', 'ce'=>'71'),
			array('typeScale'=>'AR', 'pdMin'=>'29', 'pdMax'=>'30', 'ce'=>'73'),
			array('typeScale'=>'AR', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'78'),
			array('typeScale'=>'AR', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'81'),
			array('typeScale'=>'AR', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'82'),
			array('typeScale'=>'AR', 'pdMin'=>'34', 'pdMax'=>'35', 'ce'=>'86'),
			array('typeScale'=>'AR', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'88'),
			array('typeScale'=>'AR', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'92'),
			array('typeScale'=>'AR', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'96'),
			array('typeScale'=>'AR', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'99'),
			array('typeScale'=>'AR', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'102'),
			array('typeScale'=>'AR', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'106'),
			array('typeScale'=>'AR', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'110'),
			array('typeScale'=>'AR', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'113'),
			array('typeScale'=>'AR', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'117'),
			array('typeScale'=>'AR', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'128'),
			array('typeScale'=>'IN', 'pdMin'=>'0', 'pdMax'=>'14', 'ce'=>'65'),
			array('typeScale'=>'IN', 'pdMin'=>'15', 'pdMax'=>'17', 'ce'=>'68'),
			array('typeScale'=>'IN', 'pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'71'),
			array('typeScale'=>'IN', 'pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'73'),
			array('typeScale'=>'IN', 'pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'75'),
			array('typeScale'=>'IN', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'78'),
			array('typeScale'=>'IN', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'80'),
			array('typeScale'=>'IN', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'82'),
			array('typeScale'=>'IN', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'84'),
			array('typeScale'=>'IN', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'86'),
			array('typeScale'=>'IN', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'90'),
			array('typeScale'=>'IN', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'96'),
			array('typeScale'=>'IN', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'99'),
			array('typeScale'=>'IN', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'104'),
			array('typeScale'=>'IN', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'108'),
			array('typeScale'=>'IN', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'112'),
			array('typeScale'=>'IN', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'116'),
			array('typeScale'=>'IN', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'124'),
			array('typeScale'=>'IN', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'128'),
			array('typeScale'=>'IN', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'133'),
			array('typeScale'=>'RI', 'pdMin'=>'0', 'pdMax'=>'20', 'ce'=>'65'),
			array('typeScale'=>'RI', 'pdMin'=>'21', 'pdMax'=>'26', 'ce'=>'68'),
			array('typeScale'=>'RI', 'pdMin'=>'27', 'pdMax'=>'28', 'ce'=>'71'),
			array('typeScale'=>'RI', 'pdMin'=>'29', 'pdMax'=>'31', 'ce'=>'73'),
			array('typeScale'=>'RI', 'pdMin'=>'32', 'pdMax'=>'33', 'ce'=>'75'),
			array('typeScale'=>'RI', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'78'),
			array('typeScale'=>'RI', 'pdMin'=>'35', 'pdMax'=>'36', 'ce'=>'80'),
			array('typeScale'=>'RI', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'81'),
			array('typeScale'=>'RI', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'84'),
			array('typeScale'=>'RI', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'85'),
			array('typeScale'=>'RI', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'88'),
			array('typeScale'=>'RI', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'90'),
			array('typeScale'=>'RI', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'91'),
			array('typeScale'=>'RI', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'94'),
			array('typeScale'=>'RI', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'98'),
			array('typeScale'=>'RI', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'100'),
			array('typeScale'=>'RI', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'104'),
			array('typeScale'=>'RI', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'107'),
			array('typeScale'=>'RI', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'109'),
			array('typeScale'=>'RI', 'pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'111'),
			array('typeScale'=>'RI', 'pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'114'),
			array('typeScale'=>'RI', 'pdMin'=>'51', 'pdMax'=>'51', 'ce'=>'119'),
			array('typeScale'=>'RI', 'pdMin'=>'52', 'pdMax'=>'52', 'ce'=>'124'),
			array('typeScale'=>'RI', 'pdMin'=>'53', 'pdMax'=>'53', 'ce'=>'128'),
			array('typeScale'=>'RI', 'pdMin'=>'54', 'pdMax'=>'54', 'ce'=>'130'),
			array('typeScale'=>'RI', 'pdMin'=>'55', 'pdMax'=>'55', 'ce'=>'133'),
			array('typeScale'=>'RS', 'pdMin'=>'0', 'pdMax'=>'26', 'ce'=>'65'),
			array('typeScale'=>'RS', 'pdMin'=>'27', 'pdMax'=>'30', 'ce'=>'68'),
			array('typeScale'=>'RS', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'71'),
			array('typeScale'=>'RS', 'pdMin'=>'32', 'pdMax'=>'33', 'ce'=>'73'),
			array('typeScale'=>'RS', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'81'),
			array('typeScale'=>'RS', 'pdMin'=>'35', 'pdMax'=>'36', 'ce'=>'82'),
			array('typeScale'=>'RS', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'86'),
			array('typeScale'=>'RS', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'91'),
			array('typeScale'=>'RS', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'93'),
			array('typeScale'=>'RS', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'97'),
			array('typeScale'=>'RS', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'102'),
			array('typeScale'=>'RS', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'106'),
			array('typeScale'=>'RS', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'110'),
			array('typeScale'=>'RS', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'112'),
			array('typeScale'=>'RS', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'116'),
			array('typeScale'=>'RS', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'120'),
			array('typeScale'=>'RS', 'pdMin'=>'47', 'pdMax'=>'50', 'ce'=>'128'),			
			array('typeScale'=>'EM', 'pdMin'=>'0', 'pdMax'=>'19', 'ce'=>'65'),
			array('typeScale'=>'EM', 'pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'68'),
			array('typeScale'=>'EM', 'pdMin'=>'21', 'pdMax'=>'22', 'ce'=>'71'),
			array('typeScale'=>'EM', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'73'),
			array('typeScale'=>'EM', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'75'),
			array('typeScale'=>'EM', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'79'),			
			array('typeScale'=>'EM', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'85'),
			array('typeScale'=>'EM', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'89'),
			array('typeScale'=>'EM', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'92'),
			array('typeScale'=>'EM', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'97'),
			array('typeScale'=>'EM', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'101'),
			array('typeScale'=>'EM', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'106'),
			array('typeScale'=>'EM', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'109'),
			array('typeScale'=>'EM', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'112'),
			array('typeScale'=>'EM', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'115'),			
			array('typeScale'=>'EM', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'119'),
			array('typeScale'=>'EM', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'124'),
			array('typeScale'=>'EM', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'126'),
			array('typeScale'=>'EM', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'128'),
			array('typeScale'=>'EM', 'pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'130'),			
			array('typeScale'=>'SP', 'pdMin'=>'0', 'pdMax'=>'18', 'ce'=>'65'),
			array('typeScale'=>'SP', 'pdMin'=>'19', 'pdMax'=>'21', 'ce'=>'68'),
			array('typeScale'=>'SP', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'71'),
			array('typeScale'=>'SP', 'pdMin'=>'23', 'pdMax'=>'24', 'ce'=>'73'),		
			array('typeScale'=>'SP', 'pdMin'=>'25', 'pdMax'=>'26', 'ce'=>'75'),
			array('typeScale'=>'SP', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'78'),
			array('typeScale'=>'SP', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'81'),
			array('typeScale'=>'SP', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'82'),
			array('typeScale'=>'SP', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'87'),
			array('typeScale'=>'SP', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'90'),
			array('typeScale'=>'SP', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'94'),
			array('typeScale'=>'SP', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'98'),
			array('typeScale'=>'SP', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'101'),			
			array('typeScale'=>'SP', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'105'),
			array('typeScale'=>'SP', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'108'),
			array('typeScale'=>'SP', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'110'),
			array('typeScale'=>'SP', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'119'),
			array('typeScale'=>'SP', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'126'),
			array('typeScale'=>'SP', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'128'),			
			array('typeScale'=>'PR', 'pdMin'=>'0', 'pdMax'=>'20', 'ce'=>'65'),
			array('typeScale'=>'PR', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'68'),
			array('typeScale'=>'PR', 'pdMin'=>'22', 'pdMax'=>'24', 'ce'=>'71'),
			array('typeScale'=>'PR', 'pdMin'=>'25', 'pdMax'=>'28', 'ce'=>'73'),
			array('typeScale'=>'PR', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'75'),
			array('typeScale'=>'PR', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'77'),			
			array('typeScale'=>'PR', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'78'),
			array('typeScale'=>'PR', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'79'),
			array('typeScale'=>'PR', 'pdMin'=>'33', 'pdMax'=>'34', 'ce'=>'82'),
			array('typeScale'=>'PR', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'86'),
			array('typeScale'=>'PR', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'87'),
			array('typeScale'=>'PR', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'89'),
			array('typeScale'=>'PR', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'92'),
			array('typeScale'=>'PR', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'93'),
			array('typeScale'=>'PR', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'95'),
			array('typeScale'=>'PR', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'98'),
			array('typeScale'=>'PR', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'100'),
			array('typeScale'=>'PR', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'103'),
			array('typeScale'=>'PR', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'107'),
			array('typeScale'=>'PR', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'109'),
			array('typeScale'=>'PR', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'115'),
			array('typeScale'=>'PR', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'123'),
			array('typeScale'=>'PR', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'128'),
			array('typeScale'=>'PR', 'pdMin'=>'49', 'pdMax'=>'50', 'ce'=>'130'),			
			array('typeScale'=>'FL', 'pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),
			array('typeScale'=>'FL', 'pdMin'=>'17', 'pdMax'=>'20', 'ce'=>'68'),
			array('typeScale'=>'FL', 'pdMin'=>'21', 'pdMax'=>'22', 'ce'=>'71'),
			array('typeScale'=>'FL', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'73'),
			array('typeScale'=>'FL', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'82'),		
			array('typeScale'=>'FL', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'84'),
			array('typeScale'=>'FL', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'88'),
			array('typeScale'=>'FL', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'91'),
			array('typeScale'=>'FL', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'94'),
			array('typeScale'=>'FL', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'95'),
			array('typeScale'=>'FL', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'98'),
			array('typeScale'=>'FL', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'105'),
			array('typeScale'=>'FL', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'107'),
			array('typeScale'=>'FL', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'113'),
			array('typeScale'=>'FL', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'118'),			
			array('typeScale'=>'FL', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'122'),
			array('typeScale'=>'FL', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'124'),
			array('typeScale'=>'FL', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'126'),
			array('typeScale'=>'FL', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'130'),
			array('typeScale'=>'FL', 'pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'133'),
			array('typeScale'=>'TT', 'pdMin'=>'0', 'pdMax'=>'18', 'ce'=>'65'),
			array('typeScale'=>'TT', 'pdMin'=>'19', 'pdMax'=>'20', 'ce'=>'68'),
			array('typeScale'=>'TT', 'pdMin'=>'21', 'pdMax'=>'22', 'ce'=>'71'),
			array('typeScale'=>'TT', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'73'),
			array('typeScale'=>'TT', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'77'),
			array('typeScale'=>'TT', 'pdMin'=>'25', 'pdMax'=>'26', 'ce'=>'79'),
			array('typeScale'=>'TT', 'pdMin'=>'27', 'pdMax'=>'28', 'ce'=>'82'),
			array('typeScale'=>'TT', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'85'),
			array('typeScale'=>'TT', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'89'),	
			array('typeScale'=>'TT', 'pdMin'=>'31', 'pdMax'=>'32', 'ce'=>'93'),
			array('typeScale'=>'TT', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'96'),
			array('typeScale'=>'TT', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'97'),
			array('typeScale'=>'TT', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'100'),
			array('typeScale'=>'TT', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'102'),
			array('typeScale'=>'TT', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'107'),
			array('typeScale'=>'TT', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'112'),
			array('typeScale'=>'TT', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'115'),
			array('typeScale'=>'TT', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'117'),
			array('typeScale'=>'TT', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'119'),
			array('typeScale'=>'TT', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'126'),
			array('typeScale'=>'TT', 'pdMin'=>'43', 'pdMax'=>'45', 'ce'=>'133'),
			array('typeScale'=>'CI', 'pdMin'=>'0', 'pdMax'=>'21', 'ce'=>'65'),
			array('typeScale'=>'CI', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'68'),
			array('typeScale'=>'CI', 'pdMin'=>'23', 'pdMax'=>'24', 'ce'=>'73'),
			array('typeScale'=>'CI', 'pdMin'=>'25', 'pdMax'=>'26', 'ce'=>'75'),
			array('typeScale'=>'CI', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'78'),
			array('typeScale'=>'CI', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'79'),
			array('typeScale'=>'CI', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'82'),
			array('typeScale'=>'CI', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'83'),
			array('typeScale'=>'CI', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'85'),	
			array('typeScale'=>'CI', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'86'),
			array('typeScale'=>'CI', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'88'),
			array('typeScale'=>'CI', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'90'),
			array('typeScale'=>'CI', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'92'),
			array('typeScale'=>'CI', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'94'),
			array('typeScale'=>'CI', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'97'),
			array('typeScale'=>'CI', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'100'),
			array('typeScale'=>'CI', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'104'),
			array('typeScale'=>'CI', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'106'),
			array('typeScale'=>'CI', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'112'),
			array('typeScale'=>'CI', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'115'),
			array('typeScale'=>'CI', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'119'),
			array('typeScale'=>'CI', 'pdMin'=>'44', 'pdMax'=>'45', 'ce'=>'128'),			
			array('typeScale'=>'FE', 'pdMin'=>'0', 'pdMax'=>'23', 'ce'=>'65'),
			array('typeScale'=>'FE', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'68'),
			array('typeScale'=>'FE', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'71'),
			array('typeScale'=>'FE', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'73'),
			array('typeScale'=>'FE', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'78'),
			array('typeScale'=>'FE', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'79'),
			array('typeScale'=>'FE', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'81'),
			array('typeScale'=>'FE', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'83'),
			array('typeScale'=>'FE', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'85'),	
			array('typeScale'=>'FE', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'88'),
			array('typeScale'=>'FE', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'92'),
			array('typeScale'=>'FE', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'95'),
			array('typeScale'=>'FE', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'99'),
			array('typeScale'=>'FE', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'104'),
			array('typeScale'=>'FE', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'108'),
			array('typeScale'=>'FE', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'109'),
			array('typeScale'=>'FE', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'113'),
			array('typeScale'=>'FE', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'119'),
			array('typeScale'=>'FE', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'128'),
			array('typeScale'=>'FE', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'130'),
			array('typeScale'=>'FE', 'pdMin'=>'43', 'pdMax'=>'45', 'ce'=>'133'),			
			array('typeScale'=>'OP', 'pdMin'=>'0', 'pdMax'=>'16', 'ce'=>'65'),
			array('typeScale'=>'OP', 'pdMin'=>'17', 'pdMax'=>'20', 'ce'=>'68'),
			array('typeScale'=>'OP', 'pdMin'=>'21', 'pdMax'=>'23', 'ce'=>'71'),
			array('typeScale'=>'OP', 'pdMin'=>'24', 'pdMax'=>'25', 'ce'=>'73'),
			array('typeScale'=>'OP', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'75'),
			array('typeScale'=>'OP', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'77'),
			array('typeScale'=>'OP', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'78'),
			array('typeScale'=>'OP', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'81'),
			array('typeScale'=>'OP', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'85'),
			array('typeScale'=>'OP', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'90'),	
			array('typeScale'=>'OP', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'92'),
			array('typeScale'=>'OP', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'96'),
			array('typeScale'=>'OP', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'100'),
			array('typeScale'=>'OP', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'103'),
			array('typeScale'=>'OP', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'107'),
			array('typeScale'=>'OP', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'112'),
			array('typeScale'=>'OP', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'116'),
			array('typeScale'=>'OP', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'119'),
			array('typeScale'=>'OP', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'126'),
			array('typeScale'=>'CERA','pdMin'=>'40', 'pdMax'=>'93', 'ce'=>'65'),  
			array('typeScale'=>'CERA','pdMin'=>'94', 'pdMax'=>'108', 'ce'=>'68'), 
			array('typeScale'=>'CERA','pdMin'=>'109', 'pdMax'=>'115', 'ce'=>'71'), 
			array('typeScale'=>'CERA','pdMin'=>'116', 'pdMax'=>'124', 'ce'=>'73'), 
			array('typeScale'=>'CERA','pdMin'=>'125', 'pdMax'=>'126', 'ce'=>'75'), 
			array('typeScale'=>'CERA','pdMin'=>'127', 'pdMax'=>'128', 'ce'=>'77'), 
			array('typeScale'=>'CERA','pdMin'=>'129', 'pdMax'=>'133', 'ce'=>'79'), 
			array('typeScale'=>'CERA','pdMin'=>'134', 'pdMax'=>'135', 'ce'=>'80'), 
			array('typeScale'=>'CERA','pdMin'=>'136', 'pdMax'=>'138', 'ce'=>'81'), 
			array('typeScale'=>'CERA','pdMin'=>'139', 'pdMax'=>'143', 'ce'=>'82'), 
			array('typeScale'=>'CERA','pdMin'=>'144', 'pdMax'=>'145', 'ce'=>'85'), 
			array('typeScale'=>'CERA','pdMin'=>'146', 'pdMax'=>'148', 'ce'=>'86'), 
			array('typeScale'=>'CERA','pdMin'=>'149', 'pdMax'=>'149', 'ce'=>'87'), 
			array('typeScale'=>'CERA','pdMin'=>'150', 'pdMax'=>'150', 'ce'=>'88'), 
			array('typeScale'=>'CERA','pdMin'=>'151', 'pdMax'=>'152', 'ce'=>'89'), 
			array('typeScale'=>'CERA','pdMin'=>'153', 'pdMax'=>'154', 'ce'=>'90'), 
			array('typeScale'=>'CERA','pdMin'=>'155', 'pdMax'=>'156', 'ce'=>'92'), 
			array('typeScale'=>'CERA','pdMin'=>'157', 'pdMax'=>'157', 'ce'=>'93'), 
			array('typeScale'=>'CERA','pdMin'=>'158', 'pdMax'=>'158', 'ce'=>'95'), 
			array('typeScale'=>'CERA','pdMin'=>'159', 'pdMax'=>'160', 'ce'=>'96'), 
			array('typeScale'=>'CERA','pdMin'=>'161', 'pdMax'=>'161', 'ce'=>'97'), 
			array('typeScale'=>'CERA','pdMin'=>'162', 'pdMax'=>'162', 'ce'=>'98'), 
			array('typeScale'=>'CERA','pdMin'=>'163', 'pdMax'=>'164', 'ce'=>'100'), 
			array('typeScale'=>'CERA','pdMin'=>'165', 'pdMax'=>'165', 'ce'=>'101'), 
			array('typeScale'=>'CERA','pdMin'=>'166', 'pdMax'=>'166', 'ce'=>'102'), 
			array('typeScale'=>'CERA','pdMin'=>'167', 'pdMax'=>'167', 'ce'=>'103'),
			array('typeScale'=>'CERA','pdMin'=>'168', 'pdMax'=>'168', 'ce'=>'104'),
			array('typeScale'=>'CERA','pdMin'=>'169', 'pdMax'=>'169', 'ce'=>'105'),
			array('typeScale'=>'CERA','pdMin'=>'170', 'pdMax'=>'170', 'ce'=>'107'),
			array('typeScale'=>'CERA','pdMin'=>'171', 'pdMax'=>'171', 'ce'=>'108'),
			array('typeScale'=>'CERA','pdMin'=>'172', 'pdMax'=>'172', 'ce'=>'109'),
			array('typeScale'=>'CERA','pdMin'=>'173', 'pdMax'=>'174', 'ce'=>'111'),
			array('typeScale'=>'CERA','pdMin'=>'175', 'pdMax'=>'175', 'ce'=>'112'),
			array('typeScale'=>'CERA','pdMin'=>'176', 'pdMax'=>'176', 'ce'=>'114'),
			array('typeScale'=>'CERA','pdMin'=>'177', 'pdMax'=>'178', 'ce'=>'116'),
			array('typeScale'=>'CERA','pdMin'=>'179', 'pdMax'=>'180', 'ce'=>'118'),
			array('typeScale'=>'CERA','pdMin'=>'181', 'pdMax'=>'181', 'ce'=>'120'),
			array('typeScale'=>'CERA','pdMin'=>'182', 'pdMax'=>'182', 'ce'=>'122'),
			array('typeScale'=>'CERA','pdMin'=>'183', 'pdMax'=>'183', 'ce'=>'123'),
			array('typeScale'=>'CERA','pdMin'=>'184', 'pdMax'=>'184', 'ce'=>'124'),
			array('typeScale'=>'CERA','pdMin'=>'185', 'pdMax'=>'186', 'ce'=>'126'),
			array('typeScale'=>'CERA','pdMin'=>'187', 'pdMax'=>'188', 'ce'=>'128'),
			array('typeScale'=>'CERA','pdMin'=>'189', 'pdMax'=>'190', 'ce'=>'130'),
			array('typeScale'=>'CERA','pdMin'=>'191', 'pdMax'=>'200', 'ce'=>'133'),
			array('typeScale'=>'CEER','pdMin'=>'24', 'pdMax'=>'69', 'ce'=>'65'),    
			array('typeScale'=>'CEER','pdMin'=>'70', 'pdMax'=>'73', 'ce'=>'68'),    
			array('typeScale'=>'CEER','pdMin'=>'74', 'pdMax'=>'74', 'ce'=>'71'),    
			array('typeScale'=>'CEER','pdMin'=>'75', 'pdMax'=>'76', 'ce'=>'73'),    
			array('typeScale'=>'CEER','pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'75'),    
			array('typeScale'=>'CEER','pdMin'=>'78', 'pdMax'=>'79', 'ce'=>'77'),    
			array('typeScale'=>'CEER','pdMin'=>'80', 'pdMax'=>'80', 'ce'=>'79'),    
			array('typeScale'=>'CEER','pdMin'=>'81', 'pdMax'=>'82', 'ce'=>'80'),    
			array('typeScale'=>'CEER','pdMin'=>'83', 'pdMax'=>'83', 'ce'=>'81'),    
			array('typeScale'=>'CEER','pdMin'=>'84', 'pdMax'=>'84', 'ce'=>'82'),    
			array('typeScale'=>'CEER','pdMin'=>'85', 'pdMax'=>'85', 'ce'=>'83'),    
			array('typeScale'=>'CEER','pdMin'=>'86', 'pdMax'=>'86', 'ce'=>'85'),    
			array('typeScale'=>'CEER','pdMin'=>'87', 'pdMax'=>'87', 'ce'=>'86'),    
			array('typeScale'=>'CEER','pdMin'=>'88', 'pdMax'=>'88', 'ce'=>'87'),   
			array('typeScale'=>'CEER','pdMin'=>'89', 'pdMax'=>'89', 'ce'=>'88'), 
			array('typeScale'=>'CEER','pdMin'=>'90', 'pdMax'=>'90', 'ce'=>'90'),
			array('typeScale'=>'CEER','pdMin'=>'91', 'pdMax'=>'91', 'ce'=>'91'),
			array('typeScale'=>'CEER','pdMin'=>'92', 'pdMax'=>'92', 'ce'=>'92'), 
			array('typeScale'=>'CEER','pdMin'=>'93', 'pdMax'=>'93', 'ce'=>'94'), 
			array('typeScale'=>'CEER','pdMin'=>'94', 'pdMax'=>'94', 'ce'=>'97'), 
			array('typeScale'=>'CEER','pdMin'=>'95', 'pdMax'=>'95', 'ce'=>'99'), 
			array('typeScale'=>'CEER','pdMin'=>'96', 'pdMax'=>'96', 'ce'=>'101'), 
			array('typeScale'=>'CEER','pdMin'=>'97', 'pdMax'=>'97', 'ce'=>'102'), 
			array('typeScale'=>'CEER','pdMin'=>'98', 'pdMax'=>'98', 'ce'=>'104'), 
			array('typeScale'=>'CEER','pdMin'=>'99', 'pdMax'=>'99', 'ce'=>'106'), 
			array('typeScale'=>'CEER','pdMin'=>'100', 'pdMax'=>'100', 'ce'=>'108'), 
			array('typeScale'=>'CEER','pdMin'=>'101', 'pdMax'=>'101', 'ce'=>'109'), 
			array('typeScale'=>'CEER','pdMin'=>'102', 'pdMax'=>'102', 'ce'=>'111'), 
			array('typeScale'=>'CEER','pdMin'=>'103', 'pdMax'=>'103', 'ce'=>'112'), 
			array('typeScale'=>'CEER','pdMin'=>'104', 'pdMax'=>'104', 'ce'=>'114'), 
			array('typeScale'=>'CEER','pdMin'=>'105', 'pdMax'=>'106', 'ce'=>'115'), 
			array('typeScale'=>'CEER','pdMin'=>'107', 'pdMax'=>'107', 'ce'=>'118'), 
			array('typeScale'=>'CEER','pdMin'=>'108', 'pdMax'=>'108', 'ce'=>'120'), 
			array('typeScale'=>'CEER','pdMin'=>'109', 'pdMax'=>'109', 'ce'=>'124'), 
			array('typeScale'=>'CEER','pdMin'=>'110', 'pdMax'=>'110', 'ce'=>'126'), 
			array('typeScale'=>'CEER','pdMin'=>'111', 'pdMax'=>'112', 'ce'=>'128'), 
			array('typeScale'=>'CEER','pdMin'=>'113', 'pdMax'=>'120', 'ce'=>'133'), 
			array('typeScale'=>'CEAD','pdMin'=>'26', 'pdMax'=>'63', 'ce'=>'65'),   
			array('typeScale'=>'CEAD','pdMin'=>'64', 'pdMax'=>'68', 'ce'=>'68'),   
			array('typeScale'=>'CEAD','pdMin'=>'69', 'pdMax'=>'72', 'ce'=>'71'),   
			array('typeScale'=>'CEAD','pdMin'=>'73', 'pdMax'=>'78', 'ce'=>'73'),   
			array('typeScale'=>'CEAD','pdMin'=>'79', 'pdMax'=>'82', 'ce'=>'75'), 
			array('typeScale'=>'CEAD','pdMin'=>'83', 'pdMax'=>'85', 'ce'=>'77'),   
			array('typeScale'=>'CEAD','pdMin'=>'86', 'pdMax'=>'86', 'ce'=>'78'),   
			array('typeScale'=>'CEAD','pdMin'=>'87', 'pdMax'=>'89', 'ce'=>'82'),   
			array('typeScale'=>'CEAD','pdMin'=>'90', 'pdMax'=>'90', 'ce'=>'83'),   
			array('typeScale'=>'CEAD','pdMin'=>'91', 'pdMax'=>'91', 'ce'=>'84'),   
			array('typeScale'=>'CEAD','pdMin'=>'92', 'pdMax'=>'92', 'ce'=>'85'),   
			array('typeScale'=>'CEAD','pdMin'=>'93', 'pdMax'=>'93', 'ce'=>'86'),   
			array('typeScale'=>'CEAD','pdMin'=>'94', 'pdMax'=>'94', 'ce'=>'87'),   
			array('typeScale'=>'CEAD','pdMin'=>'95', 'pdMax'=>'95', 'ce'=>'88'),
			array('typeScale'=>'CEAD','pdMin'=>'96', 'pdMax'=>'97', 'ce'=>'89'),   
			array('typeScale'=>'CEAD','pdMin'=>'98', 'pdMax'=>'98', 'ce'=>'90'), 
			array('typeScale'=>'CEAD','pdMin'=>'99', 'pdMax'=>'99', 'ce'=>'92'), 
			array('typeScale'=>'CEAD','pdMin'=>'100', 'pdMax'=>'100', 'ce'=>'95'), 
			array('typeScale'=>'CEAD','pdMin'=>'101', 'pdMax'=>'102', 'ce'=>'96'), 
			array('typeScale'=>'CEAD','pdMin'=>'103', 'pdMax'=>'104', 'ce'=>'98'), 
			array('typeScale'=>'CEAD','pdMin'=>'105', 'pdMax'=>'105', 'ce'=>'101'),
			array('typeScale'=>'CEAD','pdMin'=>'106', 'pdMax'=>'106', 'ce'=>'102'),
			array('typeScale'=>'CEAD','pdMin'=>'107', 'pdMax'=>'107', 'ce'=>'104'),
			array('typeScale'=>'CEAD','pdMin'=>'108', 'pdMax'=>'108', 'ce'=>'106'),
			array('typeScale'=>'CEAD','pdMin'=>'109', 'pdMax'=>'110', 'ce'=>'109'),
			array('typeScale'=>'CEAD','pdMin'=>'111', 'pdMax'=>'111', 'ce'=>'111'),
			array('typeScale'=>'CEAD','pdMin'=>'112', 'pdMax'=>'113', 'ce'=>'115'),
			array('typeScale'=>'CEAD','pdMin'=>'114', 'pdMax'=>'114', 'ce'=>'116'),
			array('typeScale'=>'CEAD','pdMin'=>'115', 'pdMax'=>'115', 'ce'=>'118'),
			array('typeScale'=>'CEAD','pdMin'=>'116', 'pdMax'=>'116', 'ce'=>'121'),
			array('typeScale'=>'CEAD','pdMin'=>'117', 'pdMax'=>'117', 'ce'=>'122'),
			array('typeScale'=>'CEAD','pdMin'=>'118', 'pdMax'=>'119', 'ce'=>'124'),
			array('typeScale'=>'CEAD','pdMin'=>'120', 'pdMax'=>'120', 'ce'=>'126'),
			array('typeScale'=>'CEAD','pdMin'=>'121', 'pdMax'=>'122', 'ce'=>'128'), 
			array('typeScale'=>'CEAD','pdMin'=>'123', 'pdMax'=>'123', 'ce'=>'130'),
			array('typeScale'=>'CEAD','pdMin'=>'124', 'pdMax'=>'130', 'ce'=>'133'),
			array('typeScale'=>'CEMT','pdMin'=>'18', 'pdMax'=>'42', 'ce'=>'65'),  
			array('typeScale'=>'CEMT','pdMin'=>'43', 'pdMax'=>'47', 'ce'=>'68'),  
			array('typeScale'=>'CEMT','pdMin'=>'48', 'pdMax'=>'50', 'ce'=>'71'),       
			array('typeScale'=>'CEMT','pdMin'=>'51', 'pdMax'=>'52', 'ce'=>'73'),  
			array('typeScale'=>'CEMT','pdMin'=>'53', 'pdMax'=>'53', 'ce'=>'77'),  
			array('typeScale'=>'CEMT','pdMin'=>'54', 'pdMax'=>'54', 'ce'=>'78'),  
			array('typeScale'=>'CEMT','pdMin'=>'55', 'pdMax'=>'55', 'ce'=>'79'),  
			array('typeScale'=>'CEMT','pdMin'=>'56', 'pdMax'=>'56', 'ce'=>'81'),  
			array('typeScale'=>'CEMT','pdMin'=>'57', 'pdMax'=>'58', 'ce'=>'82'),  
			array('typeScale'=>'CEMT','pdMin'=>'59', 'pdMax'=>'59', 'ce'=>'85'),  
			array('typeScale'=>'CEMT','pdMin'=>'60', 'pdMax'=>'61', 'ce'=>'86'),  
			array('typeScale'=>'CEMT','pdMin'=>'62', 'pdMax'=>'62', 'ce'=>'87'),  
			array('typeScale'=>'CEMT','pdMin'=>'63', 'pdMax'=>'64', 'ce'=>'88'),  
			array('typeScale'=>'CEMT','pdMin'=>'65', 'pdMax'=>'65', 'ce'=>'90'),  
			array('typeScale'=>'CEMT','pdMin'=>'66', 'pdMax'=>'66', 'ce'=>'91'),  
			array('typeScale'=>'CEMT','pdMin'=>'67', 'pdMax'=>'68', 'ce'=>'92'),
			array('typeScale'=>'CEMT','pdMin'=>'69', 'pdMax'=>'69', 'ce'=>'95'),  
			array('typeScale'=>'CEMT','pdMin'=>'70', 'pdMax'=>'70', 'ce'=>'96'),  
			array('typeScale'=>'CEMT','pdMin'=>'71', 'pdMax'=>'71', 'ce'=>'98'),  
			array('typeScale'=>'CEMT','pdMin'=>'72', 'pdMax'=>'72', 'ce'=>'100'), 
			array('typeScale'=>'CEMT','pdMin'=>'73', 'pdMax'=>'74', 'ce'=>'103'), 
			array('typeScale'=>'CEMT','pdMin'=>'75', 'pdMax'=>'75', 'ce'=>'104'), 
			array('typeScale'=>'CEMT','pdMin'=>'76', 'pdMax'=>'76', 'ce'=>'106'), 
			array('typeScale'=>'CEMT','pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'110'), 
			array('typeScale'=>'CEMT','pdMin'=>'78', 'pdMax'=>'79', 'ce'=>'113'), 
			array('typeScale'=>'CEMT','pdMin'=>'80', 'pdMax'=>'80', 'ce'=>'117'), 
			array('typeScale'=>'CEMT','pdMin'=>'81', 'pdMax'=>'82', 'ce'=>'122'), 
			array('typeScale'=>'CEMT','pdMin'=>'83', 'pdMax'=>'83', 'ce'=>'124'),
			array('typeScale'=>'CEMT','pdMin'=>'84', 'pdMax'=>'84', 'ce'=>'126'), 
			array('typeScale'=>'CEMT','pdMin'=>'85', 'pdMax'=>'85', 'ce'=>'130'),
			array('typeScale'=>'CEMT','pdMin'=>'86', 'pdMax'=>'90', 'ce'=>'133'),
			array('typeScale'=>'CEAG','pdMin'=>'17', 'pdMax'=>'40', 'ce'=>'65'),  
			array('typeScale'=>'CEAG','pdMin'=>'41', 'pdMax'=>'46', 'ce'=>'68'),  
			array('typeScale'=>'CEAG','pdMin'=>'47', 'pdMax'=>'49', 'ce'=>'71'),  
			array('typeScale'=>'CEAG','pdMin'=>'50', 'pdMax'=>'51', 'ce'=>'73'),  
			array('typeScale'=>'CEAG','pdMin'=>'52', 'pdMax'=>'53', 'ce'=>'75'),  
			array('typeScale'=>'CEAG','pdMin'=>'54', 'pdMax'=>'55', 'ce'=>'77'),  
			array('typeScale'=>'CEAG','pdMin'=>'56', 'pdMax'=>'56', 'ce'=>'79'),  
			array('typeScale'=>'CEAG','pdMin'=>'57', 'pdMax'=>'57', 'ce'=>'81'),  
			array('typeScale'=>'CEAG','pdMin'=>'58', 'pdMax'=>'59', 'ce'=>'82'),  
			array('typeScale'=>'CEAG','pdMin'=>'60', 'pdMax'=>'60', 'ce'=>'83'),  
			array('typeScale'=>'CEAG','pdMin'=>'61', 'pdMax'=>'61', 'ce'=>'84'),  
			array('typeScale'=>'CEAG','pdMin'=>'62', 'pdMax'=>'62', 'ce'=>'86'),  
			array('typeScale'=>'CEAG','pdMin'=>'63', 'pdMax'=>'63', 'ce'=>'87'),  
			array('typeScale'=>'CEAG','pdMin'=>'64', 'pdMax'=>'64', 'ce'=>'89'),  
			array('typeScale'=>'CEAG','pdMin'=>'65', 'pdMax'=>'65', 'ce'=>'92'),  
			array('typeScale'=>'CEAG','pdMin'=>'66', 'pdMax'=>'66', 'ce'=>'93'),  
			array('typeScale'=>'CEAG','pdMin'=>'67', 'pdMax'=>'67', 'ce'=>'95'),  
			array('typeScale'=>'CEAG','pdMin'=>'68', 'pdMax'=>'68', 'ce'=>'97'),  
			array('typeScale'=>'CEAG','pdMin'=>'69', 'pdMax'=>'69', 'ce'=>'100'), 
			array('typeScale'=>'CEAG','pdMin'=>'70', 'pdMax'=>'70', 'ce'=>'103'), 
			array('typeScale'=>'CEAG','pdMin'=>'71', 'pdMax'=>'71', 'ce'=>'105'), 
			array('typeScale'=>'CEAG','pdMin'=>'72', 'pdMax'=>'72', 'ce'=>'106'),
			array('typeScale'=>'CEAG','pdMin'=>'73', 'pdMax'=>'73', 'ce'=>'109'),  
			array('typeScale'=>'CEAG','pdMin'=>'74', 'pdMax'=>'74', 'ce'=>'112'), 
			array('typeScale'=>'CEAG','pdMin'=>'75', 'pdMax'=>'75', 'ce'=>'115'), 
			array('typeScale'=>'CEAG','pdMin'=>'76', 'pdMax'=>'76', 'ce'=>'116'), 
			array('typeScale'=>'CEAG','pdMin'=>'77', 'pdMax'=>'78', 'ce'=>'123'), 
			array('typeScale'=>'CEAG','pdMin'=>'79', 'pdMax'=>'79', 'ce'=>'128'), 
			array('typeScale'=>'CEAG','pdMin'=>'80', 'pdMax'=>'80', 'ce'=>'130'), 
			array('typeScale'=>'CEAG','pdMin'=>'81', 'pdMax'=>'85', 'ce'=>'133'), 
			array('typeScale'=>'CETOTAL','pdMin'=>'117', 'pdMax'=>'300', 'ce'=>'65'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'301', 'pdMax'=>'333', 'ce'=>'68'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'334', 'pdMax'=>'357', 'ce'=>'71'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'358', 'pdMax'=>'381', 'ce'=>'73'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'382', 'pdMax'=>'387', 'ce'=>'75'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'388', 'pdMax'=>'388', 'ce'=>'77'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'389', 'pdMax'=>'391', 'ce'=>'78'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'392', 'pdMax'=>'394', 'ce'=>'79'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'395', 'pdMax'=>'396', 'ce'=>'80'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'397', 'pdMax'=>'399', 'ce'=>'81'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'400', 'pdMax'=>'411', 'ce'=>'82'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'412', 'pdMax'=>'418', 'ce'=>'83'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'419', 'pdMax'=>'425', 'ce'=>'84'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'426', 'pdMax'=>'428', 'ce'=>'85'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'429', 'pdMax'=>'434', 'ce'=>'86'),
			array('typeScale'=>'CETOTAL','pdMin'=>'435', 'pdMax'=>'437', 'ce'=>'87'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'438', 'pdMax'=>'439', 'ce'=>'88'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'440', 'pdMax'=>'441', 'ce'=>'89'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'442', 'pdMax'=>'444', 'ce'=>'90'),
			array('typeScale'=>'CETOTAL','pdMin'=>'445', 'pdMax'=>'445', 'ce'=>'91'),        
			array('typeScale'=>'CETOTAL','pdMin'=>'446', 'pdMax'=>'453', 'ce'=>'92'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'454', 'pdMax'=>'455', 'ce'=>'93'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'456', 'pdMax'=>'456', 'ce'=>'94'),
			array('typeScale'=>'CETOTAL','pdMin'=>'457', 'pdMax'=>'457', 'ce'=>'95'),
			array('typeScale'=>'CETOTAL','pdMin'=>'458', 'pdMax'=>'459', 'ce'=>'96'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'460', 'pdMax'=>'461', 'ce'=>'97'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'462', 'pdMax'=>'463', 'ce'=>'98'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'464', 'pdMax'=>'465', 'ce'=>'99'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'466', 'pdMax'=>'468', 'ce'=>'100'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'469', 'pdMax'=>'471', 'ce'=>'101'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'472', 'pdMax'=>'474', 'ce'=>'102'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'475', 'pdMax'=>'477', 'ce'=>'103'),    
			array('typeScale'=>'CETOTAL','pdMin'=>'478', 'pdMax'=>'480', 'ce'=>'104'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'481', 'pdMax'=>'483', 'ce'=>'105'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'484', 'pdMax'=>'486', 'ce'=>'106'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'487', 'pdMax'=>'489', 'ce'=>'107'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'490', 'pdMax'=>'491', 'ce'=>'108'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'492', 'pdMax'=>'494', 'ce'=>'109'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'495', 'pdMax'=>'495', 'ce'=>'110'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'496', 'pdMax'=>'497', 'ce'=>'111'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'498', 'pdMax'=>'503', 'ce'=>'112'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'504', 'pdMax'=>'504', 'ce'=>'113'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'505', 'pdMax'=>'505', 'ce'=>'115'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'506', 'pdMax'=>'507', 'ce'=>'116'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'508', 'pdMax'=>'509', 'ce'=>'117'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'510', 'pdMax'=>'515', 'ce'=>'118'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'516', 'pdMax'=>'516', 'ce'=>'120'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'517', 'pdMax'=>'517', 'ce'=>'121'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'518', 'pdMax'=>'518', 'ce'=>'122'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'519', 'pdMax'=>'519', 'ce'=>'123'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'520', 'pdMax'=>'526', 'ce'=>'124'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'527', 'pdMax'=>'529', 'ce'=>'126'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'530', 'pdMax'=>'536', 'ce'=>'128'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'537', 'pdMax'=>'540', 'ce'=>'130'),   
			array('typeScale'=>'CETOTAL','pdMin'=>'541', 'pdMax'=>'585', 'ce'=>'133'),   			
			
			
		);
         
        foreach ($lstStructure as $lst) {

            $objeto = new ICEM1620Baremo();
            $objeto->setTypeScale($lst['typeScale']);
            $objeto->setPdMin($lst['pdMin']);
            $objeto->setPdMax($lst['pdMax']);
            $objeto->setCE($lst['ce']);
            
            $manager->persist($objeto);                              
        }

        $manager->flush();    
	}
}
