<?php

namespace Jaxxes\TestICEBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture; 
use Symfony\Component\DependencyInjection\ContainerAwareInterface;

use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerInterface;

use Jaxxes\TestICEBundle\Entity\ICEM4100Baremo;

/**
 * Fixtures de la entidad Resume.
 * Crea el registro de la cabecera para Resume = Ficha del candidato
 */
 
// class Resumes implements FixtureInterface
 class ICEM4100Baremos extends AbstractFixture implements OrderedFixtureInterface
{
	
    public function getOrder()
    {
        return 4;
    }
    private $container;
    
    
    
    public function load(ObjectManager $manager)
    {
        $lstStructure = array(	
			array('typeScale'=>'IMP', 'pdMin'=>'0', 'pdMax'=>'12', 'ce'=>'65'),
			array('typeScale'=>'IMP', 'pdMin'=>'13', 'pdMax'=>'15', 'ce'=>'73'),
			array('typeScale'=>'IMP', 'pdMin'=>'16', 'pdMax'=>'16', 'ce'=>'75'),
			array('typeScale'=>'IMP', 'pdMin'=>'17', 'pdMax'=>'17', 'ce'=>'78'),
			array('typeScale'=>'IMP', 'pdMin'=>'18', 'pdMax'=>'18', 'ce'=>'81'),
			array('typeScale'=>'IMP', 'pdMin'=>'19', 'pdMax'=>'19', 'ce'=>'82'),
			array('typeScale'=>'IMP', 'pdMin'=>'20', 'pdMax'=>'20', 'ce'=>'83'),
			array('typeScale'=>'IMP', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'87'),
			array('typeScale'=>'IMP', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'91'),
			array('typeScale'=>'IMP', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'97'),
			array('typeScale'=>'IMP', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'100'),
			array('typeScale'=>'IMP', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'104'),
			array('typeScale'=>'IMP', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'109'),
			array('typeScale'=>'IMP', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'110'),
			array('typeScale'=>'IMP', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'112'),
			array('typeScale'=>'IMP', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'114'),
			array('typeScale'=>'IMP', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'115'),
			array('typeScale'=>'IMP', 'pdMin'=>'31', 'pdMax'=>'32', 'ce'=>'118'),
			array('typeScale'=>'IMP', 'pdMin'=>'33', 'pdMax'=>'34', 'ce'=>'120'),
			array('typeScale'=>'IMP', 'pdMin'=>'35', 'pdMax'=>'40', 'ce'=>'123'),
			array('typeScale'=>'IMN', 'pdMin'=>'0', 'pdMax'=>'7', 'ce'=>'65'),
			array('typeScale'=>'IMN', 'pdMin'=>'8', 'pdMax'=>'8', 'ce'=>'100'),
			array('typeScale'=>'IMN', 'pdMin'=>'9', 'pdMax'=>'9', 'ce'=>'103'),
			array('typeScale'=>'IMN', 'pdMin'=>'10', 'pdMax'=>'10', 'ce'=>'110'),
			array('typeScale'=>'IMN', 'pdMin'=>'11', 'pdMax'=>'11', 'ce'=>'111'),
			array('typeScale'=>'IMN', 'pdMin'=>'12', 'pdMax'=>'12', 'ce'=>'114'),
			array('typeScale'=>'IMN', 'pdMin'=>'13', 'pdMax'=>'13', 'ce'=>'118'),
			array('typeScale'=>'IMN', 'pdMin'=>'14', 'pdMax'=>'14', 'ce'=>'120'),
			array('typeScale'=>'IMN', 'pdMin'=>'15', 'pdMax'=>'35', 'ce'=>'128'),			
			array('typeScale'=>'CM', 'pdMin'=>'0', 'pdMax'=>'23', 'ce'=>'65'),
			array('typeScale'=>'CM', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'73'),
			array('typeScale'=>'CM', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'78'),
			array('typeScale'=>'CM', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'82'),
			array('typeScale'=>'CM', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'83'),
			array('typeScale'=>'CM', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'85'),
			array('typeScale'=>'CM', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'87'),
			array('typeScale'=>'CM', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'92'),
			array('typeScale'=>'CM', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'94'),
			array('typeScale'=>'CM', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'97'),
			array('typeScale'=>'CM', 'pdMin'=>'33', 'pdMax'=>'34', 'ce'=>'103'),
			array('typeScale'=>'CM', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'105'),
			array('typeScale'=>'CM', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'110'),
			array('typeScale'=>'CM', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'116'),
			array('typeScale'=>'CM', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'120'),
			array('typeScale'=>'CM', 'pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'128'),
			array('typeScale'=>'SE', 'pdMin'=>'0', 'pdMax'=>'20', 'ce'=>'65'),
			array('typeScale'=>'SE', 'pdMin'=>'21', 'pdMax'=>'21', 'ce'=>'75'),
			array('typeScale'=>'SE', 'pdMin'=>'22', 'pdMax'=>'22', 'ce'=>'78'),
			array('typeScale'=>'SE', 'pdMin'=>'23', 'pdMax'=>'23', 'ce'=>'81'),
			array('typeScale'=>'SE', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'87'),
			array('typeScale'=>'SE', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'89'),
			array('typeScale'=>'SE', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'94'),
			array('typeScale'=>'SE', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'96'),
			array('typeScale'=>'SE', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'103'),
			array('typeScale'=>'SE', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'107'),
			array('typeScale'=>'SE', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'109'),
			array('typeScale'=>'SE', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'111'),
			array('typeScale'=>'SE', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'114'),
			array('typeScale'=>'SE', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'118'),
			array('typeScale'=>'SE', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'123'),
			array('typeScale'=>'SE', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'128'),
			array('typeScale'=>'AE', 'pdMin'=>'0', 'pdMax'=>'31', 'ce'=>'65'),
			array('typeScale'=>'AE', 'pdMin'=>'32', 'pdMax'=>'33', 'ce'=>'73'),
			array('typeScale'=>'AE', 'pdMin'=>'34', 'pdMax'=>'35', 'ce'=>'81'),
			array('typeScale'=>'AE', 'pdMin'=>'36', 'pdMax'=>'37', 'ce'=>'85'),
			array('typeScale'=>'AE', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'87'),
			array('typeScale'=>'AE', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'90'),
			array('typeScale'=>'AE', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'96'),
			array('typeScale'=>'AE', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'100'),
			array('typeScale'=>'AE', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'103'),
			array('typeScale'=>'AE', 'pdMin'=>'43', 'pdMax'=>'44', 'ce'=>'104'),
			array('typeScale'=>'AE', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'111'),
			array('typeScale'=>'AR', 'pdMin'=>'0', 'pdMax'=>'31', 'ce'=>'65'),
			array('typeScale'=>'AR', 'pdMin'=>'32', 'pdMax'=>'33', 'ce'=>'78'),
			array('typeScale'=>'AR', 'pdMin'=>'34', 'pdMax'=>'35', 'ce'=>'81'),
			array('typeScale'=>'AR', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'87'),
			array('typeScale'=>'AR', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'91'),
			array('typeScale'=>'AR', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'92'),
			array('typeScale'=>'AR', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'94'),
			array('typeScale'=>'AR', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'95'),
			array('typeScale'=>'AR', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'100'),
			array('typeScale'=>'AR', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'104'),
			array('typeScale'=>'AR', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'109'),
			array('typeScale'=>'AR', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'112'),
			array('typeScale'=>'AR', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'120'),
			array('typeScale'=>'IN', 'pdMin'=>'0', 'pdMax'=>'22', 'ce'=>'65'),
			array('typeScale'=>'IN', 'pdMin'=>'23', 'pdMax'=>'24', 'ce'=>'73'),
			array('typeScale'=>'IN', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'78'),
			array('typeScale'=>'IN', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'81'),
			array('typeScale'=>'IN', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'83'),
			array('typeScale'=>'IN', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'90'),
			array('typeScale'=>'IN', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'96'),
			array('typeScale'=>'IN', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'107'),
			array('typeScale'=>'IN', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'110'),
			array('typeScale'=>'IN', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'112'),
			array('typeScale'=>'IN', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'118'),
			array('typeScale'=>'IN', 'pdMin'=>'34', 'pdMax'=>'35', 'ce'=>'123'),
			array('typeScale'=>'RI', 'pdMin'=>'0', 'pdMax'=>'36', 'ce'=>'65'),
			array('typeScale'=>'RI', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'77'),
			array('typeScale'=>'RI', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'78'),
			array('typeScale'=>'RI', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'83'),
			array('typeScale'=>'RI', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'88'),
			array('typeScale'=>'RI', 'pdMin'=>'41', 'pdMax'=>'43', 'ce'=>'90'),
			array('typeScale'=>'RI', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'91'),
			array('typeScale'=>'RI', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'92'),
			array('typeScale'=>'RI', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'96'),
			array('typeScale'=>'RI', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'100'),
			array('typeScale'=>'RI', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'103'),
			array('typeScale'=>'RI', 'pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'106'),
			array('typeScale'=>'RI', 'pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'110'),
			array('typeScale'=>'RI', 'pdMin'=>'51', 'pdMax'=>'51', 'ce'=>'114'),
			array('typeScale'=>'RI', 'pdMin'=>'52', 'pdMax'=>'52', 'ce'=>'116'),
			array('typeScale'=>'RI', 'pdMin'=>'53', 'pdMax'=>'53', 'ce'=>'118'),
			array('typeScale'=>'RI', 'pdMin'=>'54', 'pdMax'=>'55', 'ce'=>'123'),
			array('typeScale'=>'RS', 'pdMin'=>'0', 'pdMax'=>'35', 'ce'=>'65'),
			array('typeScale'=>'RS', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'73'),
			array('typeScale'=>'RS', 'pdMin'=>'37', 'pdMax'=>'38', 'ce'=>'81'),
			array('typeScale'=>'RS', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'85'),
			array('typeScale'=>'RS', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'89'),
			array('typeScale'=>'RS', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'90'),
			array('typeScale'=>'RS', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'94'),
			array('typeScale'=>'RS', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'101'),
			array('typeScale'=>'RS', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'105'),
			array('typeScale'=>'RS', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'109'),
			array('typeScale'=>'RS', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'110'),
			array('typeScale'=>'RS', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'112'),
			array('typeScale'=>'RS', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'113'),
			array('typeScale'=>'RS', 'pdMin'=>'49', 'pdMax'=>'50', 'ce'=>'120'),			
			array('typeScale'=>'EM', 'pdMin'=>'0', 'pdMax'=>'21', 'ce'=>'65'),
			array('typeScale'=>'EM', 'pdMin'=>'22', 'pdMax'=>'23', 'ce'=>'73'),
			array('typeScale'=>'EM', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'78'),
			array('typeScale'=>'EM', 'pdMin'=>'25', 'pdMax'=>'25', 'ce'=>'82'),
			array('typeScale'=>'EM', 'pdMin'=>'26', 'pdMax'=>'26', 'ce'=>'83'),
			array('typeScale'=>'EM', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'87'),
			array('typeScale'=>'EM', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'92'),
			array('typeScale'=>'EM', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'94'),
			array('typeScale'=>'EM', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'95'),
			array('typeScale'=>'EM', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'96'),
			array('typeScale'=>'EM', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'98'),
			array('typeScale'=>'EM', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'105'),
			array('typeScale'=>'EM', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'109'),
			array('typeScale'=>'EM', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'111'),
			array('typeScale'=>'EM', 'pdMin'=>'36', 'pdMax'=>'37', 'ce'=>'116'),
			array('typeScale'=>'EM', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'120'),
			array('typeScale'=>'EM', 'pdMin'=>'39', 'pdMax'=>'40', 'ce'=>'128'),		
			array('typeScale'=>'SP', 'pdMin'=>'0', 'pdMax'=>'26', 'ce'=>'65'),
			array('typeScale'=>'SP', 'pdMin'=>'27', 'pdMax'=>'29', 'ce'=>'75'),
			array('typeScale'=>'SP', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'81'),
			array('typeScale'=>'SP', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'82'),
			array('typeScale'=>'SP', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'90'),
			array('typeScale'=>'SP', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'91'),
			array('typeScale'=>'SP', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'92'),
			array('typeScale'=>'SP', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'96'),
			array('typeScale'=>'SP', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'104'),
			array('typeScale'=>'SP', 'pdMin'=>'37', 'pdMax'=>'38', 'ce'=>'107'),
			array('typeScale'=>'SP', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'114'),
			array('typeScale'=>'SP', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'128'),			
			array('typeScale'=>'PR', 'pdMin'=>'0', 'pdMax'=>'34', 'ce'=>'65'),
			array('typeScale'=>'PR', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'73'),
			array('typeScale'=>'PR', 'pdMin'=>'36', 'pdMax'=>'37', 'ce'=>'78'),
			array('typeScale'=>'PR', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'81'),
			array('typeScale'=>'PR', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'83'),
			array('typeScale'=>'PR', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'91'),
			array('typeScale'=>'PR', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'92'),
			array('typeScale'=>'PR', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'94'),
			array('typeScale'=>'PR', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'95'),
			array('typeScale'=>'PR', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'97'),
			array('typeScale'=>'PR', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'104'),
			array('typeScale'=>'PR', 'pdMin'=>'46', 'pdMax'=>'46', 'ce'=>'106'),
			array('typeScale'=>'PR', 'pdMin'=>'47', 'pdMax'=>'47', 'ce'=>'112'),
			array('typeScale'=>'PR', 'pdMin'=>'48', 'pdMax'=>'48', 'ce'=>'114'),
			array('typeScale'=>'PR', 'pdMin'=>'49', 'pdMax'=>'49', 'ce'=>'116'),
			array('typeScale'=>'PR', 'pdMin'=>'50', 'pdMax'=>'50', 'ce'=>'120'),			
			array('typeScale'=>'FL', 'pdMin'=>'0', 'pdMax'=>'23', 'ce'=>'65'),
			array('typeScale'=>'FL', 'pdMin'=>'24', 'pdMax'=>'24', 'ce'=>'73'),
			array('typeScale'=>'FL', 'pdMin'=>'25', 'pdMax'=>'26', 'ce'=>'78'),
			array('typeScale'=>'FL', 'pdMin'=>'27', 'pdMax'=>'27', 'ce'=>'85'),
			array('typeScale'=>'FL', 'pdMin'=>'28', 'pdMax'=>'28', 'ce'=>'89'),
			array('typeScale'=>'FL', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'90'),
			array('typeScale'=>'FL', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'94'),
			array('typeScale'=>'FL', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'95'),
			array('typeScale'=>'FL', 'pdMin'=>'32', 'pdMax'=>'33', 'ce'=>'97'),
			array('typeScale'=>'FL', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'101'),
			array('typeScale'=>'FL', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'105'),
			array('typeScale'=>'FL', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'114'),
			array('typeScale'=>'FL', 'pdMin'=>'37', 'pdMax'=>'38', 'ce'=>'120'),
			array('typeScale'=>'FL', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'121'),
			array('typeScale'=>'FL', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'128'),			
			array('typeScale'=>'TT', 'pdMin'=>'0', 'pdMax'=>'29', 'ce'=>'65'),
			array('typeScale'=>'TT', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'73'),
			array('typeScale'=>'TT', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'78'),
			array('typeScale'=>'TT', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'83'),
			array('typeScale'=>'TT', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'85'),
			array('typeScale'=>'TT', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'89'),
			array('typeScale'=>'TT', 'pdMin'=>'35', 'pdMax'=>'36', 'ce'=>'96'),
			array('typeScale'=>'TT', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'97'),
			array('typeScale'=>'TT', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'100'),
			array('typeScale'=>'TT', 'pdMin'=>'39', 'pdMax'=>'41', 'ce'=>'106'),
			array('typeScale'=>'TT', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'107'),
			array('typeScale'=>'TT', 'pdMin'=>'43', 'pdMax'=>'44', 'ce'=>'116'),
			array('typeScale'=>'TT', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'128'),			
			array('typeScale'=>'CI', 'pdMin'=>'0', 'pdMax'=>'27', 'ce'=>'65'),
			array('typeScale'=>'CI', 'pdMin'=>'28', 'pdMax'=>'29', 'ce'=>'73'),
			array('typeScale'=>'CI', 'pdMin'=>'30', 'pdMax'=>'31', 'ce'=>'78'),
			array('typeScale'=>'CI', 'pdMin'=>'32', 'pdMax'=>'33', 'ce'=>'81'),
			array('typeScale'=>'CI', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'83'),
			array('typeScale'=>'CI', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'87'),
			array('typeScale'=>'CI', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'90'),
			array('typeScale'=>'CI', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'91'),
			array('typeScale'=>'CI', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'94'),
			array('typeScale'=>'CI', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'98'),
			array('typeScale'=>'CI', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'100'),
			array('typeScale'=>'CI', 'pdMin'=>'41', 'pdMax'=>'41', 'ce'=>'103'),
			array('typeScale'=>'CI', 'pdMin'=>'42', 'pdMax'=>'42', 'ce'=>'110'),
			array('typeScale'=>'CI', 'pdMin'=>'43', 'pdMax'=>'43', 'ce'=>'111'),
			array('typeScale'=>'CI', 'pdMin'=>'44', 'pdMax'=>'44', 'ce'=>'116'),
			array('typeScale'=>'CI', 'pdMin'=>'45', 'pdMax'=>'45', 'ce'=>'123'),			
			array('typeScale'=>'FE', 'pdMin'=>'0', 'pdMax'=>'26', 'ce'=>'65'),
			array('typeScale'=>'FE', 'pdMin'=>'27', 'pdMax'=>'28', 'ce'=>'73'),
			array('typeScale'=>'FE', 'pdMin'=>'29', 'pdMax'=>'29', 'ce'=>'78'),
			array('typeScale'=>'FE', 'pdMin'=>'30', 'pdMax'=>'30', 'ce'=>'81'),
			array('typeScale'=>'FE', 'pdMin'=>'31', 'pdMax'=>'31', 'ce'=>'85'),
			array('typeScale'=>'FE', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'89'),
			array('typeScale'=>'FE', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'91'),
			array('typeScale'=>'FE', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'92'),
			array('typeScale'=>'FE', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'100'),
			array('typeScale'=>'FE', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'101'),
			array('typeScale'=>'FE', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'105'),
			array('typeScale'=>'FE', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'106'),
			array('typeScale'=>'FE', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'114'),
			array('typeScale'=>'FE', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'123'),
			array('typeScale'=>'FE', 'pdMin'=>'41', 'pdMax'=>'45', 'ce'=>'128'),			
			array('typeScale'=>'OP', 'pdMin'=>'0', 'pdMax'=>'29', 'ce'=>'65'),
			array('typeScale'=>'OP', 'pdMin'=>'30', 'pdMax'=>'31', 'ce'=>'73'),
			array('typeScale'=>'OP', 'pdMin'=>'32', 'pdMax'=>'32', 'ce'=>'86'),
			array('typeScale'=>'OP', 'pdMin'=>'33', 'pdMax'=>'33', 'ce'=>'87'),
			array('typeScale'=>'OP', 'pdMin'=>'34', 'pdMax'=>'34', 'ce'=>'91'),
			array('typeScale'=>'OP', 'pdMin'=>'35', 'pdMax'=>'35', 'ce'=>'94'),
			array('typeScale'=>'OP', 'pdMin'=>'36', 'pdMax'=>'36', 'ce'=>'96'),
			array('typeScale'=>'OP', 'pdMin'=>'37', 'pdMax'=>'37', 'ce'=>'104'),
			array('typeScale'=>'OP', 'pdMin'=>'38', 'pdMax'=>'38', 'ce'=>'106'),
			array('typeScale'=>'OP', 'pdMin'=>'39', 'pdMax'=>'39', 'ce'=>'109'),
			array('typeScale'=>'OP', 'pdMin'=>'40', 'pdMax'=>'40', 'ce'=>'112'),						
			array('typeScale'=>'CERA', 'pdMin'=>'40', 'pdMax'=>'147', 'ce'=>'65'),
			array('typeScale'=>'CERA', 'pdMin'=>'148', 'pdMax'=>'148', 'ce'=>'73'),
			array('typeScale'=>'CERA', 'pdMin'=>'149', 'pdMax'=>'149', 'ce'=>'78'),
			array('typeScale'=>'CERA', 'pdMin'=>'150', 'pdMax'=>'150', 'ce'=>'81'),
			array('typeScale'=>'CERA', 'pdMin'=>'151', 'pdMax'=>'151', 'ce'=>'82'),
			array('typeScale'=>'CERA', 'pdMin'=>'152', 'pdMax'=>'152', 'ce'=>'83'),
			array('typeScale'=>'CERA', 'pdMin'=>'153', 'pdMax'=>'153', 'ce'=>'88'),
			array('typeScale'=>'CERA', 'pdMin'=>'154', 'pdMax'=>'154', 'ce'=>'89'),
			array('typeScale'=>'CERA', 'pdMin'=>'155', 'pdMax'=>'157', 'ce'=>'90'),
			array('typeScale'=>'CERA', 'pdMin'=>'158', 'pdMax'=>'158', 'ce'=>'91'),
			array('typeScale'=>'CERA', 'pdMin'=>'159', 'pdMax'=>'160', 'ce'=>'92'),
			array('typeScale'=>'CERA', 'pdMin'=>'161', 'pdMax'=>'161', 'ce'=>'93'),
			array('typeScale'=>'CERA', 'pdMin'=>'162', 'pdMax'=>'164', 'ce'=>'94'),
			array('typeScale'=>'CERA', 'pdMin'=>'165', 'pdMax'=>'166', 'ce'=>'97'),
			array('typeScale'=>'CERA', 'pdMin'=>'167', 'pdMax'=>'168', 'ce'=>'100'),
			array('typeScale'=>'CERA', 'pdMin'=>'169', 'pdMax'=>'171', 'ce'=>'101'),
			array('typeScale'=>'CERA', 'pdMin'=>'172', 'pdMax'=>'173', 'ce'=>'102'),
			array('typeScale'=>'CERA', 'pdMin'=>'174', 'pdMax'=>'174', 'ce'=>'103'),
			array('typeScale'=>'CERA', 'pdMin'=>'175', 'pdMax'=>'175', 'ce'=>'104'),
			array('typeScale'=>'CERA', 'pdMin'=>'176', 'pdMax'=>'177', 'ce'=>'105'),
			array('typeScale'=>'CERA', 'pdMin'=>'178', 'pdMax'=>'178', 'ce'=>'106'),
			array('typeScale'=>'CERA', 'pdMin'=>'179', 'pdMax'=>'180', 'ce'=>'107'),
			array('typeScale'=>'CERA', 'pdMin'=>'181', 'pdMax'=>'181', 'ce'=>'109'),
			array('typeScale'=>'CERA', 'pdMin'=>'182', 'pdMax'=>'182', 'ce'=>'111'),
			array('typeScale'=>'CERA', 'pdMin'=>'183', 'pdMax'=>'183', 'ce'=>'116'),
			array('typeScale'=>'CERA', 'pdMin'=>'184', 'pdMax'=>'184', 'ce'=>'118'),
			array('typeScale'=>'CERA', 'pdMin'=>'185', 'pdMax'=>'185', 'ce'=>'119'),
			array('typeScale'=>'CERA', 'pdMin'=>'186', 'pdMax'=>'189', 'ce'=>'120'),
			array('typeScale'=>'CERA', 'pdMin'=>'190', 'pdMax'=>'190', 'ce'=>'121'),
			array('typeScale'=>'CERA', 'pdMin'=>'191', 'pdMax'=>'191', 'ce'=>'122'),
			array('typeScale'=>'CERA', 'pdMin'=>'192', 'pdMax'=>'193', 'ce'=>'123'),
			array('typeScale'=>'CERA', 'pdMin'=>'194', 'pdMax'=>'200', 'ce'=>'128'),			
			array('typeScale'=>'CEER', 'pdMin'=>'24', 'pdMax'=>'84', 'ce'=>'65'),
			array('typeScale'=>'CEER', 'pdMin'=>'85', 'pdMax'=>'85', 'ce'=>'73'),
			array('typeScale'=>'CEER', 'pdMin'=>'86', 'pdMax'=>'87', 'ce'=>'78'),
			array('typeScale'=>'CEER', 'pdMin'=>'88', 'pdMax'=>'88', 'ce'=>'81'),
			array('typeScale'=>'CEER', 'pdMin'=>'89', 'pdMax'=>'89', 'ce'=>'87'),
			array('typeScale'=>'CEER', 'pdMin'=>'90', 'pdMax'=>'90', 'ce'=>'88'),
			array('typeScale'=>'CEER', 'pdMin'=>'91', 'pdMax'=>'92', 'ce'=>'89'),
			array('typeScale'=>'CEER', 'pdMin'=>'93', 'pdMax'=>'95', 'ce'=>'90'),
			array('typeScale'=>'CEER', 'pdMin'=>'96', 'pdMax'=>'98', 'ce'=>'94'),
			array('typeScale'=>'CEER', 'pdMin'=>'99', 'pdMax'=>'99', 'ce'=>'95'),
			array('typeScale'=>'CEER', 'pdMin'=>'100', 'pdMax'=>'102', 'ce'=>'96'),
			array('typeScale'=>'CEER', 'pdMin'=>'103', 'pdMax'=>'104', 'ce'=>'100'),
			array('typeScale'=>'CEER', 'pdMin'=>'105', 'pdMax'=>'105', 'ce'=>'103'),
			array('typeScale'=>'CEER', 'pdMin'=>'106', 'pdMax'=>'106', 'ce'=>'105'),
			array('typeScale'=>'CEER', 'pdMin'=>'107', 'pdMax'=>'107', 'ce'=>'107'),
			array('typeScale'=>'CEER', 'pdMin'=>'108', 'pdMax'=>'108', 'ce'=>'111'),
			array('typeScale'=>'CEER', 'pdMin'=>'109', 'pdMax'=>'109', 'ce'=>'112'),
			array('typeScale'=>'CEER', 'pdMin'=>'110', 'pdMax'=>'110', 'ce'=>'114'),
			array('typeScale'=>'CEER', 'pdMin'=>'111', 'pdMax'=>'112', 'ce'=>'118'),
			array('typeScale'=>'CEER', 'pdMin'=>'113', 'pdMax'=>'113', 'ce'=>'120'),
			array('typeScale'=>'CEER', 'pdMin'=>'114', 'pdMax'=>'114', 'ce'=>'123'),
			array('typeScale'=>'CEER', 'pdMin'=>'115', 'pdMax'=>'115', 'ce'=>'126'),
			array('typeScale'=>'CEER', 'pdMin'=>'116', 'pdMax'=>'120', 'ce'=>'128'),	
			array('typeScale'=>'CEAD', 'pdMin'=>'26', 'pdMax'=>'90', 'ce'=>'65'),
			array('typeScale'=>'CEAD', 'pdMin'=>'91', 'pdMax'=>'92', 'ce'=>'78'),
			array('typeScale'=>'CEAD', 'pdMin'=>'93', 'pdMax'=>'93', 'ce'=>'79'),
			array('typeScale'=>'CEAD', 'pdMin'=>'94', 'pdMax'=>'95', 'ce'=>'81'),
			array('typeScale'=>'CEAD', 'pdMin'=>'96', 'pdMax'=>'96', 'ce'=>'82'),
			array('typeScale'=>'CEAD', 'pdMin'=>'97', 'pdMax'=>'100', 'ce'=>'83'),
			array('typeScale'=>'CEAD', 'pdMin'=>'101', 'pdMax'=>'101', 'ce'=>'85'),
			array('typeScale'=>'CEAD', 'pdMin'=>'102', 'pdMax'=>'103', 'ce'=>'88'),
			array('typeScale'=>'CEAD', 'pdMin'=>'104', 'pdMax'=>'106', 'ce'=>'89'),
			array('typeScale'=>'CEAD', 'pdMin'=>'107', 'pdMax'=>'107', 'ce'=>'94'),
			array('typeScale'=>'CEAD', 'pdMin'=>'108', 'pdMax'=>'108', 'ce'=>'95'),
			array('typeScale'=>'CEAD', 'pdMin'=>'109', 'pdMax'=>'109', 'ce'=>'98'),
			array('typeScale'=>'CEAD', 'pdMin'=>'110', 'pdMax'=>'111', 'ce'=>'100'),
			array('typeScale'=>'CEAD', 'pdMin'=>'112', 'pdMax'=>'112', 'ce'=>'101'),
			array('typeScale'=>'CEAD', 'pdMin'=>'113', 'pdMax'=>'114', 'ce'=>'103'),
			array('typeScale'=>'CEAD', 'pdMin'=>'115', 'pdMax'=>'115', 'ce'=>'105'), 
			array('typeScale'=>'CEAD', 'pdMin'=>'116', 'pdMax'=>'117', 'ce'=>'107'),
			array('typeScale'=>'CEAD', 'pdMin'=>'118', 'pdMax'=>'118', 'ce'=>'112'),
			array('typeScale'=>'CEAD', 'pdMin'=>'119', 'pdMax'=>'119', 'ce'=>'114'),
			array('typeScale'=>'CEAD', 'pdMin'=>'120', 'pdMax'=>'121', 'ce'=>'118'),
			array('typeScale'=>'CEAD', 'pdMin'=>'122', 'pdMax'=>'123', 'ce'=>'120'),
			array('typeScale'=>'CEAD', 'pdMin'=>'124', 'pdMax'=>'124', 'ce'=>'122'),
			array('typeScale'=>'CEAD', 'pdMin'=>'125', 'pdMax'=>'127', 'ce'=>'123'),
			array('typeScale'=>'CEAD', 'pdMin'=>'128', 'pdMax'=>'130', 'ce'=>'124'),
			array('typeScale'=>'CEMT', 'pdMin'=>'18', 'pdMax'=>'58', 'ce'=>'65'),
			array('typeScale'=>'CEMT', 'pdMin'=>'59', 'pdMax'=>'59', 'ce'=>'77'),
			array('typeScale'=>'CEMT', 'pdMin'=>'60', 'pdMax'=>'61', 'ce'=>'78'),
			array('typeScale'=>'CEMT', 'pdMin'=>'62', 'pdMax'=>'62', 'ce'=>'79'),
			array('typeScale'=>'CEMT', 'pdMin'=>'63', 'pdMax'=>'63', 'ce'=>'80'),
			array('typeScale'=>'CEMT', 'pdMin'=>'64', 'pdMax'=>'66', 'ce'=>'81'),
			array('typeScale'=>'CEMT', 'pdMin'=>'67', 'pdMax'=>'67', 'ce'=>'82'),
			array('typeScale'=>'CEMT', 'pdMin'=>'68', 'pdMax'=>'68', 'ce'=>'83'),
			array('typeScale'=>'CEMT', 'pdMin'=>'69', 'pdMax'=>'69', 'ce'=>'88'),
			array('typeScale'=>'CEMT', 'pdMin'=>'70', 'pdMax'=>'71', 'ce'=>'89'),
			array('typeScale'=>'CEMT', 'pdMin'=>'72', 'pdMax'=>'72', 'ce'=>'91'),
			array('typeScale'=>'CEMT', 'pdMin'=>'73', 'pdMax'=>'75', 'ce'=>'95'),
			array('typeScale'=>'CEMT', 'pdMin'=>'76', 'pdMax'=>'76', 'ce'=>'100'),
			array('typeScale'=>'CEMT', 'pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'101'),
			array('typeScale'=>'CEMT', 'pdMin'=>'78', 'pdMax'=>'79', 'ce'=>'103'),
			array('typeScale'=>'CEMT', 'pdMin'=>'79', 'pdMax'=>'80', 'ce'=>'104'),
			array('typeScale'=>'CEMT', 'pdMin'=>'80', 'pdMax'=>'81', 'ce'=>'105'),
			array('typeScale'=>'CEMT', 'pdMin'=>'81', 'pdMax'=>'82', 'ce'=>'107'),
			array('typeScale'=>'CEMT', 'pdMin'=>'82', 'pdMax'=>'83', 'ce'=>'109'),
			array('typeScale'=>'CEMT', 'pdMin'=>'83', 'pdMax'=>'84', 'ce'=>'110'),
			array('typeScale'=>'CEMT', 'pdMin'=>'84', 'pdMax'=>'85', 'ce'=>'111'),
			array('typeScale'=>'CEMT', 'pdMin'=>'86', 'pdMax'=>'86', 'ce'=>'114'),
			array('typeScale'=>'CEMT', 'pdMin'=>'87', 'pdMax'=>'87', 'ce'=>'116'),
			array('typeScale'=>'CEMT', 'pdMin'=>'88', 'pdMax'=>'88', 'ce'=>'120'),
			array('typeScale'=>'CEMT', 'pdMin'=>'89', 'pdMax'=>'90', 'ce'=>'128'),				
			array('typeScale'=>'CEAG', 'pdMin'=>'17', 'pdMax'=>'57', 'ce'=>'65'),
			array('typeScale'=>'CEAG', 'pdMin'=>'58', 'pdMax'=>'60', 'ce'=>'73'),
			array('typeScale'=>'CEAG', 'pdMin'=>'61', 'pdMax'=>'61', 'ce'=>'75'),
			array('typeScale'=>'CEAG', 'pdMin'=>'62', 'pdMax'=>'62', 'ce'=>'78'),
			array('typeScale'=>'CEAG', 'pdMin'=>'63', 'pdMax'=>'63', 'ce'=>'81'),
			array('typeScale'=>'CEAG', 'pdMin'=>'64', 'pdMax'=>'64', 'ce'=>'85'),
			array('typeScale'=>'CEAG', 'pdMin'=>'65', 'pdMax'=>'65', 'ce'=>'87'),
			array('typeScale'=>'CEAG', 'pdMin'=>'66', 'pdMax'=>'66', 'ce'=>'90'),
			array('typeScale'=>'CEAG', 'pdMin'=>'67', 'pdMax'=>'67', 'ce'=>'92'),
			array('typeScale'=>'CEAG', 'pdMin'=>'68', 'pdMax'=>'69', 'ce'=>'94'),
			array('typeScale'=>'CEAG', 'pdMin'=>'70', 'pdMax'=>'71', 'ce'=>'96'),
			array('typeScale'=>'CEAG', 'pdMin'=>'72', 'pdMax'=>'72', 'ce'=>'100'),
			array('typeScale'=>'CEAG', 'pdMin'=>'73', 'pdMax'=>'74', 'ce'=>'104'),
			array('typeScale'=>'CEAG', 'pdMin'=>'75', 'pdMax'=>'75', 'ce'=>'109'),
			array('typeScale'=>'CEAG', 'pdMin'=>'76', 'pdMax'=>'76', 'ce'=>'112'),
			array('typeScale'=>'CEAG', 'pdMin'=>'77', 'pdMax'=>'77', 'ce'=>'114'),
			array('typeScale'=>'CEAG', 'pdMin'=>'78', 'pdMax'=>'78', 'ce'=>'118'),
			array('typeScale'=>'CEAG', 'pdMin'=>'79', 'pdMax'=>'79', 'ce'=>'120'),
			array('typeScale'=>'CEAG', 'pdMin'=>'80', 'pdMax'=>'80', 'ce'=>'123'),
			array('typeScale'=>'CEAG', 'pdMin'=>'81', 'pdMax'=>'85', 'ce'=>'128'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'117', 'pdMax'=>'422', 'ce'=>'65'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'423', 'pdMax'=>'423', 'ce'=>'71'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'424', 'pdMax'=>'428', 'ce'=>'73'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'429', 'pdMax'=>'430', 'ce'=>'75'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'431', 'pdMax'=>'431', 'ce'=>'80'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'432', 'pdMax'=>'434', 'ce'=>'81'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'435', 'pdMax'=>'435', 'ce'=>'82'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'436', 'pdMax'=>'439', 'ce'=>'83'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'440', 'pdMax'=>'447', 'ce'=>'85'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'448', 'pdMax'=>'450', 'ce'=>'86'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'451', 'pdMax'=>'454', 'ce'=>'87'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'455', 'pdMax'=>'456', 'ce'=>'88'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'457', 'pdMax'=>'457', 'ce'=>'89'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'458', 'pdMax'=>'461', 'ce'=>'90'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'462', 'pdMax'=>'465', 'ce'=>'91'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'468', 'pdMax'=>'471', 'ce'=>'92'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'472', 'pdMax'=>'473', 'ce'=>'93'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'474', 'pdMax'=>'475', 'ce'=>'94'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'476', 'pdMax'=>'479', 'ce'=>'95'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'480', 'pdMax'=>'488', 'ce'=>'97'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'489', 'pdMax'=>'495', 'ce'=>'98'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'496', 'pdMax'=>'498', 'ce'=>'99'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'499', 'pdMax'=>'502', 'ce'=>'100'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'503', 'pdMax'=>'504', 'ce'=>'101'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'505', 'pdMax'=>'505', 'ce'=>'102'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'506', 'pdMax'=>'509', 'ce'=>'103'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'510', 'pdMax'=>'511', 'ce'=>'104'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'512', 'pdMax'=>'514', 'ce'=>'105'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'515', 'pdMax'=>'516', 'ce'=>'106'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'517', 'pdMax'=>'522', 'ce'=>'107'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'523', 'pdMax'=>'524', 'ce'=>'109'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'525', 'pdMax'=>'526', 'ce'=>'110'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'527', 'pdMax'=>'527', 'ce'=>'111'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'528', 'pdMax'=>'528', 'ce'=>'112'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'529', 'pdMax'=>'529', 'ce'=>'114'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'530', 'pdMax'=>'533', 'ce'=>'116'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'534', 'pdMax'=>'544', 'ce'=>'118'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'545', 'pdMax'=>'545', 'ce'=>'119'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'546', 'pdMax'=>'549', 'ce'=>'120'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'550', 'pdMax'=>'550', 'ce'=>'121'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'551', 'pdMax'=>'552', 'ce'=>'123'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'553', 'pdMax'=>'554', 'ce'=>'126'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'555', 'pdMax'=>'561', 'ce'=>'128'),
			array('typeScale'=>'CETOTAL', 'pdMin'=>'562', 'pdMax'=>'585', 'ce'=>'130'),
		
		);
         
        foreach ($lstStructure as $lst) {

            $objeto = new ICEM4100Baremo();
            $objeto->setTypeScale($lst['typeScale']);
            $objeto->setPdMin($lst['pdMin']);
            $objeto->setPdMax($lst['pdMax']);
            $objeto->setCE($lst['ce']);
            
            $manager->persist($objeto);                              
        }

        $manager->flush();    
	}
}
