parameters:
#    test_pma_sp.example.class: Jaxxes\TestPmaSPBundle\Example

services:
#    test_pma_sp.example:
#        class: %test_pma_sp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
