<?php

namespace Proxies\__CG__\Jaxxes\TestPmaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PmaPart4Group extends \Jaxxes\TestPmaBundle\Entity\PmaPart4Group implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Jaxxes\\TestPmaBundle\\Entity\\PmaPart4Group' . "\0" . 'id', '' . "\0" . 'Jaxxes\\TestPmaBundle\\Entity\\PmaPart4Group' . "\0" . 'groupInt', '' . "\0" . 'Jaxxes\\TestPmaBundle\\Entity\\PmaPart4Group' . "\0" . 'block', 'pmaPart4', '' . "\0" . 'Jaxxes\\TestPmaBundle\\Entity\\PmaPart4Group' . "\0" . 'pmaPart4Details');
        }

        return array('__isInitialized__', '' . "\0" . 'Jaxxes\\TestPmaBundle\\Entity\\PmaPart4Group' . "\0" . 'id', '' . "\0" . 'Jaxxes\\TestPmaBundle\\Entity\\PmaPart4Group' . "\0" . 'groupInt', '' . "\0" . 'Jaxxes\\TestPmaBundle\\Entity\\PmaPart4Group' . "\0" . 'block', 'pmaPart4', '' . "\0" . 'Jaxxes\\TestPmaBundle\\Entity\\PmaPart4Group' . "\0" . 'pmaPart4Details');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PmaPart4Group $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroupInt($groupInt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupInt', array($groupInt));

        return parent::setGroupInt($groupInt);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupInt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupInt', array());

        return parent::getGroupInt();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlock($block)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlock', array($block));

        return parent::setBlock($block);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlock', array());

        return parent::getBlock();
    }

    /**
     * {@inheritDoc}
     */
    public function setPmaPart4(\Jaxxes\TestPmaBundle\Entity\PmaPart4 $pmaPart4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPmaPart4', array($pmaPart4));

        return parent::setPmaPart4($pmaPart4);
    }

    /**
     * {@inheritDoc}
     */
    public function getPmaPart4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPmaPart4', array());

        return parent::getPmaPart4();
    }

    /**
     * {@inheritDoc}
     */
    public function getPmaPart4Details()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPmaPart4Details', array());

        return parent::getPmaPart4Details();
    }

    /**
     * {@inheritDoc}
     */
    public function addPmaPart4Details(\Jaxxes\TestPmaBundle\Entity\PmaPart4Detail $pmaPart4Details)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPmaPart4Details', array($pmaPart4Details));

        return parent::addPmaPart4Details($pmaPart4Details);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSource(\Jaxxes\TestPmaBundle\Entity\PmaPart4Detail $pmaPart4Details)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSource', array($pmaPart4Details));

        return parent::removeSource($pmaPart4Details);
    }

}
