parameters:
#    test_icesp.example.class: Jaxxes\TestICESPBundle\Example

services:
#    test_icesp.example:
#        class: %test_icesp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
