<?php

namespace Proxies\__CG__\Jaxxes\SeleccionProcesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ResultSPC extends \Jaxxes\SeleccionProcesBundle\Entity\ResultSPC implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'id', 'selectionProcessCandidate', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'commentGTB', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'commentPMA', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'commentICE', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'commentESC', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'strengths', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'improvementOpportunities', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'recommendation', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'finalResult');
        }

        return array('__isInitialized__', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'id', 'selectionProcessCandidate', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'commentGTB', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'commentPMA', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'commentICE', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'commentESC', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'strengths', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'improvementOpportunities', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'recommendation', '' . "\0" . 'Jaxxes\\SeleccionProcesBundle\\Entity\\ResultSPC' . "\0" . 'finalResult');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ResultSPC $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSelectionProcessCandidate(\Jaxxes\SeleccionProcesBundle\Entity\SelectionProcessCandidate $selectionProcessCandidate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSelectionProcessCandidate', array($selectionProcessCandidate));

        return parent::setSelectionProcessCandidate($selectionProcessCandidate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSelectionProcessCandidate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSelectionProcessCandidate', array());

        return parent::getSelectionProcessCandidate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentGTB($commentGTB)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentGTB', array($commentGTB));

        return parent::setCommentGTB($commentGTB);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentGTB()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentGTB', array());

        return parent::getCommentGTB();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentPMA($commentPMA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentPMA', array($commentPMA));

        return parent::setCommentPMA($commentPMA);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentPMA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentPMA', array());

        return parent::getCommentPMA();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentICE($commentICE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentICE', array($commentICE));

        return parent::setCommentICE($commentICE);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentICE()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentICE', array());

        return parent::getCommentICE();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentESC($commentESC)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentESC', array($commentESC));

        return parent::setCommentESC($commentESC);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentESC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentESC', array());

        return parent::getCommentESC();
    }

    /**
     * {@inheritDoc}
     */
    public function setStrengths($strengths)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStrengths', array($strengths));

        return parent::setStrengths($strengths);
    }

    /**
     * {@inheritDoc}
     */
    public function getStrengths()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStrengths', array());

        return parent::getStrengths();
    }

    /**
     * {@inheritDoc}
     */
    public function setImprovementOpportunities($improvementOpportunities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImprovementOpportunities', array($improvementOpportunities));

        return parent::setImprovementOpportunities($improvementOpportunities);
    }

    /**
     * {@inheritDoc}
     */
    public function getImprovementOpportunities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImprovementOpportunities', array());

        return parent::getImprovementOpportunities();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecommendation($recommendation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecommendation', array($recommendation));

        return parent::setRecommendation($recommendation);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecommendation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecommendation', array());

        return parent::getRecommendation();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinalResult($finalResult)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinalResult', array($finalResult));

        return parent::setFinalResult($finalResult);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinalResult()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinalResult', array());

        return parent::getFinalResult();
    }

}
